export {
  CONTACTS_QUERY_KEY,
  CONTACT_COLUMN_PREFERENCES_QUERY_KEY,
  CONTACTS_SAVED_REPORTS_QUERY_KEY,
  CONTACTS_GOOGLE_SYNC_QUERY_KEY,
  CONTACTS_METRICS_QUERY_KEY,
  CONTACTS_REPORT_ANALYTICS_QUERY_KEY,
  CONTACTS_WIDGET_AGGREGATES_QUERY_KEY,
  CONTACTS_DUPLICATES_QUERY_KEY,
  contactsPaginatedQueryKey,
  useContactsPaginated,
  fetchAllContactsForQuery,
  useContactsMetrics,
  useContactsReportAnalytics,
  useContactsWidgetAggregates,
  useContactsDuplicatePairs,
  contactsListQueryKey,
  contactDetailQueryKey,
  fetchContactById,
  useContacts,
  useContactById,
  useContactsByIds,
  useContactGoogleSyncConfig,
  useContactGoogleSyncMutations,
  useContactColumnPrefs,
  useContactColumnPrefsMutation,
  useContactsSavedReports,
  useContactsSavedReportMutations,
  useContactsCollection,
  useContactsCollectionState,
  type ContactsPaginatedParams,
  type ContactsReportAnalyticsParams,
  type ContactsReportAnalyticsResult,
  type ContactsWidgetAggregateWidgetInput,
  type ContactsDuplicatesParams,
  type UseContactsCollectionResult,
} from '@/tenant/features/contacts/hooks/useContactsQueries';

export {
  useInvalidateContactsQueries,
  useContactMutations,
} from '@/tenant/features/contacts/hooks/useContactMutations';
