import type { FieldType } from '../schemas/dynamicFormSchemas.js';

export interface FieldTypeMeta {
  type: FieldType;
  displayLabelKey: string;
  descriptionKey: string;
  hasOptions: boolean;
  isNumeric: boolean;
  supportsMinMax: boolean;
  supportsMask: boolean;
  supportsFileRules: boolean;
}

export const FIELD_TYPES_META: Record<FieldType, FieldTypeMeta> = {
  text: {
    type: 'text',
    displayLabelKey: 'fieldTypes.text.label',
    descriptionKey: 'fieldTypes.text.description',
    hasOptions: false,
    isNumeric: false,
    supportsMinMax: false,
    supportsMask: true,
    supportsFileRules: false,
  },
  textarea: {
    type: 'textarea',
    displayLabelKey: 'fieldTypes.textarea.label',
    descriptionKey: 'fieldTypes.textarea.description',
    hasOptions: false,
    isNumeric: false,
    supportsMinMax: false,
    supportsMask: false,
    supportsFileRules: false,
  },
  number: {
    type: 'number',
    displayLabelKey: 'fieldTypes.number.label',
    descriptionKey: 'fieldTypes.number.description',
    hasOptions: false,
    isNumeric: true,
    supportsMinMax: true,
    supportsMask: true,
    supportsFileRules: false,
  },
  date: {
    type: 'date',
    displayLabelKey: 'fieldTypes.date.label',
    descriptionKey: 'fieldTypes.date.description',
    hasOptions: false,
    isNumeric: false,
    supportsMinMax: false,
    supportsMask: false,
    supportsFileRules: false,
  },
  url: {
    type: 'url',
    displayLabelKey: 'fieldTypes.url.label',
    descriptionKey: 'fieldTypes.url.description',
    hasOptions: false,
    isNumeric: false,
    supportsMinMax: false,
    supportsMask: false,
    supportsFileRules: false,
  },
  email: {
    type: 'email',
    displayLabelKey: 'fieldTypes.email.label',
    descriptionKey: 'fieldTypes.email.description',
    hasOptions: false,
    isNumeric: false,
    supportsMinMax: false,
    supportsMask: false,
    supportsFileRules: false,
  },
  select: {
    type: 'select',
    displayLabelKey: 'fieldTypes.select.label',
    descriptionKey: 'fieldTypes.select.description',
    hasOptions: true,
    isNumeric: false,
    supportsMinMax: false,
    supportsMask: false,
    supportsFileRules: false,
  },
  tags: {
    type: 'tags',
    displayLabelKey: 'fieldTypes.tags.label',
    descriptionKey: 'fieldTypes.tags.description',
    hasOptions: true,
    isNumeric: false,
    supportsMinMax: false,
    supportsMask: false,
    supportsFileRules: false,
  },
  boolean: {
    type: 'boolean',
    displayLabelKey: 'fieldTypes.boolean.label',
    descriptionKey: 'fieldTypes.boolean.description',
    hasOptions: false,
    isNumeric: false,
    supportsMinMax: false,
    supportsMask: false,
    supportsFileRules: false,
  },
  currency: {
    type: 'currency',
    displayLabelKey: 'fieldTypes.currency.label',
    descriptionKey: 'fieldTypes.currency.description',
    hasOptions: false,
    isNumeric: true,
    supportsMinMax: true,
    supportsMask: true,
    supportsFileRules: false,
  },
  phone: {
    type: 'phone',
    displayLabelKey: 'fieldTypes.phone.label',
    descriptionKey: 'fieldTypes.phone.description',
    hasOptions: false,
    isNumeric: false,
    supportsMinMax: false,
    supportsMask: true,
    supportsFileRules: false,
  },
  file: {
    type: 'file',
    displayLabelKey: 'fieldTypes.file.label',
    descriptionKey: 'fieldTypes.file.description',
    hasOptions: false,
    isNumeric: false,
    supportsMinMax: false,
    supportsMask: false,
    supportsFileRules: true,
  },
  rating: {
    type: 'rating',
    displayLabelKey: 'fieldTypes.rating.label',
    descriptionKey: 'fieldTypes.rating.description',
    hasOptions: false,
    isNumeric: true,
    supportsMinMax: false,
    supportsMask: false,
    supportsFileRules: false,
  },
  datetime: {
    type: 'datetime',
    displayLabelKey: 'fieldTypes.datetime.label',
    descriptionKey: 'fieldTypes.datetime.description',
    hasOptions: false,
    isNumeric: false,
    supportsMinMax: false,
    supportsMask: false,
    supportsFileRules: false,
  },
};
