import dotenv from 'dotenv';
dotenv.config({ path: '.env' });
import { initDb } from '../db/database.js';
import { getDb } from '../db/dbClient.js';
import { workspaces } from '../db/schema.js';
import { bulkSaveContacts } from '../db/repositories/contactRepository.js';
import type { Contact } from '@mms/shared';

const DUMMY_CONTACTS: Omit<Contact, 'id'>[] = [
  {
    name: 'Muhammad Ali Khan',
    firstName: 'Muhammad Ali',
    lastName: 'Khan',
    gender: 'male',
    dob: '1985-03-15',
    phones: [{ id: 'ph-1', label: 'mobile', number: '+923001234501' }],
    emails: [{ id: 'em-1', label: 'personal', address: 'ali.khan@example.com' }],
    addresses: [{ id: 'ad-1', label: 'home', line1: 'House 42, Block C, Gulberg III', city: 'Lahore', state: 'Punjab', country: 'Pakistan' }],
    city: 'Lahore',
    state: 'Punjab',
    country: 'Pakistan',
    tag: 'Parent',
    notes: 'Father of Quran student Ahmed Ali Khan. Active volunteer.',
    isSyed: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Fatima Zahra Hashmi',
    firstName: 'Fatima Zahra',
    lastName: 'Hashmi',
    gender: 'female',
    dob: '1990-07-22',
    phones: [{ id: 'ph-2', label: 'mobile', number: '+923019876502' }],
    emails: [{ id: 'em-2', label: 'work', address: 'fatima.hashmi@example.com' }],
    addresses: [{ id: 'ad-2', label: 'home', line1: 'Flat 4B, Clifton Block 2', city: 'Karachi', state: 'Sindh', country: 'Pakistan' }],
    city: 'Karachi',
    state: 'Sindh',
    country: 'Pakistan',
    tag: 'Teacher',
    notes: 'Tajweed and Arabic Grammar instructor.',
    isSyed: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Usman Ahmed',
    firstName: 'Usman',
    lastName: 'Ahmed',
    gender: 'male',
    dob: '1994-11-05',
    phones: [{ id: 'ph-3', label: 'mobile', number: '+923125550103' }],
    emails: [{ id: 'em-3', label: 'personal', address: 'usman.ahmed@example.com' }],
    addresses: [{ id: 'ad-3', label: 'home', line1: 'Street 15, Sector F-8/3', city: 'Islamabad', state: 'ICT', country: 'Pakistan' }],
    city: 'Islamabad',
    state: 'ICT',
    country: 'Pakistan',
    tag: 'Staff',
    notes: 'Administrator for student admissions and records.',
    isSyed: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Ayesha Siddiqua',
    firstName: 'Ayesha',
    lastName: 'Siddiqua',
    gender: 'female',
    dob: '1988-02-18',
    phones: [{ id: 'ph-4', label: 'mobile', number: '+923334440104' }],
    emails: [{ id: 'em-4', label: 'personal', address: 'ayesha.s@example.com' }],
    addresses: [{ id: 'ad-4', label: 'home', line1: 'House 112, Satellite Town', city: 'Rawalpindi', state: 'Punjab', country: 'Pakistan' }],
    city: 'Rawalpindi',
    state: 'Punjab',
    country: 'Pakistan',
    tag: 'Parent',
    notes: 'Mother of two enrolled female students.',
    isSyed: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Zayd Ibn Malik',
    firstName: 'Zayd',
    lastName: 'Malik',
    gender: 'male',
    dob: '1998-09-30',
    phones: [{ id: 'ph-5', label: 'mobile', number: '+923218880105' }],
    emails: [{ id: 'em-5', label: 'personal', address: 'zayd.malik@example.com' }],
    addresses: [{ id: 'ad-5', label: 'home', line1: 'Madina Town, Main Bazar', city: 'Faisalabad', state: 'Punjab', country: 'Pakistan' }],
    city: 'Faisalabad',
    state: 'Punjab',
    country: 'Pakistan',
    tag: 'Student',
    notes: 'Advanced Hifz student completing 25th Juz.',
    isSyed: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Maryam Nawaz',
    firstName: 'Maryam',
    lastName: 'Nawaz',
    gender: 'female',
    dob: '1996-04-12',
    phones: [{ id: 'ph-6', label: 'mobile', number: '+923027770106' }],
    emails: [{ id: 'em-6', label: 'work', address: 'maryam.n@example.com' }],
    addresses: [{ id: 'ad-6', label: 'home', line1: 'Boson Road, Near University', city: 'Multan', state: 'Punjab', country: 'Pakistan' }],
    city: 'Multan',
    state: 'Punjab',
    country: 'Pakistan',
    tag: 'Staff',
    notes: 'Financial auditor and accounting coordinator.',
    isSyed: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Tariq Mahmood',
    firstName: 'Tariq',
    lastName: 'Mahmood',
    gender: 'male',
    dob: '1980-01-25',
    phones: [{ id: 'ph-7', label: 'mobile', number: '+923459990107' }],
    emails: [{ id: 'em-7', label: 'personal', address: 'tariq.mahmood@example.com' }],
    addresses: [{ id: 'ad-7', label: 'home', line1: 'University Town, Canal Bank Road', city: 'Peshawar', state: 'KPK', country: 'Pakistan' }],
    city: 'Peshawar',
    state: 'KPK',
    country: 'Pakistan',
    tag: 'Donor',
    notes: 'Regular sponsor for orphan student scholarships.',
    isSyed: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Zainab Bibi',
    firstName: 'Zainab',
    lastName: 'Bibi',
    gender: 'female',
    dob: '1993-08-14',
    phones: [{ id: 'ph-8', label: 'mobile', number: '+923061110108' }],
    emails: [{ id: 'em-8', label: 'personal', address: 'zainab.bibi@example.com' }],
    addresses: [{ id: 'ad-8', label: 'home', line1: 'Model Town, Near Park', city: 'Gujranwala', state: 'Punjab', country: 'Pakistan' }],
    city: 'Gujranwala',
    state: 'Punjab',
    country: 'Pakistan',
    tag: 'Parent',
    notes: 'Guardian contact for student Hafsa Bibi.',
    isSyed: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Bilal Hassan',
    firstName: 'Bilal',
    lastName: 'Hassan',
    gender: 'male',
    dob: '1991-12-03',
    phones: [{ id: 'ph-9', label: 'mobile', number: '+923152220109' }],
    emails: [{ id: 'em-9', label: 'work', address: 'bilal.hassan@example.com' }],
    addresses: [{ id: 'ad-9', label: 'home', line1: 'Paris Road, Near Square', city: 'Sialkot', state: 'Punjab', country: 'Pakistan' }],
    city: 'Sialkot',
    state: 'Punjab',
    country: 'Pakistan',
    tag: 'Teacher',
    notes: 'Hadith studies and Fiqh teacher.',
    isSyed: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Hafsa Khalid',
    firstName: 'Hafsa',
    lastName: 'Khalid',
    gender: 'female',
    dob: '1999-06-20',
    phones: [{ id: 'ph-10', label: 'mobile', number: '+923043330110' }],
    emails: [{ id: 'em-10', label: 'personal', address: 'hafsa.khalid@example.com' }],
    addresses: [{ id: 'ad-10', label: 'home', line1: 'Latifabad Unit 6', city: 'Hyderabad', state: 'Sindh', country: 'Pakistan' }],
    city: 'Hyderabad',
    state: 'Sindh',
    country: 'Pakistan',
    tag: 'Student',
    notes: 'Enrolled in Morning Tajweed Certificate course.',
    isSyed: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Hamza Raza Syed',
    firstName: 'Hamza Raza',
    lastName: 'Syed',
    gender: 'male',
    dob: '1987-10-10',
    phones: [{ id: 'ph-11', label: 'mobile', number: '+923314440111' }],
    emails: [{ id: 'em-11', label: 'personal', address: 'hamza.syed@example.com' }],
    addresses: [{ id: 'ad-11', label: 'home', line1: 'Jinnah Road, Cantonment', city: 'Quetta', state: 'Balochistan', country: 'Pakistan' }],
    city: 'Quetta',
    state: 'Balochistan',
    country: 'Pakistan',
    tag: 'Parent',
    notes: 'Parent of Syed Ali Raza (Hifz class).',
    isSyed: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Sara Ibrahim',
    firstName: 'Sara',
    lastName: 'Ibrahim',
    gender: 'female',
    dob: '1995-03-08',
    phones: [{ id: 'ph-12', label: 'mobile', number: '+923085550112' }],
    emails: [{ id: 'em-12', label: 'work', address: 'sara.ibrahim@example.com' }],
    addresses: [{ id: 'ad-12', label: 'home', line1: 'One Unit Staff Colony', city: 'Bahawalpur', state: 'Punjab', country: 'Pakistan' }],
    city: 'Bahawalpur',
    state: 'Punjab',
    country: 'Pakistan',
    tag: 'Staff',
    notes: 'IT and Database Administrator.',
    isSyed: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Abdullah Al-Mansoor',
    firstName: 'Abdullah',
    lastName: 'Al-Mansoor',
    gender: 'male',
    dob: '1982-05-19',
    phones: [{ id: 'ph-13', label: 'mobile', number: '+923236660113' }],
    emails: [{ id: 'em-13', label: 'personal', address: 'mansoor@example.com' }],
    addresses: [{ id: 'ad-13', label: 'home', line1: 'Satellite Town, Block A', city: 'Sargodha', state: 'Punjab', country: 'Pakistan' }],
    city: 'Sargodha',
    state: 'Punjab',
    country: 'Pakistan',
    tag: 'Donor',
    notes: 'Major benefactor for new madrasa library building.',
    isSyed: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Khadija Tul Kubra',
    firstName: 'Khadija',
    lastName: 'Kubra',
    gender: 'female',
    dob: '1989-09-17',
    phones: [{ id: 'ph-14', label: 'mobile', number: '+923147770114' }],
    emails: [{ id: 'em-14', label: 'work', address: 'khadija.kubra@example.com' }],
    addresses: [{ id: 'ad-14', label: 'home', line1: 'Military Road', city: 'Sukkur', state: 'Sindh', country: 'Pakistan' }],
    city: 'Sukkur',
    state: 'Sindh',
    country: 'Pakistan',
    tag: 'Teacher',
    notes: 'Head Teacher for Female Arabic Department.',
    isSyed: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Omar Farooq',
    firstName: 'Omar',
    lastName: 'Farooq',
    gender: 'male',
    dob: '1997-11-28',
    phones: [{ id: 'ph-15', label: 'mobile', number: '+923058880115' }],
    emails: [{ id: 'em-15', label: 'personal', address: 'omar.farooq@example.com' }],
    addresses: [{ id: 'ad-15', label: 'home', line1: 'Mansehra Road', city: 'Abbottabad', state: 'KPK', country: 'Pakistan' }],
    city: 'Abbottabad',
    state: 'KPK',
    country: 'Pakistan',
    tag: 'Student',
    notes: 'Senior Dars-e-Nizami student.',
    isSyed: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Sumaira Yasin',
    firstName: 'Sumaira',
    lastName: 'Yasin',
    gender: 'female',
    dob: '1992-01-14',
    phones: [{ id: 'ph-16', label: 'mobile', number: '+923349990116' }],
    emails: [{ id: 'em-16', label: 'personal', address: 'sumaira.yasin@example.com' }],
    addresses: [{ id: 'ad-16', label: 'home', line1: 'Baghdada Sector B', city: 'Mardan', state: 'KPK', country: 'Pakistan' }],
    city: 'Mardan',
    state: 'KPK',
    country: 'Pakistan',
    tag: 'Parent',
    notes: 'Mother of student Bilal Yasin.',
    isSyed: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Mustafa Kamal',
    firstName: 'Mustafa',
    lastName: 'Kamal',
    gender: 'male',
    dob: '1986-04-05',
    phones: [{ id: 'ph-17', label: 'mobile', number: '+923071230117' }],
    emails: [{ id: 'em-17', label: 'work', address: 'mustafa.kamal@example.com' }],
    addresses: [{ id: 'ad-17', label: 'home', line1: 'VIP Road', city: 'Larkana', state: 'Sindh', country: 'Pakistan' }],
    city: 'Larkana',
    state: 'Sindh',
    country: 'Pakistan',
    tag: 'Staff',
    notes: 'Logistics and Facilities Manager.',
    isSyed: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Amina Bukhari',
    firstName: 'Amina',
    lastName: 'Bukhari',
    gender: 'female',
    dob: '1994-07-31',
    phones: [{ id: 'ph-18', label: 'mobile', number: '+923164560118' }],
    emails: [{ id: 'em-18', label: 'work', address: 'amina.bukhari@example.com' }],
    addresses: [{ id: 'ad-18', label: 'home', line1: 'Bhimber Road', city: 'Gujrat', state: 'Punjab', country: 'Pakistan' }],
    city: 'Gujrat',
    state: 'Punjab',
    country: 'Pakistan',
    tag: 'Teacher',
    notes: 'Islamic History and Seerah teacher.',
    isSyed: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Saad Bin Waqas',
    firstName: 'Saad',
    lastName: 'Waqas',
    gender: 'male',
    dob: '1990-02-22',
    phones: [{ id: 'ph-19', label: 'mobile', number: '+923247890119' }],
    emails: [{ id: 'em-19', label: 'personal', address: 'saad.waqas@example.com' }],
    addresses: [{ id: 'ad-19', label: 'home', line1: 'Housing Colony', city: 'Sheikhupura', state: 'Punjab', country: 'Pakistan' }],
    city: 'Sheikhupura',
    state: 'Punjab',
    country: 'Pakistan',
    tag: 'Parent',
    notes: 'Parent representative in Madrasa Management Committee.',
    isSyed: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Rabia Basri',
    firstName: 'Rabia',
    lastName: 'Basri',
    gender: 'female',
    dob: '1996-10-04',
    phones: [{ id: 'ph-20', label: 'mobile', number: '+923099870120' }],
    emails: [{ id: 'em-20', label: 'personal', address: 'rabia.basri@example.com' }],
    addresses: [{ id: 'ad-20', label: 'home', line1: 'Civil Lines Road', city: 'Jhelum', state: 'Punjab', country: 'Pakistan' }],
    city: 'Jhelum',
    state: 'Punjab',
    country: 'Pakistan',
    tag: 'Student',
    notes: 'Enrolled in Special Hadith Intensive program.',
    isSyed: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

async function main() {
  await initDb();
  const db = getDb();
  
  const argSubdomain = process.argv[2]?.trim().toLowerCase();
  let subdomainsToSeed: string[];

  if (argSubdomain && argSubdomain !== 'all') {
    subdomainsToSeed = [argSubdomain];
  } else {
    // Seed all existing workspaces in the database
    const allWorkspaces = await db.select({ subdomain: workspaces.subdomain }).from(workspaces);
    subdomainsToSeed = Array.from(new Set(['demo', ...allWorkspaces.map((w) => w.subdomain)]));
  }

  for (const subdomain of subdomainsToSeed) {
    console.log(`Seeding 20 complete dummy contacts into local database for tenant subdomain: "${subdomain}"...`);
    const preparedContacts: Contact[] = DUMMY_CONTACTS.map((draft, idx) => ({
      ...draft,
      id: `c-seed-dummy-${idx + 1}`,
    }) as Contact);

    await bulkSaveContacts(subdomain, preparedContacts);
    console.log(`Successfully seeded 20 complete dummy contacts into workspace "${subdomain}"!`);
  }
  
  process.exit(0);
}

main().catch((err) => {
  console.error('Failed to seed contacts:', err);
  process.exit(1);
});
