import React from 'react';
import { useTranslation } from '@/hooks/useTranslation';

export interface SimpleTransactionPostingTableProps {
  debitAccount: string;
  creditAccount: string;
  amountLabel: string;
}

export function SimpleTransactionPostingTable({
  debitAccount,
  creditAccount,
  amountLabel,
}: SimpleTransactionPostingTableProps): React.JSX.Element {
  const { t } = useTranslation();

  return (
    <div className="overflow-x-auto rounded-xl border border-border">
      <table className="min-w-review-panel w-full border-collapse">
        <caption className="sr-only">
          {t('accounting.journal.dashboard.wizard.linesAutoGenerated')}
        </caption>
        <thead>
          <tr className="bg-muted/60 border-b border-border">
            <th scope="col" className="px-3 py-2 font-bold text-muted-foreground uppercase text-start">
              {t('accounting.journal.detail.account')}
            </th>
            <th scope="col" className="px-3 py-2 font-bold text-muted-foreground uppercase text-end">
              {t('accounting.columns.journal.debit')}
            </th>
            <th scope="col" className="px-3 py-2 font-bold text-muted-foreground uppercase text-end">
              {t('accounting.columns.journal.credit')}
            </th>
          </tr>
        </thead>
        <tbody>
          <tr className="bg-info/5 border-b border-border">
            <td className="px-3 py-2 font-semibold text-foreground">{debitAccount}</td>
            <td className="px-3 py-2 text-end font-mono text-info font-bold">{amountLabel}</td>
            <td className="px-3 py-2 text-end text-muted-foreground">—</td>
          </tr>
          <tr className="bg-success/10">
            <td className="px-3 py-2 font-semibold text-foreground">{creditAccount}</td>
            <td className="px-3 py-2 text-end text-muted-foreground">—</td>
            <td className="px-3 py-2 text-end font-mono text-success font-bold">{amountLabel}</td>
          </tr>
        </tbody>
      </table>
    </div>
  );
}
