import React from "react";
import { describe, it, expect, vi } from "vitest";
import { renderToStaticMarkup } from "react-dom/server";
import { SimpleTransactionPostingTable } from "./SimpleTransactionPostingTable";

vi.mock("@/hooks/useTranslation", () => ({
  useTranslation: () => ({
    t: (key: string) => key,
    language: "en",
    dir: "ltr",
  }),
}));

describe("SimpleTransactionPostingTable", () => {
  it("renders debit and credit accounts with formatted amount labels", () => {
    const html = renderToStaticMarkup(
      <SimpleTransactionPostingTable
        debitAccount="1010 - Bank Account"
        creditAccount="4010 - Tuition Revenue"
        amountLabel="$500.00"
      />
    );

    expect(html).toContain("1010 - Bank Account");
    expect(html).toContain("4010 - Tuition Revenue");
    expect(html).toContain("$500.00");
    expect(html).toContain("row-debit");
    expect(html).toContain("row-credit");
    expect(html).toContain("accounting.journal.dashboard.wizard.linesAutoGenerated");
    expect(html).toContain("accounting.columns.journal.debit");
    expect(html).toContain("accounting.columns.journal.credit");
  });
});
