import React from 'react';
import { useTranslation } from '@/hooks/useTranslation';
import {
  Table,
  TableHeader,
  TableBody,
  TableRow,
  TableHead,
  TableCell,
  TableCaption,
} from '@/components/ui/table';

export interface SimpleTransactionPostingTableProps {
  debitAccount: string;
  creditAccount: string;
  amountLabel: string;
}

export function SimpleTransactionPostingTable({
  debitAccount,
  creditAccount,
  amountLabel,
}: SimpleTransactionPostingTableProps): React.JSX.Element {
  const { t } = useTranslation();

  return (
    <div className="overflow-x-auto rounded-xl border border-border">
      <Table className="min-w-review-panel w-full">
        <TableCaption className="sr-only">
          {t('accounting.journal.dashboard.wizard.linesAutoGenerated')}
        </TableCaption>
        <TableHeader>
          <TableRow className="bg-muted/60 border-b border-border hover:bg-muted/60">
            <TableHead className="px-3 py-2 font-bold text-muted-foreground uppercase text-start">
              {t('accounting.journal.detail.account')}
            </TableHead>
            <TableHead className="px-3 py-2 font-bold text-muted-foreground uppercase text-end">
              {t('accounting.columns.journal.debit')}
            </TableHead>
            <TableHead className="px-3 py-2 font-bold text-muted-foreground uppercase text-end">
              {t('accounting.columns.journal.credit')}
            </TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          <TableRow className="bg-info/5 border-b border-border hover:bg-info/5">
            <TableCell className="px-3 py-2 font-semibold text-foreground">{debitAccount}</TableCell>
            <TableCell className="px-3 py-2 text-end font-mono text-info font-bold">{amountLabel}</TableCell>
            <TableCell className="px-3 py-2 text-end text-muted-foreground">—</TableCell>
          </TableRow>
          <TableRow className="bg-success/10 hover:bg-success/10 border-0">
            <TableCell className="px-3 py-2 font-semibold text-foreground">{creditAccount}</TableCell>
            <TableCell className="px-3 py-2 text-end text-muted-foreground">—</TableCell>
            <TableCell className="px-3 py-2 text-end font-mono text-success font-bold">{amountLabel}</TableCell>
          </TableRow>
        </TableBody>
      </Table>
    </div>
  );
}
