import React from 'react';
import { useTranslation } from '@/hooks/useTranslation';
import {
  FinancialLedgerTable,
  type FinancialLedgerTableProps,
} from '@/components/ui/FinancialLedgerTable';

export interface SimpleTransactionPostingTableProps {
  debitAccount: string;
  creditAccount: string;
  amountLabel: string;
}

/**
 * Accounting wizard posting preview — shows a debit row and a credit row.
 * Thin wrapper over {@link FinancialLedgerTable}; styling lives in the primitive.
 */
export function SimpleTransactionPostingTable({
  debitAccount,
  creditAccount,
  amountLabel,
}: SimpleTransactionPostingTableProps): React.JSX.Element {
  const { t } = useTranslation();

  const rows: FinancialLedgerTableProps['rows'] = [
    { account: debitAccount, debit: amountLabel, variant: 'debit' },
    { account: creditAccount, credit: amountLabel, variant: 'credit' },
  ];

  return (
    <FinancialLedgerTable
      caption={t('accounting.journal.dashboard.wizard.linesAutoGenerated')}
      rows={rows}
      columnLabels={{
        account: t('accounting.journal.detail.account'),
        debit: t('accounting.columns.journal.debit'),
        credit: t('accounting.columns.journal.credit'),
      }}
    />
  );
}

