import type { DocumentTemplatePreset } from "@mms/shared";
import type { BrandingInfo } from "@/lib/invoiceTemplateStore";
import type { StudentCardPayload, StudentCardTemplate } from "./studentCardTemplateTypes";
import { getDefaultStudentCardTemplate } from "./studentCardTemplateDefaults";

export interface StudentCardTemplatePreset extends DocumentTemplatePreset<StudentCardPayload> {
  nameKey: string;
}

export function getAvailableStudentCardPresets(
  branding?: BrandingInfo,
): StudentCardTemplatePreset[] {
  const madrasaName = branding?.madrasaName || "Madrasa Management System";
  const standardTemplate = getDefaultStudentCardTemplate(branding);

  const verticalBadgeTemplate: StudentCardTemplate = {
    pageSize: "CR80",
    orientation: "portrait",
    elements: [
      {
        id: "badge_inst",
        type: "field",
        field: "institution_name",
        label: madrasaName,
        x: 12,
        y: 10,
        w: 180,
        h: 16,
        style: { fontSize: 10, fontWeight: "bold", textAlign: "center", color: "#0f172a" },
      },
      {
        id: "badge_title",
        type: "text",
        label: "STUDENT ID",
        x: 12,
        y: 28,
        w: 180,
        h: 12,
        style: { fontSize: 7, fontWeight: "bold", textAlign: "center", color: "#0284c7" },
      },
      {
        id: "badge_div1",
        type: "divider",
        label: "Divider",
        x: 12,
        y: 42,
        w: 180,
        h: 1,
        style: { borderColor: "#cbd5e1", borderWidth: 1 },
      },
      {
        id: "badge_photo",
        type: "logo",
        field: "photo",
        label: "Photo",
        x: 62,
        y: 48,
        w: 80,
        h: 90,
        style: { borderWidth: 1, borderColor: "#cbd5e1", borderRadius: 8, backgroundColor: "#f8fafc" },
      },
      {
        id: "badge_name",
        type: "field",
        field: "student_name",
        label: "Student Name",
        x: 12,
        y: 144,
        w: 180,
        h: 16,
        style: { fontSize: 11, fontWeight: "bold", textAlign: "center", color: "#0f172a" },
      },
      {
        id: "badge_gr",
        type: "field",
        field: "gr_number",
        label: "G.R. Number",
        x: 12,
        y: 162,
        w: 180,
        h: 13,
        style: { fontSize: 8, fontWeight: "bold", textAlign: "center", color: "#0284c7" },
      },
      {
        id: "badge_session",
        type: "field",
        field: "session_name",
        label: "Session",
        x: 12,
        y: 176,
        w: 180,
        h: 13,
        style: { fontSize: 8, textAlign: "center", color: "#475569" },
      },
      {
        id: "badge_qr",
        type: "qrcode",
        label: "QR Code",
        x: 72,
        y: 194,
        w: 60,
        h: 60,
        style: { color: "#0f172a" },
      },
      {
        id: "badge_blood",
        type: "field",
        field: "blood_group",
        label: "Blood Group",
        x: 12,
        y: 260,
        w: 180,
        h: 12,
        style: { fontSize: 7, fontWeight: "bold", textAlign: "center", color: "#dc2626" },
      },
      {
        id: "badge_issue",
        type: "field",
        field: "issue_date",
        label: "Issue Date",
        x: 12,
        y: 280,
        w: 180,
        h: 11,
        style: { fontSize: 6, textAlign: "center", color: "#94a3b8" },
      },
    ],
    backElements: [
      {
        id: "vbadge_back_title",
        type: "text",
        label: "EMERGENCY & INSTRUCTIONS",
        x: 12,
        y: 12,
        w: 180,
        h: 14,
        style: { fontSize: 8, fontWeight: "bold", textAlign: "center", color: "#0284c7" },
      },
      {
        id: "vbadge_back_div1",
        type: "divider",
        label: "Divider",
        x: 12,
        y: 28,
        w: 180,
        h: 1,
        style: { borderColor: "#cbd5e1", borderWidth: 1 },
      },
      {
        id: "vbadge_back_terms",
        type: "field",
        field: "card_terms",
        label: "Terms & Conditions",
        x: 12,
        y: 34,
        w: 180,
        h: 60,
        style: { fontSize: 6.5, textAlign: "center", color: "#475569" },
      },
      {
        id: "vbadge_back_emg",
        type: "field",
        field: "emergency_phone",
        label: "Emergency Phone",
        x: 12,
        y: 102,
        w: 180,
        h: 14,
        style: { fontSize: 7.5, fontWeight: "bold", textAlign: "center", color: "#dc2626" },
      },
      {
        id: "vbadge_back_inst",
        type: "field",
        field: "institution_name",
        label: madrasaName,
        x: 12,
        y: 130,
        w: 180,
        h: 14,
        style: { fontSize: 8, fontWeight: "bold", textAlign: "center", color: "#0f172a" },
      },
      {
        id: "vbadge_back_addr",
        type: "field",
        field: "institution_address",
        label: "Institution Address",
        x: 12,
        y: 148,
        w: 180,
        h: 28,
        style: { fontSize: 6.5, textAlign: "center", color: "#475569" },
      },
      {
        id: "vbadge_back_qr",
        type: "qrcode",
        label: "QR Verification",
        x: 72,
        y: 188,
        w: 60,
        h: 60,
        style: { color: "#0f172a" },
      },
      {
        id: "vbadge_back_sign_line",
        type: "divider",
        label: "Signature Line",
        x: 32,
        y: 275,
        w: 140,
        h: 1,
        style: { borderColor: "#475569", borderWidth: 1 },
      },
      {
        id: "vbadge_back_sign_label",
        type: "text",
        label: "Authorized Signature",
        x: 12,
        y: 280,
        w: 180,
        h: 12,
        style: { fontSize: 6.5, fontWeight: "600", textAlign: "center", color: "#334155" },
      },
    ],
  };

  const minimalTemplate: StudentCardTemplate = {
    pageSize: "CR80",
    orientation: "landscape",
    elements: [
      {
        id: "min_inst",
        type: "field",
        field: "institution_name",
        label: madrasaName,
        x: 16,
        y: 14,
        w: 200,
        h: 16,
        style: { fontSize: 10, fontWeight: "bold", color: "#1e293b" },
      },
      {
        id: "min_name",
        type: "field",
        field: "student_name",
        label: "Student Name",
        x: 16,
        y: 44,
        w: 190,
        h: 18,
        style: { fontSize: 13, fontWeight: "bold", color: "#0f172a" },
      },
      {
        id: "min_session",
        type: "field",
        field: "session_name",
        label: "Session",
        x: 16,
        y: 65,
        w: 190,
        h: 14,
        style: { fontSize: 8, color: "#64748b" },
      },
      {
        id: "min_gr",
        type: "field",
        field: "gr_number",
        label: "G.R. Number",
        x: 16,
        y: 84,
        w: 190,
        h: 14,
        style: { fontSize: 8, fontWeight: "600", color: "#0f172a" },
      },
      {
        id: "min_guardian",
        type: "field",
        field: "guardian_name",
        label: "Guardian",
        x: 16,
        y: 100,
        w: 190,
        h: 14,
        style: { fontSize: 8, color: "#475569" },
      },
      {
        id: "min_qr",
        type: "qrcode",
        label: "QR Code",
        x: 236,
        y: 36,
        w: 72,
        h: 72,
        style: { color: "#0f172a" },
      },
      {
        id: "min_blood",
        type: "field",
        field: "blood_group",
        label: "Blood Group",
        x: 16,
        y: 118,
        w: 80,
        h: 14,
        style: { fontSize: 8, fontWeight: "bold", color: "#dc2626" },
      },
      {
        id: "min_issue",
        type: "field",
        field: "issue_date",
        label: "Issue Date",
        x: 160,
        y: 120,
        w: 148,
        h: 12,
        style: { fontSize: 7, textAlign: "right", color: "#94a3b8" },
      },
    ],
    backElements: [
      {
        id: "min_back_terms",
        type: "field",
        field: "card_terms",
        label: "Card Terms",
        x: 16,
        y: 16,
        w: 290,
        h: 40,
        style: { fontSize: 7, color: "#475569" },
      },
      {
        id: "min_back_emg",
        type: "field",
        field: "emergency_phone",
        label: "Emergency Phone",
        x: 16,
        y: 65,
        w: 200,
        h: 14,
        style: { fontSize: 8, color: "#0f172a", fontWeight: "600" },
      },
      {
        id: "min_back_inst",
        type: "field",
        field: "institution_address",
        label: "Institution Address",
        x: 16,
        y: 84,
        w: 200,
        h: 30,
        style: { fontSize: 6.5, color: "#64748b" },
      },
      {
        id: "min_back_sign",
        type: "text",
        label: "Authorized Signature",
        x: 200,
        y: 120,
        w: 108,
        h: 12,
        style: { fontSize: 6.5, textAlign: "right", color: "#64748b", fontWeight: "600" },
      },
    ],
  };

  return [
    {
      key: "standard",
      label: "Standard Card (Horizontal)",
      nameKey: "students.cardTemplate.presetStandard",
      template: standardTemplate,
    },
    {
      key: "badge",
      label: "Vertical Badge",
      nameKey: "students.cardTemplate.presetBadge",
      template: verticalBadgeTemplate,
    },
    {
      key: "minimal",
      label: "Modern Minimalist",
      nameKey: "students.cardTemplate.presetMinimal",
      template: minimalTemplate,
    },
  ];
}
