import type { BrandingInfo } from "@/lib/invoiceTemplateStore";
import type { StudentCardTemplate } from "./studentCardTemplateTypes";

/**
 * Returns default back-of-card elements (Instructions, Return Address, Terms, Signatures).
 */
export function getDefaultStudentCardBackElements(
  branding?: BrandingInfo,
): StudentCardTemplate["elements"] {
  const madrasaName = branding?.madrasaName || "Madrasa Management System";

  return [
    {
      id: "back_header",
      type: "text",
      label: "TERMS & EMERGENCY INSTRUCTIONS",
      x: 12,
      y: 10,
      w: 300,
      h: 14,
      style: { fontSize: 8, fontWeight: "bold", color: "rgb(2, 132, 199)" },
    },
    {
      id: "back_top_divider",
      type: "divider",
      label: "Divider",
      x: 12,
      y: 24,
      w: 300,
      h: 1,
      style: { borderColor: "rgb(203, 213, 225)", borderWidth: 1 },
    },
    {
      id: "back_terms",
      type: "field",
      field: "card_terms",
      label: "Card Terms",
      x: 12,
      y: 28,
      w: 300,
      h: 36,
      style: { fontSize: 7, color: "rgb(51, 65, 85)" },
    },
    {
      id: "back_return_notice",
      type: "text",
      label: "If found, please return to:",
      x: 12,
      y: 66,
      w: 200,
      h: 11,
      style: { fontSize: 7, fontWeight: "600", color: "rgb(15, 23, 42)" },
    },
    {
      id: "back_inst_name",
      type: "field",
      field: "institution_name",
      label: madrasaName,
      x: 12,
      y: 77,
      w: 200,
      h: 12,
      style: { fontSize: 7, fontWeight: "bold", color: "rgb(15, 23, 42)" },
    },
    {
      id: "back_inst_address",
      type: "field",
      field: "institution_address",
      label: "Institution Address",
      x: 12,
      y: 89,
      w: 200,
      h: 22,
      style: { fontSize: 6.5, color: "rgb(71, 85, 105)" },
    },
    {
      id: "back_inst_phone",
      type: "field",
      field: "institution_phone",
      label: "Helpline Phone",
      x: 12,
      y: 112,
      w: 200,
      h: 12,
      style: { fontSize: 7, color: "rgb(2, 132, 199)", fontWeight: "600" },
    },
    {
      id: "back_qr",
      type: "qrcode",
      label: "Verification QR",
      x: 234,
      y: 66,
      w: 64,
      h: 64,
      style: { color: "rgb(15, 23, 42)" },
    },
    {
      id: "back_bottom_divider",
      type: "divider",
      label: "Divider",
      x: 12,
      y: 132,
      w: 300,
      h: 1,
      style: { borderColor: "rgb(203, 213, 225)", borderWidth: 1 },
    },
    {
      id: "back_auth_line",
      type: "divider",
      label: "Signature Line",
      x: 190,
      y: 168,
      w: 115,
      h: 1,
      style: { borderColor: "rgb(71, 85, 105)", borderWidth: 1 },
    },
    {
      id: "back_signature_title",
      type: "text",
      label: "Principal / Authorized Signature",
      x: 190,
      y: 172,
      w: 115,
      h: 12,
      style: { fontSize: 6.5, fontWeight: "600", textAlign: "center", color: "rgb(51, 65, 85)" },
    },
    {
      id: "back_validity",
      type: "field",
      field: "expiry_date",
      label: "Valid Until",
      x: 12,
      y: 140,
      w: 160,
      h: 12,
      style: { fontSize: 7, color: "rgb(100, 116, 139)" },
    },
  ];
}
