import type { BrandingInfo } from "@/lib/invoiceTemplateStore";
import type { StudentCardTemplate } from "./studentCardTemplateTypes";

/**
 * Returns the default system template for Student ID cards (CR80 landscape).
 */
export function getDefaultStudentCardTemplate(branding?: BrandingInfo): StudentCardTemplate {
  const madrasaName = branding?.madrasaName || "Madrasa Management System";

  return {
    pageSize: "CR80",
    orientation: "landscape",
    elements: [
      {
        id: "inst_header",
        type: "field",
        field: "institution_name",
        label: madrasaName,
        x: 12,
        y: 8,
        w: 220,
        h: 16,
        style: { fontSize: 11, fontWeight: "bold", color: "#0f172a" },
      },
      {
        id: "card_title",
        type: "text",
        label: "STUDENT IDENTITY CARD",
        x: 12,
        y: 25,
        w: 220,
        h: 12,
        style: { fontSize: 7, fontWeight: "bold", color: "#0284c7" },
      },
      {
        id: "top_divider",
        type: "divider",
        label: "Divider",
        x: 12,
        y: 38,
        w: 300,
        h: 1,
        style: { borderColor: "#cbd5e1", borderWidth: 1 },
      },
      {
        id: "student_photo",
        type: "logo",
        field: "photo",
        label: "Photo",
        x: 12,
        y: 44,
        w: 58,
        h: 68,
        style: { borderWidth: 1, borderColor: "#cbd5e1", borderRadius: 6, backgroundColor: "#f8fafc" },
      },
      {
        id: "student_name",
        type: "field",
        field: "student_name",
        label: "Student Name",
        x: 78,
        y: 44,
        w: 160,
        h: 16,
        style: { fontSize: 11, fontWeight: "bold", color: "#0f172a" },
      },
      {
        id: "session_name",
        type: "field",
        field: "session_name",
        label: "Class / Session",
        x: 78,
        y: 62,
        w: 160,
        h: 13,
        style: { fontSize: 8, fontWeight: "600", color: "#0284c7" },
      },
      {
        id: "guardian_name",
        type: "field",
        field: "guardian_name",
        label: "Guardian Name",
        x: 78,
        y: 76,
        w: 160,
        h: 13,
        style: { fontSize: 8, color: "#475569" },
      },
      {
        id: "emergency_phone",
        type: "field",
        field: "emergency_phone",
        label: "Emergency Contact",
        x: 78,
        y: 90,
        w: 160,
        h: 13,
        style: { fontSize: 8, color: "#475569" },
      },
      {
        id: "blood_group",
        type: "field",
        field: "blood_group",
        label: "Blood Group",
        x: 78,
        y: 104,
        w: 50,
        h: 13,
        style: { fontSize: 8, fontWeight: "bold", color: "#dc2626" },
      },
      {
        id: "student_qr",
        type: "qrcode",
        label: "QR Code",
        x: 248,
        y: 44,
        w: 64,
        h: 64,
        style: { color: "#0f172a" },
      },
      {
        id: "gr_number",
        type: "field",
        field: "gr_number",
        label: "G.R. Number",
        x: 244,
        y: 110,
        w: 72,
        h: 12,
        style: { fontSize: 7, fontWeight: "bold", textAlign: "center", color: "#0f172a" },
      },
      {
        id: "bottom_divider",
        type: "divider",
        label: "Divider",
        x: 12,
        y: 126,
        w: 300,
        h: 1,
        style: { borderColor: "#cbd5e1", borderWidth: 1 },
      },
      {
        id: "student_id",
        type: "field",
        field: "student_id",
        label: "Student ID",
        x: 12,
        y: 131,
        w: 140,
        h: 12,
        style: { fontSize: 7, color: "#64748b" },
      },
      {
        id: "issue_date",
        type: "field",
        field: "issue_date",
        label: "Issue Date",
        x: 180,
        y: 131,
        w: 132,
        h: 12,
        style: { fontSize: 7, textAlign: "right", color: "#64748b" },
      },
    ],
    backElements: getDefaultStudentCardBackElements(branding),
  };
}

/**
 * Returns default back-of-card elements (Instructions, Return Address, Terms, Signatures).
 */
export function getDefaultStudentCardBackElements(
  branding?: BrandingInfo,
): StudentCardTemplate["elements"] {
  const madrasaName = branding?.madrasaName || "Madrasa Management System";

  return [
    {
      id: "back_header",
      type: "text",
      label: "TERMS & EMERGENCY INSTRUCTIONS",
      x: 12,
      y: 10,
      w: 300,
      h: 14,
      style: { fontSize: 8, fontWeight: "bold", color: "#0284c7" },
    },
    {
      id: "back_top_divider",
      type: "divider",
      label: "Divider",
      x: 12,
      y: 24,
      w: 300,
      h: 1,
      style: { borderColor: "#cbd5e1", borderWidth: 1 },
    },
    {
      id: "back_terms",
      type: "field",
      field: "card_terms",
      label: "Card Terms",
      x: 12,
      y: 28,
      w: 300,
      h: 36,
      style: { fontSize: 7, color: "#334155" },
    },
    {
      id: "back_return_notice",
      type: "text",
      label: "If found, please return to:",
      x: 12,
      y: 66,
      w: 200,
      h: 11,
      style: { fontSize: 7, fontWeight: "600", color: "#0f172a" },
    },
    {
      id: "back_inst_name",
      type: "field",
      field: "institution_name",
      label: madrasaName,
      x: 12,
      y: 77,
      w: 200,
      h: 12,
      style: { fontSize: 7, fontWeight: "bold", color: "#0f172a" },
    },
    {
      id: "back_inst_address",
      type: "field",
      field: "institution_address",
      label: "Institution Address",
      x: 12,
      y: 89,
      w: 200,
      h: 22,
      style: { fontSize: 6.5, color: "#475569" },
    },
    {
      id: "back_inst_phone",
      type: "field",
      field: "institution_phone",
      label: "Helpline Phone",
      x: 12,
      y: 112,
      w: 200,
      h: 12,
      style: { fontSize: 7, color: "#0284c7", fontWeight: "600" },
    },
    {
      id: "back_qr",
      type: "qrcode",
      label: "Verification QR",
      x: 234,
      y: 66,
      w: 64,
      h: 64,
      style: { color: "#0f172a" },
    },
    {
      id: "back_bottom_divider",
      type: "divider",
      label: "Divider",
      x: 12,
      y: 132,
      w: 300,
      h: 1,
      style: { borderColor: "#cbd5e1", borderWidth: 1 },
    },
    {
      id: "back_auth_line",
      type: "divider",
      label: "Signature Line",
      x: 190,
      y: 168,
      w: 115,
      h: 1,
      style: { borderColor: "#475569", borderWidth: 1 },
    },
    {
      id: "back_signature_title",
      type: "text",
      label: "Principal / Authorized Signature",
      x: 190,
      y: 172,
      w: 115,
      h: 12,
      style: { fontSize: 6.5, fontWeight: "600", textAlign: "center", color: "#334155" },
    },
    {
      id: "back_validity",
      type: "field",
      field: "expiry_date",
      label: "Valid Until",
      x: 12,
      y: 140,
      w: 160,
      h: 12,
      style: { fontSize: 7, color: "#64748b" },
    },
  ];
}

