import type { StudentCardTemplate } from "./studentCardTemplateTypes";

/**
 * Returns back-side elements for the vertical badge ID card preset.
 */
export function getVerticalBadgeBackElements(
  madrasaName = "Madrasa Management System",
): NonNullable<StudentCardTemplate["backElements"]> {
  return [
    {
      id: "vbadge_back_title",
      type: "text",
      label: "EMERGENCY & INSTRUCTIONS",
      x: 12,
      y: 12,
      w: 180,
      h: 14,
      style: { fontSize: 8, fontWeight: "bold", textAlign: "center", color: "rgb(2, 132, 199)" },
    },
    {
      id: "vbadge_back_div1",
      type: "divider",
      label: "Divider",
      x: 12,
      y: 28,
      w: 180,
      h: 1,
      style: { borderColor: "rgb(203, 213, 225)", borderWidth: 1 },
    },
    {
      id: "vbadge_back_terms",
      type: "field",
      field: "card_terms",
      label: "Terms & Conditions",
      x: 12,
      y: 34,
      w: 180,
      h: 60,
      style: { fontSize: 6.5, textAlign: "center", color: "rgb(71, 85, 105)" },
    },
    {
      id: "vbadge_back_emg",
      type: "field",
      field: "emergency_phone",
      label: "Emergency Phone",
      x: 12,
      y: 102,
      w: 180,
      h: 14,
      style: { fontSize: 7.5, fontWeight: "bold", textAlign: "center", color: "rgb(220, 38, 38)" },
    },
    {
      id: "vbadge_back_inst",
      type: "field",
      field: "institution_name",
      label: madrasaName,
      x: 12,
      y: 130,
      w: 180,
      h: 14,
      style: { fontSize: 8, fontWeight: "bold", textAlign: "center", color: "rgb(15, 23, 42)" },
    },
    {
      id: "vbadge_back_addr",
      type: "field",
      field: "institution_address",
      label: "Institution Address",
      x: 12,
      y: 148,
      w: 180,
      h: 28,
      style: { fontSize: 6.5, textAlign: "center", color: "rgb(71, 85, 105)" },
    },
    {
      id: "vbadge_back_qr",
      type: "qrcode",
      label: "QR Verification",
      x: 72,
      y: 188,
      w: 60,
      h: 60,
      style: { color: "rgb(15, 23, 42)" },
    },
    {
      id: "vbadge_back_sign_line",
      type: "divider",
      label: "Signature Line",
      x: 32,
      y: 275,
      w: 140,
      h: 1,
      style: { borderColor: "rgb(71, 85, 105)", borderWidth: 1 },
    },
    {
      id: "vbadge_back_sign_label",
      type: "text",
      label: "Authorized Signature",
      x: 12,
      y: 280,
      w: 180,
      h: 12,
      style: { fontSize: 6.5, fontWeight: "600", textAlign: "center", color: "rgb(51, 65, 85)" },
    },
  ];
}
