import type { BrandingInfo } from "@/lib/invoiceTemplateStore";
import type { StudentCardTemplate } from "./studentCardTemplateTypes";

/**
 * Returns the modern minimalist ID card preset (CR80 landscape format).
 */
export function getMinimalTemplate(
  _branding?: BrandingInfo,
  madrasaName = "Madrasa Management System",
): StudentCardTemplate {
  return {
    pageSize: "CR80",
    orientation: "landscape",
    elements: [
      {
        id: "min_inst",
        type: "field",
        field: "institution_name",
        label: madrasaName,
        x: 16,
        y: 14,
        w: 200,
        h: 16,
        style: { fontSize: 10, fontWeight: "bold", color: "rgb(30, 41, 59)" },
      },
      {
        id: "min_name",
        type: "field",
        field: "student_name",
        label: "Student Name",
        x: 16,
        y: 44,
        w: 190,
        h: 18,
        style: { fontSize: 13, fontWeight: "bold", color: "rgb(15, 23, 42)" },
      },
      {
        id: "min_session",
        type: "field",
        field: "session_name",
        label: "Session",
        x: 16,
        y: 65,
        w: 190,
        h: 14,
        style: { fontSize: 8, color: "rgb(100, 116, 139)" },
      },
      {
        id: "min_gr",
        type: "field",
        field: "gr_number",
        label: "G.R. Number",
        x: 16,
        y: 84,
        w: 190,
        h: 14,
        style: { fontSize: 8, fontWeight: "600", color: "rgb(15, 23, 42)" },
      },
      {
        id: "min_guardian",
        type: "field",
        field: "guardian_name",
        label: "Guardian",
        x: 16,
        y: 100,
        w: 190,
        h: 14,
        style: { fontSize: 8, color: "rgb(71, 85, 105)" },
      },
      {
        id: "min_qr",
        type: "qrcode",
        label: "QR Code",
        x: 236,
        y: 36,
        w: 72,
        h: 72,
        style: { color: "rgb(15, 23, 42)" },
      },
      {
        id: "min_blood",
        type: "field",
        field: "blood_group",
        label: "Blood Group",
        x: 16,
        y: 118,
        w: 80,
        h: 14,
        style: { fontSize: 8, fontWeight: "bold", color: "rgb(220, 38, 38)" },
      },
      {
        id: "min_issue",
        type: "field",
        field: "issue_date",
        label: "Issue Date",
        x: 160,
        y: 120,
        w: 148,
        h: 12,
        style: { fontSize: 7, textAlign: "right", color: "rgb(148, 163, 184)" },
      },
    ],
    backElements: [
      {
        id: "min_back_terms",
        type: "field",
        field: "card_terms",
        label: "Card Terms",
        x: 16,
        y: 16,
        w: 290,
        h: 40,
        style: { fontSize: 7, color: "rgb(71, 85, 105)" },
      },
      {
        id: "min_back_emg",
        type: "field",
        field: "emergency_phone",
        label: "Emergency Phone",
        x: 16,
        y: 65,
        w: 200,
        h: 14,
        style: { fontSize: 8, color: "rgb(15, 23, 42)", fontWeight: "600" },
      },
      {
        id: "min_back_inst",
        type: "field",
        field: "institution_address",
        label: "Institution Address",
        x: 16,
        y: 84,
        w: 200,
        h: 30,
        style: { fontSize: 6.5, color: "rgb(100, 116, 139)" },
      },
      {
        id: "min_back_sign",
        type: "text",
        label: "Authorized Signature",
        x: 200,
        y: 120,
        w: 108,
        h: 12,
        style: { fontSize: 6.5, textAlign: "right", color: "rgb(100, 116, 139)", fontWeight: "600" },
      },
    ],
  };
}
