import type { BrandingInfo } from "@/lib/invoiceTemplateStore";
import type { StudentCardTemplate } from "./studentCardTemplateTypes";
import { getDefaultStudentCardBackElements } from "./studentCardTemplateBackDefaults";

export { getDefaultStudentCardBackElements };

/**
 * Returns the default system template for Student ID cards (CR80 landscape).
 */
export function getDefaultStudentCardTemplate(branding?: BrandingInfo): StudentCardTemplate {
  const madrasaName = branding?.madrasaName || "Madrasa Management System";

  return {
    pageSize: "CR80",
    orientation: "landscape",
    elements: [
      {
        id: "inst_header",
        type: "field",
        field: "institution_name",
        label: madrasaName,
        x: 12,
        y: 8,
        w: 220,
        h: 16,
        style: { fontSize: 11, fontWeight: "bold", color: "rgb(15, 23, 42)" },
      },
      {
        id: "card_title",
        type: "text",
        label: "STUDENT IDENTITY CARD",
        x: 12,
        y: 25,
        w: 220,
        h: 12,
        style: { fontSize: 7, fontWeight: "bold", color: "rgb(2, 132, 199)" },
      },
      {
        id: "top_divider",
        type: "divider",
        label: "Divider",
        x: 12,
        y: 38,
        w: 300,
        h: 1,
        style: { borderColor: "rgb(203, 213, 225)", borderWidth: 1 },
      },
      {
        id: "student_photo",
        type: "logo",
        field: "photo",
        label: "Photo",
        x: 12,
        y: 44,
        w: 58,
        h: 68,
        style: { borderWidth: 1, borderColor: "rgb(203, 213, 225)", borderRadius: 6, backgroundColor: "rgb(248, 250, 252)" },
      },
      {
        id: "student_name",
        type: "field",
        field: "student_name",
        label: "Student Name",
        x: 78,
        y: 44,
        w: 160,
        h: 16,
        style: { fontSize: 11, fontWeight: "bold", color: "rgb(15, 23, 42)" },
      },
      {
        id: "session_name",
        type: "field",
        field: "session_name",
        label: "Class / Session",
        x: 78,
        y: 62,
        w: 160,
        h: 13,
        style: { fontSize: 8, fontWeight: "600", color: "rgb(2, 132, 199)" },
      },
      {
        id: "guardian_name",
        type: "field",
        field: "guardian_name",
        label: "Guardian Name",
        x: 78,
        y: 76,
        w: 160,
        h: 13,
        style: { fontSize: 8, color: "rgb(71, 85, 105)" },
      },
      {
        id: "emergency_phone",
        type: "field",
        field: "emergency_phone",
        label: "Emergency Contact",
        x: 78,
        y: 90,
        w: 160,
        h: 13,
        style: { fontSize: 8, color: "rgb(71, 85, 105)" },
      },
      {
        id: "blood_group",
        type: "field",
        field: "blood_group",
        label: "Blood Group",
        x: 78,
        y: 104,
        w: 50,
        h: 13,
        style: { fontSize: 8, fontWeight: "bold", color: "rgb(220, 38, 38)" },
      },
      {
        id: "student_qr",
        type: "qrcode",
        label: "QR Code",
        x: 248,
        y: 44,
        w: 64,
        h: 64,
        style: { color: "rgb(15, 23, 42)" },
      },
      {
        id: "gr_number",
        type: "field",
        field: "gr_number",
        label: "G.R. Number",
        x: 244,
        y: 110,
        w: 72,
        h: 12,
        style: { fontSize: 7, fontWeight: "bold", textAlign: "center", color: "rgb(15, 23, 42)" },
      },
      {
        id: "bottom_divider",
        type: "divider",
        label: "Divider",
        x: 12,
        y: 126,
        w: 300,
        h: 1,
        style: { borderColor: "rgb(203, 213, 225)", borderWidth: 1 },
      },
      {
        id: "student_id",
        type: "field",
        field: "student_id",
        label: "Student ID",
        x: 12,
        y: 131,
        w: 140,
        h: 12,
        style: { fontSize: 7, color: "rgb(100, 116, 139)" },
      },
      {
        id: "issue_date",
        type: "field",
        field: "issue_date",
        label: "Issue Date",
        x: 180,
        y: 131,
        w: 132,
        h: 12,
        style: { fontSize: 7, textAlign: "right", color: "rgb(100, 116, 139)" },
      },
    ],
    backElements: getDefaultStudentCardBackElements(branding),
  };
}
