import { tenantUsers, contacts, students, sessions } from './schema.js';

export const preparedTenantUserColumns = {
  id: tenantUsers.id,
  workspaceSubdomain: tenantUsers.workspaceSubdomain,
  loginEmail: tenantUsers.loginEmail,
  passwordHash: tenantUsers.passwordHash,
  name: tenantUsers.name,
  role: tenantUsers.role,
  contactId: tenantUsers.contactId,
  emailVerifiedAt: tenantUsers.emailVerifiedAt,
  pendingLoginEmail: tenantUsers.pendingLoginEmail,
  mustChangePassword: tenantUsers.mustChangePassword,
  createdAt: tenantUsers.createdAt,
  updatedAt: tenantUsers.updatedAt,
  deletedAt: tenantUsers.deletedAt,
  deletedBy: tenantUsers.deletedBy,
  deletionReason: tenantUsers.deletionReason,
  restoredAt: tenantUsers.restoredAt,
  restoredBy: tenantUsers.restoredBy,
  deletedWithCascade: tenantUsers.deletedWithCascade,
  profileJson: tenantUsers.profileJson,
};

export const preparedContactColumns = {
  id: contacts.id,
  workspaceSubdomain: contacts.workspaceSubdomain,
  firstName: contacts.firstName,
  lastName: contacts.lastName,
  name: contacts.name,
  gender: contacts.gender,
  dob: contacts.dob,
  cnic: contacts.cnic,
  isSyed: contacts.isSyed,
  avatar: contacts.avatar,
  notes: contacts.notes,
  whatsappStatus: contacts.whatsappStatus,
  lastCheckedAt: contacts.lastCheckedAt,
  aiSummary: contacts.aiSummary,
  deletedAt: contacts.deletedAt,
  deletedBy: contacts.deletedBy,
  deletionReason: contacts.deletionReason,
  restoredAt: contacts.restoredAt,
  restoredBy: contacts.restoredBy,
  deletedWithCascade: contacts.deletedWithCascade,
  createdAt: contacts.createdAt,
  updatedAt: contacts.updatedAt,
  createdBy: contacts.createdBy,
  updatedBy: contacts.updatedBy,
};

export const preparedStudentColumns = {
  id: students.id,
  workspaceSubdomain: students.workspaceSubdomain,
  contactId: students.contactId,
  fatherContactId: students.fatherContactId,
  motherContactId: students.motherContactId,
  guardianContactId: students.guardianContactId,
  fatherName: students.fatherName,
  motherName: students.motherName,
  guardianName: students.guardianName,
  grNumber: students.grNumber,
  studentId: students.studentId,
  status: students.status,
  registeredDate: students.registeredDate,
  enrollmentDate: students.enrollmentDate,
  discountType: students.discountType,
  discountPct: students.discountPct,
  registrationType: students.registrationType,
  notes: students.notes,
  deletedAt: students.deletedAt,
  deletedBy: students.deletedBy,
  deletionReason: students.deletionReason,
  restoredAt: students.restoredAt,
  restoredBy: students.restoredBy,
  deletedWithCascade: students.deletedWithCascade,
  createdAt: students.createdAt,
  updatedAt: students.updatedAt,
  createdBy: students.createdBy,
  updatedBy: students.updatedBy,
};

export const preparedSessionColumns = {
  id: sessions.id,
  workspaceSubdomain: sessions.workspaceSubdomain,
  name: sessions.name,
  type: sessions.type,
  status: sessions.status,
  startDate: sessions.startDate,
  endDate: sessions.endDate,
  baseFee: sessions.baseFee,
  currency: sessions.currency,
  description: sessions.description,
  deletedAt: sessions.deletedAt,
  deletedBy: sessions.deletedBy,
  deletionReason: sessions.deletionReason,
  restoredAt: sessions.restoredAt,
  restoredBy: sessions.restoredBy,
  deletedWithCascade: sessions.deletedWithCascade,
  createdAt: sessions.createdAt,
  updatedAt: sessions.updatedAt,
};
