import type { ObligationsRepository } from './obligationsRepository.js';
import {
  listObligationTypesByWorkspace,
  findObligationTypeById,
  findObligationTypesByIds,
  saveObligationType,
  bulkSaveObligationTypes,
  replaceObligationTypesForWorkspace,
  listMujtahidsByWorkspace,
  findMujtahidById,
  findMujtahidsByIds,
  saveMujtahid,
  bulkSaveMujtahids,
  replaceMujtahidsForWorkspace,
  listMujtahidRepsByWorkspace,
  findMujtahidRepById,
  findMujtahidRepsByIds,
  saveMujtahidRep,
  bulkSaveMujtahidReps,
  replaceMujtahidRepsForWorkspace,
  listWakalaTypesByWorkspace,
  findWakalaTypeById,
  findWakalaTypesByIds,
  saveWakalaType,
  bulkSaveWakalaTypes,
  replaceWakalaTypesForWorkspace,
  listObligationDistributionsByWorkspace,
  findObligationDistributionById,
  findObligationDistributionsByIds,
  saveObligationDistribution,
  bulkSaveObligationDistributions,
  replaceObligationDistributionsForWorkspace,
  listObligationCollectionsByWorkspace,
  findObligationCollectionById,
  findObligationCollectionsByIds,
  saveObligationCollection,
  bulkSaveObligationCollections,
  replaceObligationCollectionsForWorkspace,
  bulkSoftDeleteObligationCollections,
  bulkRestoreObligationCollections,
} from '../../db/repositories/obligationRepository.js';
import { aggregateObligationsCommandMetrics } from '../../db/repositories/obligationRepositoryMetrics.js';
import { aggregateObligationsReport } from '../../db/repositories/obligationRepositoryReport.js';

/**
 * Drizzle-backed adapter for {@link ObligationsRepository}. Delegates to the
 * existing concrete repository functions (no SQL rewrite in this pass).
 */
export const obligationsRepository: ObligationsRepository = {
  listObligationTypesByWorkspace,
  findObligationTypeById,
  findObligationTypesByIds,
  saveObligationType,
  bulkSaveObligationTypes,
  replaceObligationTypesForWorkspace,
  listMujtahidsByWorkspace,
  findMujtahidById,
  findMujtahidsByIds,
  saveMujtahid,
  bulkSaveMujtahids,
  replaceMujtahidsForWorkspace,
  listMujtahidRepsByWorkspace,
  findMujtahidRepById,
  findMujtahidRepsByIds,
  saveMujtahidRep,
  bulkSaveMujtahidReps,
  replaceMujtahidRepsForWorkspace,
  listWakalaTypesByWorkspace,
  findWakalaTypeById,
  findWakalaTypesByIds,
  saveWakalaType,
  bulkSaveWakalaTypes,
  replaceWakalaTypesForWorkspace,
  listObligationDistributionsByWorkspace,
  findObligationDistributionById,
  findObligationDistributionsByIds,
  saveObligationDistribution,
  bulkSaveObligationDistributions,
  replaceObligationDistributionsForWorkspace,
  listObligationCollectionsByWorkspace,
  findObligationCollectionById,
  findObligationCollectionsByIds,
  saveObligationCollection,
  bulkSaveObligationCollections,
  replaceObligationCollectionsForWorkspace,
  bulkSoftDeleteObligationCollections,
  bulkRestoreObligationCollections,
  aggregateObligationsCommandMetrics,
  aggregateObligationsReport,
};
