import { contacts } from '../schema.js';

export const contactSelectColumns = {
  id: contacts.id,
  workspaceSubdomain: contacts.workspaceSubdomain,
  firstName: contacts.firstName,
  lastName: contacts.lastName,
  name: contacts.name,
  gender: contacts.gender,
  dob: contacts.dob,
  cnic: contacts.cnic,
  isSyed: contacts.isSyed,
  avatar: contacts.avatar,
  notes: contacts.notes,
  whatsappStatus: contacts.whatsappStatus,
  lastCheckedAt: contacts.lastCheckedAt,
  aiSummary: contacts.aiSummary,
  deletedAt: contacts.deletedAt,
  deletedBy: contacts.deletedBy,
  deletionReason: contacts.deletionReason,
  restoredAt: contacts.restoredAt,
  restoredBy: contacts.restoredBy,
  deletedWithCascade: contacts.deletedWithCascade,
  createdAt: contacts.createdAt,
  updatedAt: contacts.updatedAt,
  createdBy: contacts.createdBy,
  updatedBy: contacts.updatedBy,
};
