export {
  contactRecordSchema,
  contactsListQuerySchema,
  contactFieldUsageParamsSchema,
  contactFieldUsageBatchBodySchema,
  buildContactMergeBodySchema,
  contactsWorkDrillDownSchema,
  contactsSavedReportCreateSchema,
  contactGoogleSyncConfigSchema,
  contactGoogleSyncAuditSchema,
  contactGoogleSyncExchangeSchema,
  contactsVcfExportBodySchema,
  contactsDuplicateScanBodySchema,
  buildContactDuplicateCheckBodySchema,
  contactsDuplicatesQuerySchema,
  contactsCsvExportBodySchema,
  moduleSetupAuditBodySchema as contactSetupAuditSchema,
} from '@mms/shared';
