export {
  platformSetupRegisterBodySchema,
  platformPasswordForgotBodySchema,
  platformPasswordResetBodySchema,
  platformPasswordResendBodySchema,
  platformProfilePatchBodySchema,
  platformChangePasswordBodySchema,
  workspaceEnabledPatchBodySchema,
  platformWorkspaceModulesPatchBodySchema,
  workspaceDeleteBodySchema,
  platformCreateAdminBodySchema,
  platformUpdateAdminPermissionsBodySchema,
  platformAdminDisabledBodySchema,
  platformDeleteAdminBodySchema,
} from '@mms/shared';
