import type { AttendanceRecord, Enrollment, Session } from "@mms/shared";
import { SEMANTIC_BADGE } from "@/lib/semanticTone";
import type { EntityDescriptor } from "@/types/entityRegistry";
import { createEntityDescriptor } from "../entityDescriptorFactory";

export const attendanceEntityDescriptor: EntityDescriptor<AttendanceRecord> =
  createEntityDescriptor<AttendanceRecord>({
    entityType: "attendance",
    singularLabel: "Attendance Record",
    pluralLabel: "Attendance",
    idField: "id",
    titleField: "studentName",
    fields: [
      {
        key: "studentName",
        label: "Student",
        labelKey: "attendance.columns.student",
        type: "text",
        sortable: true,
        defaultVisibleInTable: true,
        tableOrder: 10,
        fixed: true,
        cardSlot: "primary",
        drawerSection: "student",
        drawerOrder: 10,
      },
      {
        key: "rollNo",
        label: "Roll Number",
        labelKey: "attendance.columns.rollNo",
        type: "text",
        sortable: true,
        defaultVisibleInTable: true,
        tableOrder: 20,
        cardSlot: "secondary",
        drawerSection: "student",
        drawerOrder: 20,
      },
      {
        key: "status",
        label: "Status",
        labelKey: "attendance.columns.status",
        type: "status",
        sortable: true,
        defaultVisibleInTable: true,
        tableOrder: 30,
        cardSlot: "badge",
        drawerSection: "attendance",
        drawerOrder: 30,
        badgeVariantMap: {
          present: { label: "Present", tone: "success", className: SEMANTIC_BADGE.success },
          absent: { label: "Absent", tone: "destructive", className: SEMANTIC_BADGE.destructive },
          late: { label: "Late", tone: "warning", className: SEMANTIC_BADGE.warning },
          excused: { label: "Excused", tone: "info", className: SEMANTIC_BADGE.info },
        },
      },
      {
        key: "date",
        label: "Date",
        labelKey: "attendance.columns.date",
        type: "date",
        sortable: true,
        defaultVisibleInTable: true,
        tableOrder: 40,
        cardSlot: "meta",
        drawerSection: "attendance",
        drawerOrder: 40,
      },
      {
        key: "timeIn",
        label: "Time In",
        labelKey: "attendance.columns.timeIn",
        type: "text",
        sortable: false,
        defaultVisibleInTable: true,
        tableOrder: 50,
        cardSlot: "meta",
        drawerSection: "timing",
        drawerOrder: 50,
      },
      {
        key: "timeOut",
        label: "Time Out",
        labelKey: "attendance.columns.timeOut",
        type: "text",
        sortable: false,
        defaultVisibleInTable: false,
        tableOrder: 60,
        cardSlot: "meta",
        drawerSection: "timing",
        drawerOrder: 60,
      },
      {
        key: "notes",
        label: "Notes",
        labelKey: "attendance.columns.notes",
        type: "text",
        sortable: false,
        defaultVisibleInTable: false,
        tableOrder: 70,
        cardSlot: "hidden",
        drawerSection: "details",
        drawerOrder: 70,
      },
    ],
  });

export const enrollmentsEntityDescriptor: EntityDescriptor<Enrollment> =
  createEntityDescriptor<Enrollment>({
    entityType: "enrollments",
    singularLabel: "Enrollment",
    pluralLabel: "Enrollments",
    idField: "id",
    titleField: "studentName",
    fields: [
      {
        key: "studentName",
        label: "Student Name",
        labelKey: "enrollments.columns.student",
        type: "text",
        sortable: true,
        defaultVisibleInTable: true,
        tableOrder: 10,
        fixed: true,
        cardSlot: "primary",
        drawerSection: "student",
        drawerOrder: 10,
      },
      {
        key: "className",
        label: "Class",
        labelKey: "enrollments.columns.class",
        type: "text",
        sortable: true,
        defaultVisibleInTable: true,
        tableOrder: 20,
        cardSlot: "secondary",
        drawerSection: "academic",
        drawerOrder: 20,
      },
      {
        key: "sessionName",
        label: "Session",
        labelKey: "enrollments.columns.session",
        type: "text",
        sortable: true,
        defaultVisibleInTable: true,
        tableOrder: 30,
        cardSlot: "meta",
        drawerSection: "academic",
        drawerOrder: 30,
      },
      {
        key: "status",
        label: "Status",
        labelKey: "enrollments.columns.status",
        type: "status",
        sortable: true,
        defaultVisibleInTable: true,
        tableOrder: 40,
        cardSlot: "badge",
        drawerSection: "academic",
        drawerOrder: 40,
        badgeVariantMap: {
          pending: { label: "Pending", tone: "warning", className: SEMANTIC_BADGE.warning },
          enrolled: { label: "Enrolled", tone: "success", className: SEMANTIC_BADGE.success },
          completed: { label: "Completed", tone: "info", className: SEMANTIC_BADGE.info },
          withdrawn: { label: "Withdrawn", tone: "destructive", className: SEMANTIC_BADGE.destructive },
          cancelled: { label: "Cancelled", tone: "muted", className: SEMANTIC_BADGE.muted },
        },
      },
      {
        key: "paymentStatus",
        label: "Payment Status",
        labelKey: "enrollments.columns.payment",
        type: "badge",
        sortable: true,
        defaultVisibleInTable: true,
        tableOrder: 50,
        cardSlot: "badge",
        drawerSection: "finance",
        drawerOrder: 50,
        badgeVariantMap: {
          none: { label: "Unpaid", tone: "destructive", className: SEMANTIC_BADGE.destructive },
          partial: { label: "Partial", tone: "warning", className: SEMANTIC_BADGE.warning },
          paid: { label: "Paid", tone: "success", className: SEMANTIC_BADGE.success },
        },
      },
      {
        key: "finalFee",
        label: "Fee",
        labelKey: "enrollments.columns.finalFee",
        type: "currency",
        sortable: true,
        defaultVisibleInTable: true,
        tableOrder: 60,
        cardSlot: "meta",
        drawerSection: "finance",
        drawerOrder: 60,
      },
      {
        key: "enrolledDate",
        label: "Enrolled Date",
        labelKey: "enrollments.columns.enrolledDate",
        type: "date",
        sortable: true,
        defaultVisibleInTable: false,
        tableOrder: 70,
        cardSlot: "hidden",
        drawerSection: "academic",
        drawerOrder: 70,
      },
    ],
  });

export const sessionsEntityDescriptor: EntityDescriptor<Session> = createEntityDescriptor<Session>({
  entityType: "sessions",
  singularLabel: "Academic Session",
  pluralLabel: "Academic Sessions",
  idField: "id",
  titleField: "name",
  fields: [
    {
      key: "name",
      label: "Session Name",
      labelKey: "sessions.columns.name",
      type: "text",
      sortable: true,
      defaultVisibleInTable: true,
      tableOrder: 10,
      fixed: true,
      cardSlot: "primary",
      drawerSection: "details",
      drawerOrder: 10,
    },
    {
      key: "code",
      label: "Session Code",
      labelKey: "sessions.columns.code",
      type: "text",
      sortable: true,
      defaultVisibleInTable: true,
      tableOrder: 20,
      cardSlot: "secondary",
      drawerSection: "details",
      drawerOrder: 20,
    },
    {
      key: "status",
      label: "Status",
      labelKey: "sessions.columns.status",
      type: "status",
      sortable: true,
      defaultVisibleInTable: true,
      tableOrder: 30,
      cardSlot: "badge",
      drawerSection: "details",
      drawerOrder: 30,
    },
    {
      key: "startDate",
      label: "Start Date",
      labelKey: "sessions.columns.startDate",
      type: "date",
      sortable: true,
      defaultVisibleInTable: true,
      tableOrder: 40,
      cardSlot: "meta",
      drawerSection: "timeline",
      drawerOrder: 40,
    },
    {
      key: "endDate",
      label: "End Date",
      labelKey: "sessions.columns.endDate",
      type: "date",
      sortable: true,
      defaultVisibleInTable: true,
      tableOrder: 50,
      cardSlot: "meta",
      drawerSection: "timeline",
      drawerOrder: 50,
    },
  ],
});
