import type { AttendanceRecord } from "@mms/shared";
import { SEMANTIC_BADGE } from "@/lib/semanticTone";
import type { EntityDescriptor } from "@/types/entityRegistry";
import { createEntityDescriptor } from "../entityDescriptorFactory";

export const attendanceEntityDescriptor: EntityDescriptor<AttendanceRecord> =
  createEntityDescriptor<AttendanceRecord>({
    entityType: "attendance",
    singularLabel: "Attendance Record",
    pluralLabel: "Attendance",
    idField: "id",
    titleField: "studentName",
    fields: [
      {
        key: "studentName",
        label: "Student",
        labelKey: "attendance.columns.student",
        type: "text",
        sortable: true,
        defaultVisibleInTable: true,
        tableOrder: 10,
        fixed: true,
        cardSlot: "primary",
        drawerSection: "student",
        drawerOrder: 10,
      },
      {
        key: "rollNo",
        label: "Roll Number",
        labelKey: "attendance.columns.rollNo",
        type: "text",
        sortable: true,
        defaultVisibleInTable: true,
        tableOrder: 20,
        cardSlot: "secondary",
        drawerSection: "student",
        drawerOrder: 20,
      },
      {
        key: "status",
        label: "Status",
        labelKey: "attendance.columns.status",
        type: "status",
        sortable: true,
        defaultVisibleInTable: true,
        tableOrder: 30,
        cardSlot: "badge",
        drawerSection: "attendance",
        drawerOrder: 30,
        badgeVariantMap: {
          present: { label: "Present", tone: "success", className: SEMANTIC_BADGE.success },
          absent: { label: "Absent", tone: "destructive", className: SEMANTIC_BADGE.destructive },
          late: { label: "Late", tone: "warning", className: SEMANTIC_BADGE.warning },
          excused: { label: "Excused", tone: "info", className: SEMANTIC_BADGE.info },
        },
      },
      {
        key: "date",
        label: "Date",
        labelKey: "attendance.columns.date",
        type: "date",
        sortable: true,
        defaultVisibleInTable: true,
        tableOrder: 40,
        cardSlot: "meta",
        drawerSection: "attendance",
        drawerOrder: 40,
      },
      {
        key: "timeIn",
        label: "Time In",
        labelKey: "attendance.columns.timeIn",
        type: "text",
        sortable: false,
        defaultVisibleInTable: true,
        tableOrder: 50,
        cardSlot: "meta",
        drawerSection: "timing",
        drawerOrder: 50,
      },
      {
        key: "timeOut",
        label: "Time Out",
        labelKey: "attendance.columns.timeOut",
        type: "text",
        sortable: false,
        defaultVisibleInTable: false,
        tableOrder: 60,
        cardSlot: "meta",
        drawerSection: "timing",
        drawerOrder: 60,
      },
      {
        key: "notes",
        label: "Notes",
        labelKey: "attendance.columns.notes",
        type: "text",
        sortable: false,
        defaultVisibleInTable: false,
        tableOrder: 70,
        cardSlot: "hidden",
        drawerSection: "details",
        drawerOrder: 70,
      },
    ],
  });
