import type { Distribution, ObligationCollection } from "@mms/shared";
import { SEMANTIC_BADGE } from "@/lib/semanticTone";
import type { EntityDescriptor } from "@/types/entityRegistry";
import { createEntityDescriptor } from "../entityDescriptorFactory";

export const hasanatEntityDescriptor: EntityDescriptor<Distribution> =
  createEntityDescriptor<Distribution>({
    entityType: "hasanat",
    singularLabel: "Distribution",
    pluralLabel: "Distributions",
    idField: "id",
    titleField: "recipientName",
    fields: [
      {
        key: "recipientName",
        label: "Recipient",
        type: "text",
        sortable: true,
        defaultVisibleInTable: true,
        tableOrder: 10,
        fixed: true,
        cardSlot: "primary",
        drawerSection: "recipient",
        drawerOrder: 10,
      },
      {
        key: "denominationName",
        label: "Denomination",
        type: "text",
        sortable: true,
        defaultVisibleInTable: true,
        tableOrder: 20,
        cardSlot: "secondary",
        drawerSection: "points",
        drawerOrder: 20,
      },
      {
        key: "quantity",
        label: "Quantity",
        type: "number",
        sortable: true,
        defaultVisibleInTable: true,
        tableOrder: 30,
        cardSlot: "meta",
        drawerSection: "points",
        drawerOrder: 30,
      },
      {
        key: "status",
        label: "Status",
        type: "status",
        sortable: true,
        defaultVisibleInTable: true,
        tableOrder: 40,
        cardSlot: "badge",
        drawerSection: "distribution",
        drawerOrder: 40,
        badgeVariantMap: {
          active: { label: "Active", tone: "success", className: SEMANTIC_BADGE.success },
          redeemed: { label: "Redeemed", tone: "info", className: SEMANTIC_BADGE.info },
          returned: { label: "Returned", tone: "muted", className: SEMANTIC_BADGE.muted },
        },
      },
      {
        key: "issuedDate",
        label: "Issued Date",
        type: "date",
        sortable: true,
        defaultVisibleInTable: true,
        tableOrder: 50,
        cardSlot: "meta",
        drawerSection: "distribution",
        drawerOrder: 50,
      },
      {
        key: "recipientType",
        label: "Recipient Type",
        type: "badge",
        sortable: false,
        defaultVisibleInTable: false,
        tableOrder: 60,
        cardSlot: "hidden",
        drawerSection: "recipient",
        drawerOrder: 60,
        badgeVariantMap: {
          student: { label: "Student", tone: "info", className: SEMANTIC_BADGE.info },
          faculty: { label: "Faculty", tone: "primary", className: SEMANTIC_BADGE.primary },
        },
      },
    ],
  });

export const obligationsEntityDescriptor: EntityDescriptor<ObligationCollection> =
  createEntityDescriptor<ObligationCollection>({
    entityType: "obligations",
    singularLabel: "Obligation Collection",
    pluralLabel: "Obligation Collections",
    idField: "id",
    titleField: "receipt_no",
    fields: [
      {
        key: "receipt_no",
        label: "Receipt #",
        type: "text",
        sortable: true,
        defaultVisibleInTable: true,
        tableOrder: 10,
        fixed: true,
        cardSlot: "primary",
        drawerSection: "collection",
        drawerOrder: 10,
      },
      {
        key: "amount",
        label: "Amount",
        type: "currency",
        sortable: true,
        defaultVisibleInTable: true,
        tableOrder: 20,
        cardSlot: "secondary",
        drawerSection: "amounts",
        drawerOrder: 20,
      },
      {
        key: "payment_mode",
        label: "Payment Mode",
        type: "badge",
        sortable: true,
        defaultVisibleInTable: true,
        tableOrder: 30,
        cardSlot: "badge",
        drawerSection: "collection",
        drawerOrder: 30,
        badgeVariantMap: {
          Cash: { label: "Cash", tone: "info", className: SEMANTIC_BADGE.info },
          Online: { label: "Online", tone: "success", className: SEMANTIC_BADGE.success },
        },
      },
      {
        key: "received_date",
        label: "Received Date",
        type: "date",
        sortable: true,
        defaultVisibleInTable: true,
        tableOrder: 40,
        cardSlot: "meta",
        drawerSection: "dates",
        drawerOrder: 40,
      },
      {
        key: "received_by",
        label: "Received By",
        type: "text",
        sortable: false,
        defaultVisibleInTable: true,
        tableOrder: 50,
        cardSlot: "meta",
        drawerSection: "collection",
        drawerOrder: 50,
      },
    ],
  });
