import type { Enrollment } from "@mms/shared";
import { SEMANTIC_BADGE } from "@/lib/semanticTone";
import type { EntityDescriptor } from "@/types/entityRegistry";
import { createEntityDescriptor } from "../entityDescriptorFactory";

export const enrollmentsEntityDescriptor: EntityDescriptor<Enrollment> =
  createEntityDescriptor<Enrollment>({
    entityType: "enrollments",
    singularLabel: "Enrollment",
    pluralLabel: "Enrollments",
    idField: "id",
    titleField: "studentName",
    fields: [
      {
        key: "studentName",
        label: "Student Name",
        labelKey: "enrollments.columns.student",
        type: "text",
        sortable: true,
        defaultVisibleInTable: true,
        tableOrder: 10,
        fixed: true,
        cardSlot: "primary",
        drawerSection: "student",
        drawerOrder: 10,
      },
      {
        key: "className",
        label: "Class",
        labelKey: "enrollments.columns.class",
        type: "text",
        sortable: true,
        defaultVisibleInTable: true,
        tableOrder: 20,
        cardSlot: "secondary",
        drawerSection: "academic",
        drawerOrder: 20,
      },
      {
        key: "sessionName",
        label: "Session",
        labelKey: "enrollments.columns.session",
        type: "text",
        sortable: true,
        defaultVisibleInTable: true,
        tableOrder: 30,
        cardSlot: "meta",
        drawerSection: "academic",
        drawerOrder: 30,
      },
      {
        key: "status",
        label: "Status",
        labelKey: "enrollments.columns.status",
        type: "status",
        sortable: true,
        defaultVisibleInTable: true,
        tableOrder: 40,
        cardSlot: "badge",
        drawerSection: "academic",
        drawerOrder: 40,
        badgeVariantMap: {
          pending: { label: "Pending", tone: "warning", className: SEMANTIC_BADGE.warning },
          enrolled: { label: "Enrolled", tone: "success", className: SEMANTIC_BADGE.success },
          completed: { label: "Completed", tone: "info", className: SEMANTIC_BADGE.info },
          withdrawn: { label: "Withdrawn", tone: "destructive", className: SEMANTIC_BADGE.destructive },
          cancelled: { label: "Cancelled", tone: "muted", className: SEMANTIC_BADGE.muted },
        },
      },
      {
        key: "paymentStatus",
        label: "Payment Status",
        labelKey: "enrollments.columns.payment",
        type: "badge",
        sortable: true,
        defaultVisibleInTable: true,
        tableOrder: 50,
        cardSlot: "badge",
        drawerSection: "finance",
        drawerOrder: 50,
        badgeVariantMap: {
          none: { label: "Unpaid", tone: "destructive", className: SEMANTIC_BADGE.destructive },
          partial: { label: "Partial", tone: "warning", className: SEMANTIC_BADGE.warning },
          paid: { label: "Paid", tone: "success", className: SEMANTIC_BADGE.success },
        },
      },
      {
        key: "finalFee",
        label: "Fee",
        labelKey: "enrollments.columns.finalFee",
        type: "currency",
        sortable: true,
        defaultVisibleInTable: true,
        tableOrder: 60,
        cardSlot: "meta",
        drawerSection: "finance",
        drawerOrder: 60,
      },
      {
        key: "enrolledDate",
        label: "Enrolled Date",
        labelKey: "enrollments.columns.enrolledDate",
        type: "date",
        sortable: true,
        defaultVisibleInTable: false,
        tableOrder: 70,
        cardSlot: "hidden",
        drawerSection: "academic",
        drawerOrder: 70,
      },
    ],
  });
