import type { Exam } from "@mms/shared";
import { SEMANTIC_BADGE } from "@/lib/semanticTone";
import type { EntityDescriptor } from "@/types/entityRegistry";
import { createEntityDescriptor } from "../entityDescriptorFactory";

export const examinationsEntityDescriptor: EntityDescriptor<Exam> = createEntityDescriptor<Exam>({
  entityType: "examinations",
  singularLabel: "Examination",
  pluralLabel: "Examinations",
  idField: "id",
  titleField: "name",
  fields: [
    {
      key: "name",
      label: "Exam Name",
      labelKey: "examinations.columns.name",
      type: "text",
      sortable: true,
      defaultVisibleInTable: true,
      tableOrder: 10,
      fixed: true,
      cardSlot: "primary",
      drawerSection: "general",
      drawerOrder: 10,
    },
    {
      key: "subject",
      label: "Subject",
      labelKey: "examinations.columns.subject",
      type: "text",
      sortable: true,
      defaultVisibleInTable: true,
      tableOrder: 20,
      cardSlot: "secondary",
      drawerSection: "general",
      drawerOrder: 20,
    },
    {
      key: "status",
      label: "Status",
      labelKey: "examinations.columns.status",
      type: "status",
      sortable: true,
      defaultVisibleInTable: true,
      tableOrder: 30,
      cardSlot: "badge",
      drawerSection: "status",
      drawerOrder: 30,
      badgeVariantMap: {
        upcoming: { label: "Upcoming", tone: "info", className: SEMANTIC_BADGE.info },
        scheduled: { label: "Scheduled", tone: "warning", className: SEMANTIC_BADGE.warning },
        ongoing: { label: "Ongoing", tone: "primary", className: SEMANTIC_BADGE.primary },
        completed: { label: "Completed", tone: "success", className: SEMANTIC_BADGE.success },
        cancelled: { label: "Cancelled", tone: "destructive", className: SEMANTIC_BADGE.destructive },
      },
    },
    {
      key: "date",
      label: "Exam Date",
      labelKey: "examinations.columns.date",
      type: "date",
      sortable: true,
      defaultVisibleInTable: true,
      tableOrder: 40,
      cardSlot: "meta",
      drawerSection: "schedule",
      drawerOrder: 40,
    },
    {
      key: "totalMarks",
      label: "Total Marks",
      labelKey: "examinations.columns.totalMarks",
      type: "number",
      sortable: true,
      defaultVisibleInTable: true,
      tableOrder: 50,
      cardSlot: "meta",
      drawerSection: "scoring",
      drawerOrder: 50,
    },
    {
      key: "passingMarks",
      label: "Passing Marks",
      labelKey: "examinations.columns.passingMarks",
      type: "number",
      sortable: true,
      defaultVisibleInTable: true,
      tableOrder: 60,
      cardSlot: "meta",
      drawerSection: "scoring",
      drawerOrder: 60,
    },
    {
      key: "duration",
      label: "Duration (min)",
      labelKey: "examinations.columns.duration",
      type: "number",
      sortable: false,
      defaultVisibleInTable: false,
      tableOrder: 70,
      cardSlot: "hidden",
      drawerSection: "schedule",
      drawerOrder: 70,
    },
    {
      key: "description",
      label: "Description",
      labelKey: "examinations.columns.description",
      type: "text",
      sortable: false,
      defaultVisibleInTable: false,
      tableOrder: 80,
      cardSlot: "hidden",
      drawerSection: "general",
      drawerOrder: 80,
    },
  ],
});
