import type { Faculty } from "@mms/shared";
import type { EntityDescriptor } from "@/types/entityRegistry";
import { createEntityDescriptor } from "../entityDescriptorFactory";

export const facultyEntityDescriptor: EntityDescriptor<Faculty> = createEntityDescriptor<Faculty>({
  entityType: "faculty",
  singularLabel: "Faculty Member",
  pluralLabel: "Faculty",
  idField: "id",
  titleField: "name",
  fields: [
    {
      key: "name",
      label: "Name",
      labelKey: "faculty.field.name",
      type: "text",
      sortable: true,
      defaultVisibleInTable: true,
      tableOrder: 10,
      fixed: true,
      cardSlot: "primary",
      drawerSection: "identity",
      drawerOrder: 10,
    },
    {
      key: "employeeId",
      label: "Employee ID",
      labelKey: "faculty.field.employeeId",
      type: "text",
      sortable: true,
      defaultVisibleInTable: true,
      tableOrder: 20,
      cardSlot: "secondary",
      drawerSection: "employment",
      drawerOrder: 20,
    },
    {
      key: "designation",
      label: "Designation",
      labelKey: "faculty.field.designation",
      type: "text",
      sortable: true,
      defaultVisibleInTable: true,
      tableOrder: 30,
      cardSlot: "meta",
      drawerSection: "employment",
      drawerOrder: 30,
    },
    {
      key: "department",
      label: "Department",
      labelKey: "faculty.field.department",
      type: "text",
      sortable: true,
      defaultVisibleInTable: true,
      tableOrder: 40,
      cardSlot: "meta",
      drawerSection: "employment",
      drawerOrder: 40,
    },
    {
      key: "reportingFacultyName",
      label: "Supervisor",
      labelKey: "faculty.columns.supervisor",
      type: "text",
      sortable: false,
      defaultVisibleInTable: true,
      tableOrder: 45,
      cardSlot: "meta",
      drawerSection: "employment",
      drawerOrder: 45,
    },
    {
      key: "subordinateCount",
      label: "Subordinates",
      labelKey: "faculty.columns.subordinates",
      type: "number",
      sortable: false,
      defaultVisibleInTable: true,
      tableOrder: 48,
      cardSlot: "meta",
      drawerSection: "employment",
      drawerOrder: 48,
    },
    {
      key: "status",
      label: "Status",
      labelKey: "faculty.field.status",
      type: "status",
      sortable: true,
      defaultVisibleInTable: true,
      tableOrder: 50,
      cardSlot: "badge",
      drawerSection: "employment",
      drawerOrder: 50,
    },
    {
      key: "phone",
      label: "Phone",
      labelKey: "faculty.field.phone",
      type: "phone",
      sortable: false,
      defaultVisibleInTable: true,
      tableOrder: 60,
      cardSlot: "meta",
      drawerSection: "contact",
      drawerOrder: 60,
    },
  ],
});
