import type { Invoice } from "@mms/shared";
import type { EntityDescriptor } from "@/types/entityRegistry";
import { createEntityDescriptor } from "../entityDescriptorFactory";

export const financeEntityDescriptor: EntityDescriptor<Invoice> = createEntityDescriptor<Invoice>({
  entityType: "finance",
  singularLabel: "Invoice",
  pluralLabel: "Invoices",
  idField: "id",
  titleField: "invoiceNumber",
  fields: [
    {
      key: "invoiceNumber",
      label: "Invoice #",
      labelKey: "finance.columns.invoice",
      type: "text",
      sortable: true,
      defaultVisibleInTable: true,
      tableOrder: 10,
      fixed: true,
      cardSlot: "primary",
      drawerSection: "invoice",
      drawerOrder: 10,
    },
    {
      key: "totalAmount",
      label: "Total Amount",
      labelKey: "finance.columns.amount",
      type: "currency",
      sortable: true,
      defaultVisibleInTable: true,
      tableOrder: 20,
      cardSlot: "secondary",
      drawerSection: "amounts",
      drawerOrder: 20,
    },
    {
      key: "status",
      label: "Payment Status",
      labelKey: "finance.columns.status",
      type: "status",
      sortable: true,
      defaultVisibleInTable: true,
      tableOrder: 30,
      cardSlot: "badge",
      drawerSection: "status",
      drawerOrder: 30,
    },
    {
      key: "issueDate",
      label: "Issue Date",
      labelKey: "finance.columns.paymentDate",
      type: "date",
      sortable: true,
      defaultVisibleInTable: true,
      tableOrder: 40,
      cardSlot: "meta",
      drawerSection: "dates",
      drawerOrder: 40,
    },
    {
      key: "dueDate",
      label: "Due Date",
      labelKey: "finance.columns.dueDate",
      type: "date",
      sortable: true,
      defaultVisibleInTable: true,
      tableOrder: 50,
      cardSlot: "meta",
      drawerSection: "dates",
      drawerOrder: 50,
    },
  ],
});
