import type { MessageRecordDto } from "@mms/shared";
import { SEMANTIC_BADGE } from "@/lib/semanticTone";
import type { EntityDescriptor } from "@/types/entityRegistry";
import { createEntityDescriptor } from "../entityDescriptorFactory";

export const messagingEntityDescriptor: EntityDescriptor<MessageRecordDto> =
  createEntityDescriptor<MessageRecordDto>({
    entityType: "messaging",
    singularLabel: "Message",
    pluralLabel: "Messages",
    idField: "id",
    titleField: "body",
    fields: [
      {
        key: "body",
        label: "Message Content",
        labelKey: "messaging.columns.body",
        type: "text",
        sortable: false,
        defaultVisibleInTable: true,
        tableOrder: 10,
        fixed: true,
        cardSlot: "primary",
        drawerSection: "content",
        drawerOrder: 10,
      },
      {
        key: "channel",
        label: "Channel",
        labelKey: "messaging.columns.channel",
        type: "badge",
        sortable: true,
        defaultVisibleInTable: true,
        tableOrder: 20,
        cardSlot: "badge",
        drawerSection: "delivery",
        drawerOrder: 20,
        badgeVariantMap: {
          sms: { label: "SMS", tone: "info", className: SEMANTIC_BADGE.info },
          whatsapp: { label: "WhatsApp", tone: "success", className: SEMANTIC_BADGE.success },
          email: { label: "Email", tone: "primary", className: SEMANTIC_BADGE.primary },
        },
      },
      {
        key: "status",
        label: "Status",
        labelKey: "messaging.columns.status",
        type: "status",
        sortable: true,
        defaultVisibleInTable: true,
        tableOrder: 30,
        cardSlot: "badge",
        drawerSection: "delivery",
        drawerOrder: 30,
        badgeVariantMap: {
          sent: { label: "Sent", tone: "primary", className: SEMANTIC_BADGE.primary },
          delivered: { label: "Delivered", tone: "success", className: SEMANTIC_BADGE.success },
          failed: { label: "Failed", tone: "destructive", className: SEMANTIC_BADGE.destructive },
          queued: { label: "Queued", tone: "warning", className: SEMANTIC_BADGE.warning },
          skipped: { label: "Skipped", tone: "muted", className: SEMANTIC_BADGE.muted },
        },
      },
      {
        key: "category",
        label: "Category",
        labelKey: "messaging.columns.category",
        type: "badge",
        sortable: true,
        defaultVisibleInTable: true,
        tableOrder: 40,
        cardSlot: "secondary",
        drawerSection: "classification",
        drawerOrder: 40,
        badgeVariantMap: {
          general: { label: "General", tone: "muted", className: SEMANTIC_BADGE.muted },
          attendance: { label: "Attendance", tone: "info", className: SEMANTIC_BADGE.info },
          financial: { label: "Financial", tone: "warning", className: SEMANTIC_BADGE.warning },
          academic: { label: "Academic", tone: "primary", className: SEMANTIC_BADGE.primary },
          emergency: { label: "Emergency", tone: "destructive", className: SEMANTIC_BADGE.destructive },
        },
      },
      {
        key: "sentAt",
        label: "Sent At",
        labelKey: "messaging.columns.sentAt",
        type: "datetime",
        sortable: true,
        defaultVisibleInTable: true,
        tableOrder: 50,
        cardSlot: "meta",
        drawerSection: "delivery",
        drawerOrder: 50,
      },
      {
        key: "subject",
        label: "Subject",
        labelKey: "messaging.columns.subject",
        type: "text",
        sortable: false,
        defaultVisibleInTable: false,
        tableOrder: 60,
        cardSlot: "meta",
        drawerSection: "content",
        drawerOrder: 60,
      },
      {
        key: "errorMessage",
        label: "Error Details",
        labelKey: "messaging.columns.errorMessage",
        type: "text",
        sortable: false,
        defaultVisibleInTable: false,
        tableOrder: 70,
        cardSlot: "hidden",
        drawerSection: "delivery",
        drawerOrder: 70,
      },
    ],
  });
