import type { Contact, Student } from "@mms/shared";
import { SEMANTIC_BADGE } from "@/lib/semanticTone";
import type { EntityDescriptor } from "@/types/entityRegistry";
import { createEntityDescriptor } from "../entityDescriptorFactory";

export const contactsEntityDescriptor: EntityDescriptor<Contact> = createEntityDescriptor<Contact>({
  entityType: "contacts",
  singularLabel: "Contact",
  pluralLabel: "Contacts",
  idField: "id",
  titleField: "name",
  fields: [
    {
      key: "name",
      label: "Full Name",
      labelKey: "contacts.columns.name",
      type: "text",
      sortable: true,
      defaultVisibleInTable: true,
      tableOrder: 10,
      fixed: true,
      cardSlot: "primary",
      drawerSection: "identity",
      drawerOrder: 10,
    },
    {
      key: "phone",
      label: "Phone Number",
      labelKey: "contacts.columns.phone",
      type: "phone",
      sortable: false,
      defaultVisibleInTable: true,
      tableOrder: 20,
      cardSlot: "secondary",
      drawerSection: "contact",
      drawerOrder: 20,
    },
    {
      key: "email",
      label: "Email Address",
      labelKey: "contacts.columns.email",
      type: "email",
      sortable: false,
      defaultVisibleInTable: true,
      tableOrder: 30,
      cardSlot: "meta",
      drawerSection: "contact",
      drawerOrder: 30,
    },
    {
      key: "gender",
      label: "Gender",
      labelKey: "contacts.columns.gender",
      type: "badge",
      sortable: true,
      defaultVisibleInTable: true,
      tableOrder: 40,
      cardSlot: "badge",
      drawerSection: "identity",
      drawerOrder: 40,
      badgeVariantMap: {
        male: { label: "Male", tone: "info", className: SEMANTIC_BADGE.info },
        female: { label: "Female", tone: "secondary", className: SEMANTIC_BADGE.secondary },
      },
    },
    {
      key: "whatsappStatus",
      label: "WhatsApp Status",
      labelKey: "contacts.columns.whatsappStatus",
      type: "status",
      sortable: false,
      defaultVisibleInTable: false,
      tableOrder: 50,
      cardSlot: "meta",
      drawerSection: "contact",
      drawerOrder: 50,
    },
    {
      key: "cnic",
      label: "National ID / CNIC",
      labelKey: "contacts.columns.cnic",
      type: "text",
      sortable: false,
      defaultVisibleInTable: false,
      tableOrder: 60,
      cardSlot: "hidden",
      drawerSection: "identity",
      drawerOrder: 60,
    },
    {
      key: "city",
      label: "City",
      labelKey: "contacts.columns.city",
      type: "text",
      sortable: true,
      defaultVisibleInTable: true,
      tableOrder: 70,
      cardSlot: "meta",
      drawerSection: "address",
      drawerOrder: 70,
    },
  ],
});

export const studentsEntityDescriptor: EntityDescriptor<Student> = createEntityDescriptor<Student>({
  entityType: "students",
  singularLabel: "Student",
  pluralLabel: "Students",
  idField: "id",
  titleField: "name",
  fields: [
    {
      key: "name",
      label: "Student Name",
      labelKey: "students.columns.name",
      type: "text",
      sortable: true,
      defaultVisibleInTable: true,
      tableOrder: 10,
      fixed: true,
      cardSlot: "primary",
      drawerSection: "identity",
      drawerOrder: 10,
    },
    {
      key: "grNumber",
      label: "GR Number",
      labelKey: "students.columns.grNumber",
      type: "text",
      sortable: true,
      defaultVisibleInTable: true,
      tableOrder: 20,
      cardSlot: "secondary",
      drawerSection: "academic",
      drawerOrder: 20,
    },
    {
      key: "status",
      label: "Enrollment Status",
      labelKey: "students.columns.status",
      type: "status",
      sortable: true,
      defaultVisibleInTable: true,
      tableOrder: 30,
      cardSlot: "badge",
      drawerSection: "academic",
      drawerOrder: 30,
    },
    {
      key: "gender",
      label: "Gender",
      labelKey: "students.columns.gender",
      type: "badge",
      sortable: true,
      defaultVisibleInTable: true,
      tableOrder: 40,
      cardSlot: "badge",
      drawerSection: "identity",
      drawerOrder: 40,
      badgeVariantMap: {
        male: { label: "Male", tone: "info", className: SEMANTIC_BADGE.info },
        female: { label: "Female", tone: "secondary", className: SEMANTIC_BADGE.secondary },
      },
    },
    {
      key: "fatherName",
      label: "Father Name",
      labelKey: "students.columns.fatherName",
      type: "text",
      sortable: false,
      defaultVisibleInTable: true,
      tableOrder: 50,
      cardSlot: "meta",
      drawerSection: "family",
      drawerOrder: 50,
    },
    {
      key: "phone",
      label: "Phone",
      labelKey: "students.columns.phone",
      type: "phone",
      sortable: false,
      defaultVisibleInTable: true,
      tableOrder: 60,
      cardSlot: "meta",
      drawerSection: "contact",
      drawerOrder: 60,
    },
    {
      key: "enrollmentDate",
      label: "Enrollment Date",
      labelKey: "students.columns.registeredDate",
      type: "date",
      sortable: true,
      defaultVisibleInTable: false,
      tableOrder: 70,
      cardSlot: "hidden",
      drawerSection: "academic",
      drawerOrder: 70,
    },
  ],
});
