import type { PlatformWorkspaceRow, PlatformUserProfile, PlatformSettings } from "@mms/shared";
import { SEMANTIC_BADGE } from "@/lib/semanticTone";
import type { EntityDescriptor } from "@/types/entityRegistry";
import { createEntityDescriptor } from "../entityDescriptorFactory";

export const platformWorkspacesEntityDescriptor: EntityDescriptor<PlatformWorkspaceRow> =
  createEntityDescriptor<PlatformWorkspaceRow>({
    entityType: "platformWorkspaces",
    singularLabel: "Workspace",
    pluralLabel: "Workspaces",
    idField: "subdomain",
    titleField: "madrasaName",
    fields: [
      {
        key: "madrasaName",
        label: "Madrasa Name",
        type: "text",
        sortable: true,
        defaultVisibleInTable: true,
        tableOrder: 10,
        fixed: true,
        cardSlot: "primary",
        drawerSection: "general",
        drawerOrder: 10,
      },
      {
        key: "subdomain",
        label: "Subdomain",
        type: "text",
        sortable: true,
        defaultVisibleInTable: true,
        tableOrder: 20,
        cardSlot: "secondary",
        drawerSection: "general",
        drawerOrder: 20,
      },
      {
        key: "enabled",
        label: "Active Status",
        labelKey: "platform.descriptor.workspace.enabled",
        type: "badge",
        sortable: true,
        defaultVisibleInTable: true,
        tableOrder: 30,
        cardSlot: "badge",
        drawerSection: "status",
        drawerOrder: 30,
        badgeVariantMap: {
          true: { label: "Active", tone: "success", className: SEMANTIC_BADGE.success },
          false: { label: "Disabled", tone: "muted", className: SEMANTIC_BADGE.muted },
        },
        accessor: (ws) => String(ws.enabled),
      },
      {
        key: "createdAt",
        label: "Created Date",
        type: "date",
        sortable: true,
        defaultVisibleInTable: true,
        tableOrder: 40,
        cardSlot: "meta",
        drawerSection: "general",
        drawerOrder: 40,
      },
    ],
  });

export const platformUsersEntityDescriptor: EntityDescriptor<PlatformUserProfile> =
  createEntityDescriptor<PlatformUserProfile>({
    entityType: "platformUsers",
    singularLabel: "Platform Admin",
    pluralLabel: "Platform Admins",
    idField: "id",
    titleField: "name",
    fields: [
      {
        key: "name",
        label: "Name",
        type: "text",
        sortable: true,
        defaultVisibleInTable: true,
        tableOrder: 10,
        fixed: true,
        cardSlot: "primary",
        drawerSection: "identity",
        drawerOrder: 10,
      },
      {
        key: "email",
        label: "Email",
        type: "email",
        sortable: true,
        defaultVisibleInTable: true,
        tableOrder: 20,
        cardSlot: "secondary",
        drawerSection: "identity",
        drawerOrder: 20,
      },
      {
        key: "role",
        label: "Role",
        type: "badge",
        sortable: true,
        defaultVisibleInTable: true,
        tableOrder: 30,
        cardSlot: "badge",
        drawerSection: "access",
        drawerOrder: 30,
        badgeVariantMap: {
          super_user: { label: "Super User", tone: "primary", className: SEMANTIC_BADGE.primary },
          admin: { label: "Admin", tone: "info", className: SEMANTIC_BADGE.info },
        },
      },
      {
        key: "disabledAt",
        label: "Status",
        labelKey: "platform.descriptor.user.status",
        type: "badge",
        sortable: true,
        defaultVisibleInTable: true,
        tableOrder: 40,
        cardSlot: "badge",
        drawerSection: "access",
        drawerOrder: 40,
        badgeVariantMap: {
          active: { label: "Active", tone: "success", className: SEMANTIC_BADGE.success },
          disabled: { label: "Disabled", tone: "destructive", className: SEMANTIC_BADGE.destructive },
        },
        accessor: (u) => (u.disabledAt ? "disabled" : "active"),
      },
      {
        key: "createdAt",
        label: "Created At",
        type: "date",
        sortable: true,
        defaultVisibleInTable: true,
        tableOrder: 50,
        cardSlot: "meta",
        drawerSection: "metadata",
        drawerOrder: 50,
      },
    ],
  });

export const platformSettingsEntityDescriptor: EntityDescriptor<PlatformSettings> =
  createEntityDescriptor<PlatformSettings>({
    entityType: "platformSettings",
    singularLabel: "Platform Setting",
    pluralLabel: "Platform Settings",
    idField: "id",
    titleField: "certbotEmail",
    fields: [
      {
        key: "certbotEmail",
        label: "Certbot Email",
        type: "email",
        defaultVisibleInTable: true,
        tableOrder: 10,
        fixed: true,
        cardSlot: "primary",
        drawerSection: "ssl",
        drawerOrder: 10,
      },
      {
        key: "syncTlsOnCreate",
        label: "Auto Sync TLS",
        type: "boolean",
        defaultVisibleInTable: true,
        tableOrder: 20,
        cardSlot: "badge",
        drawerSection: "ssl",
        drawerOrder: 20,
      },
      {
        key: "tlsExtraSans",
        label: "Extra SANs",
        type: "text",
        defaultVisibleInTable: true,
        tableOrder: 30,
        cardSlot: "secondary",
        drawerSection: "ssl",
        drawerOrder: 30,
      },
    ],
  });
