import type { QuestionBankQuestion } from "@mms/shared";
import type { EntityDescriptor } from "@/types/entityRegistry";
import { SEMANTIC_BADGE } from "@/lib/semanticTone";
import { createEntityDescriptor } from "../entityDescriptorFactory";

export const questionBankEntityDescriptor: EntityDescriptor<QuestionBankQuestion> =
  createEntityDescriptor<QuestionBankQuestion>({
    entityType: "questionBank",
    singularLabel: "Question",
    pluralLabel: "Questions",
    idField: "id",
    titleField: "text",
    fields: [
      {
        key: "text",
        label: "Question",
        labelKey: "questionBank.columns.text",
        type: "text",
        sortable: true,
        defaultVisibleInTable: true,
        tableOrder: 10,
        fixed: true,
        cardSlot: "primary",
        drawerSection: "content",
        drawerOrder: 10,
      },
      {
        key: "type",
        label: "Type",
        labelKey: "questionBank.columns.type",
        type: "badge",
        sortable: true,
        defaultVisibleInTable: true,
        tableOrder: 20,
        cardSlot: "badge",
        drawerSection: "classification",
        drawerOrder: 20,
        badgeVariantMap: {
          mcq: { label: "MCQ", tone: "info", className: SEMANTIC_BADGE.info },
          short_answer: { label: "Short Answer", tone: "primary", className: SEMANTIC_BADGE.primary },
          true_false: { label: "True/False", tone: "secondary", className: SEMANTIC_BADGE.secondary },
          essay: { label: "Essay", tone: "muted", className: SEMANTIC_BADGE.muted },
        },
      },
      {
        key: "difficulty",
        label: "Difficulty",
        labelKey: "questionBank.columns.difficulty",
        type: "badge",
        sortable: true,
        defaultVisibleInTable: true,
        tableOrder: 30,
        cardSlot: "badge",
        drawerSection: "classification",
        drawerOrder: 30,
        badgeVariantMap: {
          easy: { label: "Easy", tone: "success", className: SEMANTIC_BADGE.success },
          medium: { label: "Medium", tone: "warning", className: SEMANTIC_BADGE.warning },
          hard: { label: "Hard", tone: "destructive", className: SEMANTIC_BADGE.destructive },
        },
      },
      {
        key: "category",
        label: "Category",
        labelKey: "questionBank.columns.category",
        type: "text",
        sortable: true,
        defaultVisibleInTable: true,
        tableOrder: 40,
        cardSlot: "secondary",
        drawerSection: "classification",
        drawerOrder: 40,
      },
      {
        key: "language",
        label: "Language",
        labelKey: "questionBank.columns.language",
        type: "badge",
        sortable: true,
        defaultVisibleInTable: true,
        tableOrder: 50,
        cardSlot: "meta",
        drawerSection: "details",
        drawerOrder: 50,
      },
      {
        key: "source",
        label: "Source",
        labelKey: "questionBank.columns.source",
        type: "text",
        sortable: false,
        defaultVisibleInTable: false,
        tableOrder: 60,
        cardSlot: "hidden",
        drawerSection: "details",
        drawerOrder: 60,
      },
    ],
  });
