import type { Session } from "@mms/shared";
import type { EntityDescriptor } from "@/types/entityRegistry";
import { createEntityDescriptor } from "../entityDescriptorFactory";

export const sessionsEntityDescriptor: EntityDescriptor<Session> = createEntityDescriptor<Session>({
  entityType: "sessions",
  singularLabel: "Academic Session",
  pluralLabel: "Academic Sessions",
  idField: "id",
  titleField: "name",
  fields: [
    {
      key: "name",
      label: "Session Name",
      labelKey: "sessions.columns.name",
      type: "text",
      sortable: true,
      defaultVisibleInTable: true,
      tableOrder: 10,
      fixed: true,
      cardSlot: "primary",
      drawerSection: "details",
      drawerOrder: 10,
    },
    {
      key: "code",
      label: "Session Code",
      labelKey: "sessions.columns.code",
      type: "text",
      sortable: true,
      defaultVisibleInTable: true,
      tableOrder: 20,
      cardSlot: "secondary",
      drawerSection: "details",
      drawerOrder: 20,
    },
    {
      key: "status",
      label: "Status",
      labelKey: "sessions.columns.status",
      type: "status",
      sortable: true,
      defaultVisibleInTable: true,
      tableOrder: 30,
      cardSlot: "badge",
      drawerSection: "details",
      drawerOrder: 30,
    },
    {
      key: "startDate",
      label: "Start Date",
      labelKey: "sessions.columns.startDate",
      type: "date",
      sortable: true,
      defaultVisibleInTable: true,
      tableOrder: 40,
      cardSlot: "meta",
      drawerSection: "timeline",
      drawerOrder: 40,
    },
    {
      key: "endDate",
      label: "End Date",
      labelKey: "sessions.columns.endDate",
      type: "date",
      sortable: true,
      defaultVisibleInTable: true,
      tableOrder: 50,
      cardSlot: "meta",
      drawerSection: "timeline",
      drawerOrder: 50,
    },
  ],
});
