import type { CustomWidget } from "@/tenant/features/reports/components/pinnedWidgets/types";

export function buildWidgetBuilderPreview(
  editWidgetConfig: CustomWidget | null,
  category: string,
  builderTitle: string,
  builderCollection: CustomWidget["collection"],
  widgetType: CustomWidget["widgetType"],
  builderOperation: CustomWidget["operation"],
  builderTargetField: string,
  builderFilterField: string,
  builderFilterOperator: CustomWidget["filterOperator"],
  builderFilterValue: string,
  builderColor: string,
  thresholdEnabled: boolean,
  thresholdCondition: "lt" | "gt" | "equals",
  thresholdValue: string,
  thresholdColor: "red" | "amber" | "yellow",
  switchActionType: "app_setting" | "db_record",
  switchStateKey: string,
  switchCollection: CustomWidget["collection"],
  switchRecordId: string,
  switchField: string,
  switchLabelOn: string,
  switchLabelOff: string,
  builderIcon: string,
  subTextType: "fixed" | "dynamic",
  fixedSubText: string,
  trend: number,
  trendType: "manual" | "database",
  builderRole: string,
  fallbackTitle: string,
): CustomWidget {
  return {
    id: editWidgetConfig?.id || "preview",
    title: builderTitle || fallbackTitle,
    category: editWidgetConfig?.category || category,
    collection: builderCollection,
    widgetType,
    operation: builderOperation,
    targetField: builderTargetField,
    filterField: builderFilterField,
    filterOperator: builderFilterOperator,
    filterValue: builderFilterValue,
    color: builderColor,
    isPinnedToDashboard: editWidgetConfig?.isPinnedToDashboard || false,
    thresholdEnabled,
    thresholdCondition,
    thresholdValue: thresholdValue ? Number(thresholdValue) : undefined,
    thresholdColor,
    switchActionType,
    switchStateKey,
    switchCollection,
    switchRecordId,
    switchField,
    switchLabelOn,
    switchLabelOff,
    icon: builderIcon,
    subTextType,
    fixedSubText,
    trend,
    trendType,
    role: builderRole,
  };
}

export function buildWidgetSavePayload(
  editWidgetConfig: CustomWidget | null,
  category: string,
  mode: "dashboard" | "kpi",
  builderTitle: string,
  builderCollection: CustomWidget["collection"],
  widgetType: CustomWidget["widgetType"],
  builderOperation: CustomWidget["operation"],
  builderTargetField: string,
  builderFilterField: string,
  builderFilterOperator: CustomWidget["filterOperator"],
  builderFilterValue: string,
  builderColor: string,
  thresholdEnabled: boolean,
  thresholdCondition: "lt" | "gt" | "equals",
  thresholdValue: string,
  thresholdColor: "red" | "amber" | "yellow",
  switchActionType: "app_setting" | "db_record",
  switchStateKey: string,
  switchCollection: CustomWidget["collection"],
  switchRecordId: string,
  switchField: string,
  switchLabelOn: string,
  switchLabelOff: string,
  builderIcon: string,
  subTextType: "fixed" | "dynamic",
  fixedSubText: string,
  trend: number,
  trendType: "manual" | "database",
  builderRole: string,
): CustomWidget {
  return {
    id: editWidgetConfig?.id || "widget-" + crypto.randomUUID(),
    title: builderTitle,
    category: editWidgetConfig?.category || category,
    collection: builderCollection,
    widgetType,
    operation: builderOperation,
    targetField: builderTargetField,
    filterField: builderFilterField,
    filterOperator: builderFilterOperator,
    filterValue: builderFilterValue,
    color: builderColor,
    isPinnedToDashboard: editWidgetConfig?.isPinnedToDashboard || false,
    thresholdEnabled,
    thresholdCondition,
    thresholdValue: thresholdValue ? Number(thresholdValue) : undefined,
    thresholdColor,
    switchActionType,
    switchStateKey,
    switchCollection,
    switchRecordId,
    switchField,
    switchLabelOn,
    switchLabelOff,
    icon: widgetType === "card" ? builderIcon : undefined,
    subTextType: widgetType === "card" ? subTextType : undefined,
    fixedSubText: (widgetType === "card" && subTextType === "fixed") ? fixedSubText : undefined,
    trend: widgetType === "card" ? trend : undefined,
    trendType: widgetType === "card" ? trendType : undefined,
    role: (widgetType === "card" && mode === "dashboard") ? builderRole : undefined,
  };
}
