import type { ErdDomain } from './erdCatalogTypes.js';

/** Accounting + student billing tables (Drizzle `accounting.ts` / `finance.ts`). */
export const ERD_DOMAIN_ACCOUNTING: ErdDomain = {
  id: 'accounting',
  labelKey: 'nav.accounting',
  tables: [
    {
      name: 'accounting_accounts',
      columns: [
        { name: 'workspace_subdomain', type: 'text', kind: 'pk' },
        { name: 'id', type: 'text', kind: 'pk' },
        { name: 'code', type: 'varchar(50)', kind: 'unique' },
        { name: 'name', type: 'varchar(150)', kind: 'column' },
        { name: 'type', type: 'varchar(50)', kind: 'column' },
        { name: 'deleted_at', type: 'timestamptz', kind: 'column' },
      ],
    },
    {
      name: 'accounting_fiscal_years',
      columns: [
        { name: 'workspace_subdomain', type: 'text', kind: 'pk' },
        { name: 'id', type: 'text', kind: 'pk' },
        { name: 'label', type: 'varchar(120)', kind: 'column' },
        { name: 'start_date', type: 'varchar(10)', kind: 'column' },
        { name: 'end_date', type: 'varchar(10)', kind: 'column' },
        { name: 'status', type: 'varchar(20)', kind: 'column' },
        { name: 'closed_at', type: 'timestamptz', kind: 'column' },
      ],
    },
    {
      name: 'accounting_posting_rules',
      columns: [
        { name: 'workspace_subdomain', type: 'text', kind: 'pk' },
        { name: 'ar_account_id', type: 'text', kind: 'fk' },
        { name: 'cash_account_id', type: 'text', kind: 'fk' },
        { name: 'income_account_id', type: 'text', kind: 'fk' },
      ],
    },
    {
      name: 'accounting_opening_balances',
      columns: [
        { name: 'workspace_subdomain', type: 'text', kind: 'pk' },
        { name: 'fiscal_year_id', type: 'text', kind: 'pk' },
        { name: 'id', type: 'text', kind: 'pk' },
        { name: 'account_id', type: 'text', kind: 'fk' },
        { name: 'debit', type: 'numeric(14,2)', kind: 'column' },
        { name: 'credit', type: 'numeric(14,2)', kind: 'column' },
      ],
    },
    {
      name: 'accounting_bank_statements',
      columns: [
        { name: 'workspace_subdomain', type: 'text', kind: 'pk' },
        { name: 'id', type: 'text', kind: 'pk' },
        { name: 'account_id', type: 'text', kind: 'fk' },
        { name: 'period_start', type: 'varchar(10)', kind: 'column' },
        { name: 'period_end', type: 'varchar(10)', kind: 'column' },
      ],
    },
    {
      name: 'accounting_bank_statement_lines',
      columns: [
        { name: 'workspace_subdomain', type: 'text', kind: 'pk' },
        { name: 'statement_id', type: 'text', kind: 'pk' },
        { name: 'id', type: 'text', kind: 'pk' },
        { name: 'amount', type: 'numeric(14,2)', kind: 'column' },
      ],
    },
    {
      name: 'accounting_bank_reconciliations',
      columns: [
        { name: 'workspace_subdomain', type: 'text', kind: 'pk' },
        { name: 'statement_line_id', type: 'text', kind: 'pk' },
        { name: 'journal_entry_id', type: 'text', kind: 'fk' },
        { name: 'journal_line_id', type: 'text', kind: 'fk' },
      ],
    },
    {
      name: 'accounting_entries',
      columns: [
        { name: 'workspace_subdomain', type: 'text', kind: 'pk' },
        { name: 'id', type: 'text', kind: 'pk' },
        { name: 'date', type: 'varchar(10)', kind: 'column' },
        { name: 'ref', type: 'varchar(100)', kind: 'column' },
        { name: 'status', type: 'varchar(20)', kind: 'column' },
        { name: 'fiscal_year', type: 'varchar(64)', kind: 'column' },
        { name: 'fiscal_year_id', type: 'text', kind: 'fk' },
        { name: 'source_type', type: 'varchar(20)', kind: 'column' },
        { name: 'source_id', type: 'varchar(64)', kind: 'column' },
      ],
    },
    {
      name: 'accounting_journal_lines',
      columns: [
        { name: 'workspace_subdomain', type: 'text', kind: 'pk' },
        { name: 'entry_id', type: 'text', kind: 'pk' },
        { name: 'id', type: 'text', kind: 'pk' },
        { name: 'account_id', type: 'text', kind: 'fk' },
        { name: 'debit', type: 'numeric(14,2)', kind: 'column' },
        { name: 'credit', type: 'numeric(14,2)', kind: 'column' },
      ],
    },
    {
      name: 'accounting_entry_tags',
      columns: [
        { name: 'workspace_subdomain', type: 'text', kind: 'pk' },
        { name: 'entry_id', type: 'text', kind: 'pk' },
        { name: 'tag', type: 'varchar(64)', kind: 'pk' },
      ],
    },
    {
      name: 'accounting_entry_attachments',
      columns: [
        { name: 'workspace_subdomain', type: 'text', kind: 'pk' },
        { name: 'entry_id', type: 'text', kind: 'pk' },
        { name: 'url', type: 'text', kind: 'pk' },
      ],
    },
  ],
  relationships: [
    {
      fromTable: 'accounting_entries',
      fromColumn: 'fiscal_year_id',
      toTable: 'accounting_fiscal_years',
      toColumn: 'id',
      cardinality: 'N:1',
    },
    {
      fromTable: 'accounting_journal_lines',
      fromColumn: 'entry_id',
      toTable: 'accounting_entries',
      toColumn: 'id',
      cardinality: 'N:1',
    },
    {
      fromTable: 'accounting_journal_lines',
      fromColumn: 'account_id',
      toTable: 'accounting_accounts',
      toColumn: 'id',
      cardinality: 'N:1',
    },
    {
      fromTable: 'accounting_entry_tags',
      fromColumn: 'entry_id',
      toTable: 'accounting_entries',
      toColumn: 'id',
      cardinality: 'N:1',
      onDelete: 'cascade',
    },
    {
      fromTable: 'accounting_entry_attachments',
      fromColumn: 'entry_id',
      toTable: 'accounting_entries',
      toColumn: 'id',
      cardinality: 'N:1',
      onDelete: 'cascade',
    },
    {
      fromTable: 'accounting_opening_balances',
      fromColumn: 'fiscal_year_id',
      toTable: 'accounting_fiscal_years',
      toColumn: 'id',
      cardinality: 'N:1',
      onDelete: 'cascade',
    },
    {
      fromTable: 'accounting_opening_balances',
      fromColumn: 'account_id',
      toTable: 'accounting_accounts',
      toColumn: 'id',
      cardinality: 'N:1',
    },
    {
      fromTable: 'accounting_bank_statements',
      fromColumn: 'account_id',
      toTable: 'accounting_accounts',
      toColumn: 'id',
      cardinality: 'N:1',
    },
    {
      fromTable: 'accounting_bank_statement_lines',
      fromColumn: 'statement_id',
      toTable: 'accounting_bank_statements',
      toColumn: 'id',
      cardinality: 'N:1',
      onDelete: 'cascade',
    },
    {
      fromTable: 'accounting_bank_reconciliations',
      fromColumn: 'journal_entry_id',
      toTable: 'accounting_entries',
      toColumn: 'id',
      cardinality: 'N:1',
      onDelete: 'cascade',
    },
  ],
};

/** Student invoices and payments (Drizzle `finance.ts`). */
export const ERD_DOMAIN_FINANCE: ErdDomain = {
  id: 'finance',
  labelKey: 'nav.finance',
  tables: [
    {
      name: 'finance_invoices',
      columns: [
        { name: 'workspace_subdomain', type: 'text', kind: 'pk' },
        { name: 'id', type: 'text', kind: 'pk' },
        { name: 'student_id', type: 'varchar(64)', kind: 'fk' },
        { name: 'final_amt', type: 'numeric(12,2)', kind: 'column' },
        { name: 'status', type: 'varchar(20)', kind: 'column' },
        { name: 'due_date', type: 'varchar(10)', kind: 'column' },
        { name: 'invoice_number', type: 'varchar(40)', kind: 'unique' },
        { name: 'fee_structure_id', type: 'text', kind: 'fk' },
        { name: 'billing_period', type: 'varchar(7)', kind: 'column' },
        { name: 'enrollment_id', type: 'varchar(64)', kind: 'fk' },
        { name: 'family_contact_id', type: 'varchar(64)', kind: 'fk' },
        { name: 'late_fee_amt', type: 'numeric(12,2)', kind: 'column' },
        { name: 'credited_amt', type: 'numeric(12,2)', kind: 'column' },
        { name: 'last_reminded_at', type: 'timestamptz', kind: 'column' },
        { name: 'reminder_count', type: 'integer', kind: 'column' },
      ],
    },
    {
      name: 'finance_credit_notes',
      columns: [
        { name: 'workspace_subdomain', type: 'text', kind: 'pk' },
        { name: 'id', type: 'text', kind: 'pk' },
        { name: 'invoice_id', type: 'text', kind: 'fk' },
        { name: 'amount', type: 'numeric(12,2)', kind: 'column' },
        { name: 'reason', type: 'varchar(200)', kind: 'column' },
      ],
    },
    {
      name: 'finance_fee_structures',
      columns: [
        { name: 'workspace_subdomain', type: 'text', kind: 'pk' },
        { name: 'id', type: 'text', kind: 'pk' },
        { name: 'name', type: 'varchar(150)', kind: 'column' },
        { name: 'session', type: 'varchar(120)', kind: 'column' },
        { name: 'class_name', type: 'varchar(120)', kind: 'column' },
        { name: 'frequency', type: 'varchar(20)', kind: 'column' },
      ],
    },
    {
      name: 'finance_fee_items',
      columns: [
        { name: 'workspace_subdomain', type: 'text', kind: 'pk' },
        { name: 'structure_id', type: 'text', kind: 'pk' },
        { name: 'id', type: 'text', kind: 'pk' },
        { name: 'amount', type: 'numeric(12,2)', kind: 'column' },
      ],
    },
    {
      name: 'finance_invoice_lines',
      columns: [
        { name: 'workspace_subdomain', type: 'text', kind: 'pk' },
        { name: 'invoice_id', type: 'text', kind: 'pk' },
        { name: 'id', type: 'text', kind: 'pk' },
        { name: 'amount', type: 'numeric(12,2)', kind: 'column' },
      ],
    },
    {
      name: 'finance_payment_allocations',
      columns: [
        { name: 'workspace_subdomain', type: 'text', kind: 'pk' },
        { name: 'payment_id', type: 'text', kind: 'pk' },
        { name: 'id', type: 'text', kind: 'pk' },
        { name: 'invoice_id', type: 'text', kind: 'fk' },
        { name: 'amount', type: 'numeric(12,2)', kind: 'column' },
      ],
    },
    {
      name: 'finance_payments',
      columns: [
        { name: 'workspace_subdomain', type: 'text', kind: 'pk' },
        { name: 'id', type: 'text', kind: 'pk' },
        { name: 'invoice_id', type: 'text', kind: 'fk' },
        { name: 'student_id', type: 'varchar(64)', kind: 'column' },
        { name: 'amount', type: 'numeric(12,2)', kind: 'column' },
        { name: 'method', type: 'varchar(50)', kind: 'column' },
      ],
    },
    {
      name: 'enrollments',
      columns: [
        { name: 'workspace_subdomain', type: 'text', kind: 'pk' },
        { name: 'id', type: 'text', kind: 'pk' },
        { name: 'student_id', type: 'varchar(64)', kind: 'fk' },
        { name: 'invoice_id', type: 'varchar(64)', kind: 'fk' },
      ],
    },
    {
      name: 'students',
      columns: [
        { name: 'workspace_subdomain', type: 'text', kind: 'pk' },
        { name: 'id', type: 'text', kind: 'pk' },
        { name: 'contact_id', type: 'text', kind: 'fk' },
        { name: 'gr_number', type: 'varchar(100)', kind: 'column' },
      ],
    },
    {
      name: 'contacts',
      columns: [
        { name: 'workspace_subdomain', type: 'text', kind: 'pk' },
        { name: 'id', type: 'text', kind: 'pk' },
        { name: 'full_name', type: 'varchar(200)', kind: 'column' },
      ],
    },
  ],
  relationships: [
    {
      fromTable: 'finance_payments',
      fromColumn: 'invoice_id',
      toTable: 'finance_invoices',
      toColumn: 'id',
      cardinality: 'N:1',
      onDelete: 'cascade',
    },
    {
      fromTable: 'finance_invoices',
      fromColumn: 'student_id',
      toTable: 'students',
      toColumn: 'id',
      cardinality: 'N:1',
    },
    {
      fromTable: 'finance_invoices',
      fromColumn: 'enrollment_id',
      toTable: 'enrollments',
      toColumn: 'id',
      cardinality: 'N:1',
    },
    {
      fromTable: 'enrollments',
      fromColumn: 'invoice_id',
      toTable: 'finance_invoices',
      toColumn: 'id',
      cardinality: 'N:1',
    },
    {
      fromTable: 'enrollments',
      fromColumn: 'student_id',
      toTable: 'students',
      toColumn: 'id',
      cardinality: 'N:1',
    },
    {
      fromTable: 'finance_invoices',
      fromColumn: 'fee_structure_id',
      toTable: 'finance_fee_structures',
      toColumn: 'id',
      cardinality: 'N:1',
    },
    {
      fromTable: 'finance_fee_items',
      fromColumn: 'structure_id',
      toTable: 'finance_fee_structures',
      toColumn: 'id',
      cardinality: 'N:1',
      onDelete: 'cascade',
    },
    {
      fromTable: 'finance_invoice_lines',
      fromColumn: 'invoice_id',
      toTable: 'finance_invoices',
      toColumn: 'id',
      cardinality: 'N:1',
      onDelete: 'cascade',
    },
    {
      fromTable: 'finance_payment_allocations',
      fromColumn: 'payment_id',
      toTable: 'finance_payments',
      toColumn: 'id',
      cardinality: 'N:1',
      onDelete: 'cascade',
    },
    {
      fromTable: 'finance_payment_allocations',
      fromColumn: 'invoice_id',
      toTable: 'finance_invoices',
      toColumn: 'id',
      cardinality: 'N:1',
    },
    {
      fromTable: 'finance_credit_notes',
      fromColumn: 'invoice_id',
      toTable: 'finance_invoices',
      toColumn: 'id',
      cardinality: 'N:1',
      onDelete: 'cascade',
    },
    {
      fromTable: 'finance_invoices',
      fromColumn: 'family_contact_id',
      toTable: 'contacts',
      toColumn: 'id',
      cardinality: 'N:1',
    },
    {
      fromTable: 'students',
      fromColumn: 'contact_id',
      toTable: 'contacts',
      toColumn: 'id',
      cardinality: 'N:1',
    },
  ],
};
