/** Shared User interface used across frontend and backend. */
export interface User {
  id: string;
  /** Sign-in email (`loginEmail`); kept as `email` for JWT backward compatibility. */
  email: string;
  name: string;
  role: string;
  /** Madrasa subdomain this account belongs to. */
  workspaceSubdomain: string;
  /** Linked CRM contact for profile fields. */
  contactId?: string | number;
  loginEmail?: string;
  emailVerifiedAt?: string;
  /** Forces the user through password change before normal workspace access. */
  mustChangePassword?: boolean;
}

export * from './settingsTypes.js';
export * from './moduleFieldSchema.js';
export * from './globalSettingsTypes.js';
export * from './moduleSettingsTypes.js';
export * from './attendanceModuleSettings.js';
export * from './financeModuleSettings.js';
export * from './examinationsModuleSettings.js';
export * from './questionBankModuleSettings.js';
export * from './sessionsModuleSettings.js';
export * from './enrollmentsModuleSettings.js';
export * from './studentsModuleSettings.js';
export * from './teachersModuleSettings.js';
export * from './accountingModuleSettings.js';
export * from './hasanatModuleSettings.js';
export * from './usersModuleSettings.js';
export * from './imageOptimizationUtils.js';
export * from './moduleFieldConfigUtils.js';
export * from './settingsDateFormatters.js';
export * from './dashboardPreferencesTypes.js';
export * from './moduleFieldSetupDefaults.js';
export * from './llmSettingsTypes.js';
export * from './globalSettingsUtils.js';
export * from './languageUtils.js';
export * from './timezoneUtils.js';
export * from './dateFormatUtils.js';
export * from './emailIntegrationTypes.js';
export * from './emailProviderRegistry.js';
export * from './smsUtils.js';
export * from './appTranslations.js';
export * from './backupTypes.js';
export * from './backupCrypto.js';
export * from './brandingTypes.js';
export * from './brandingTheme.js';
export * from './brandingColorUtils.js';
export * from './brandingCssVariables.js';
export * from './brandingChartPalette.js';
export * from './chartPalettes.js';
export * from './logoBrandColors.js';
export * from './logoPaletteSampling.js';
export * from './brandingCornerStyle.js';
export * from './moduleTierTabs.js';
export * from './contactFieldDependencies.js';
export * from './contactsReportFields.js';
export * from './contactTypes.js';
export * from './contactDuplicateUtils.js';
export * from './contactsModuleManifest.js';
export * from './contactsPreferencesTypes.js';
export * from './contactsSearchUtils.js';
export * from './contactsSortUtils.js';
export * from './contactsMetricsUtils.js';
export * from './contactsReportAnalytics.js';
export * from './contactsWidgetAggregate.js';
export * from './studentsWidgetAggregate.js';
export * from './backgroundJobTypes.js';
export * from './contactProfileCompleteness.js';
export * from './contactsListQuery.js';
export * from './contactsExportUtils.js';
export * from './contactsDuplicatesQuery.js';
export type { ContactsSavedReportShareScope, ContactsSavedReportViewer } from './contactsSavedReportUtils.js';
export {
  canDeleteContactsSavedReport,
  canViewContactsSavedReport,
  validateContactsSavedReportDrillDown,
} from './contactsSavedReportUtils.js';
export * from './contactResponseSanitizer.js';
export * from './contactSyncDiff.js';
export * from './contactSoftDelete.js';
export * from './contactFieldAccess.js';
export * from './contactColumnAccess.js';
export * from './workspaceTypes.js';
export * from './tenantUtils.js';
export * from './tenantStorage.js';
export * from './userTypes.js';
export * from './questionBankTypes.js';
export * from './questionBankCore.js';
export * from './questionBankEntities.js';
export * from './questionBankAnswerUtils.js';
export * from './questionBankFormUtils.js';
export * from './questionBankCategoryUtils.js';
export * from './questionBankSourceUtils.js';
export * from './questionBankDefaults.js';
export * from './utils.js';
export * from './phoneUtils.js';
export * from './moneyFormatUtils.js';
export * from './ageUtils.js';
export * from './titleCaseUtils.js';
export * from './paginationUtils.js';
export * from './messagingPersonalizeUtils.js';
export * from './contactUtils.js';
export * from './blueprintVersionUtils.js';
export * from './widgetFilterUtils.js';
export * from './hasanatPointsUtils.js';
export * from './identityFormatUtils.js';
export * from './numberUtils.js';
export * from './csvUtils.js';
export * from './gradeUtils.js';
export * from './teacherTypes.js';
export * from './teacherUtils.js';
export * from './demoSeedBuilders.js';
export * from './demoTeachers.js';
export * from './demoStudents.js';
export * from './studentTypes.js';
export * from './studentsModuleManifest.js';
export * from './studentsListQuery.js';
export * from './studentRegistrationUtils.js';
export * from './studentSettingsUtils.js';
export * from './teachersModuleManifest.js';
export * from './teachersListQuery.js';
export * from './sessionsListQuery.js';
export * from './teacherRegistrationUtils.js';
export * from './teachersWidgetAggregate.js';
export * from './financeModuleManifest.js';
export * from './financeListQuery.js';
export * from './attendanceModuleManifest.js';
export * from './attendanceListQuery.js';
export * from './sessionsModuleManifest.js';
export * from './enrollmentsModuleManifest.js';
export * from './enrollmentsListQuery.js';
export * from './obligationsModuleManifest.js';
export * from './accountingModuleManifest.js';
export * from './hasanatModuleManifest.js';
export * from './examinationsModuleManifest.js';
export * from './questionBankModuleManifest.js';
export * from './usersModuleManifest.js';
export * from './moduleCommandMetrics.js';
export * from './moduleColumnPreferences.js';
export * from './studentUtils.js';
export * from './contactLinkPolicy.js';
export * from './linkedCollectionUtils.js';
export * from './permissions.js';
export * from './auditTypes.js';
export * from './platformTypes.js';
export * from './platformSetupValidation.js';
export * from './serverPorts.js';
export * from './tenantAuthTypes.js';
export * from './contactValidation.js';
export { buildDynamicStudentSchema, formatStudentZodIssues } from './studentValidation.js';
export * from './sessionTypes.js';
export * from './platformSettingsTypes.js';
export * from './platformSchemas.js';
export * from './apiSchemas.js';
export * from './messagingSchemas.js';
export * from './messagingModuleManifest.js';
export * from './savedReportsSchemas.js';
export * from './dashboardModuleManifest.js';
export * from './whatsappProvider.js';
export * from './vcardUtils.js';
