import type {
  QuestionBankQuestion,
  QuestionBankResult,
  QuestionBankTest,
} from './questionBankEntities.js';
import { normalizeQuestionBankQuestion } from './questionBankSourceUtils.js';

const DEFAULT_QUESTION_BANK_QUESTIONS_RAW: Array<Partial<QuestionBankQuestion> & Record<string, unknown>> = [
  {
    id: 'q1',
    categoryIds: ['cat1'],
    categoryId: 'cat1',
    type: 'mcq',
    difficulty: 'easy',
    questionLanguage: 'en',
    text: 'Which rule applies when noon sakinah is followed by a letter from (ي ن م و)?',
    options: ['Izhar', 'Idgham', 'Iqlab', 'Ikhfa'],
    answer: 'Idgham',
  },
  {
    id: 'q2',
    categoryIds: ['cat1'],
    categoryId: 'cat1',
    type: 'true_false',
    difficulty: 'easy',
    text: "Madd Tabee'i has a duration of 2 counts.",
    options: ['True', 'False'],
    answer: 'True',
  },
  {
    id: 'q3',
    categoryIds: ['cat3', 'cat1'],
    categoryId: 'cat3',
    type: 'mcq',
    difficulty: 'medium',
    text: 'Which pillar of Islam comes second after Shahada?',
    options: ['Sawm', 'Salah', 'Zakat', 'Hajj'],
    answer: 'Salah',
  },
  {
    id: 'q4',
    categoryIds: ['cat4'],
    categoryId: 'cat4',
    type: 'mcq',
    difficulty: 'medium',
    questionLanguage: 'ar',
    text: 'What is the plural of كتاب (kitab)?',
    options: ['كتب', 'كاتب', 'مكتبة', 'كتابة'],
    answer: 'كتب',
  },
  {
    id: 'q5',
    categoryIds: ['cat5'],
    categoryId: 'cat5',
    type: 'short',
    difficulty: 'hard',
    text: 'Explain the concept of Tawheed Al-Uluhiyyah in your own words.',
    options: [],
    answer:
      'Singling out Allah alone in acts of worship such as prayer, supplication, sacrifice and vows.',
  },
  {
    id: 'q6',
    categoryIds: ['cat2', 'cat3'],
    categoryId: 'cat2',
    type: 'mcq',
    difficulty: 'hard',
    text: 'In Surah Al-Baqarah, which verse is known as Ayat Al-Kursi?',
    options: ['Verse 255', 'Verse 256', 'Verse 257', 'Verse 258'],
    answer: 'Verse 255',
    sourceCitations: [
      {
        bookId: 'book-quran',
        citation: { surah: 'Al-Baqarah', ayah: '255', juz: '3', pageNumber: '42' },
      },
      {
        bookId: 'book-tafsir-ibn-kathir',
        citation: { surah: 'Al-Baqarah', ayah: '255', pageNumber: '120' },
      },
    ],
  },
  {
    id: 'q7',
    categoryIds: ['cat1'],
    categoryId: 'cat1',
    type: 'mcq',
    difficulty: 'medium',
    text: 'Which letter requires Qalqalah?',
    options: ['ب', 'أ', 'ه', 'ف'],
    answer: 'ب',
  },
  {
    id: 'q8',
    categoryIds: ['cat3'],
    categoryId: 'cat3',
    type: 'true_false',
    difficulty: 'easy',
    text: 'The Quran was revealed over a period of 23 years.',
    options: ['True', 'False'],
    answer: 'True',
  },
  {
    id: 'q9',
    categoryIds: ['cat4'],
    categoryId: 'cat4',
    type: 'fill_blank',
    difficulty: 'easy',
    questionLanguage: 'en',
    text: 'The plural of كتاب (kitab) is ___.',
    options: [],
    answer: 'كتب',
  },
  {
    id: 'q10',
    categoryIds: ['cat3'],
    categoryId: 'cat3',
    type: 'matching',
    difficulty: 'medium',
    text: 'Match each pillar to its order.',
    options: ['Shahada', 'Salah', 'Zakat'],
    answer: '1st pillar|||2nd pillar|||3rd pillar',
  },
  {
    id: 'q11',
    categoryIds: ['cat1'],
    categoryId: 'cat1',
    type: 'numeric',
    difficulty: 'easy',
    text: "How many counts does Madd Tabee'i have?",
    options: ['0'],
    answer: '2',
  },
  {
    id: 'q12',
    categoryIds: ['cat3'],
    categoryId: 'cat3',
    type: 'ordering',
    difficulty: 'medium',
    text: 'Arrange the pillars of Islam in order.',
    options: ['Shahada', 'Salah', 'Zakat', 'Sawm', 'Hajj'],
    answer: 'Shahada|||Salah|||Zakat|||Sawm|||Hajj',
  },
];

export const DEFAULT_QUESTION_BANK_QUESTIONS: QuestionBankQuestion[] =
  DEFAULT_QUESTION_BANK_QUESTIONS_RAW.map((question) => normalizeQuestionBankQuestion(question));

export const DEFAULT_QUESTION_BANK_TESTS: QuestionBankTest[] = [
  {
    id: 't1',
    name: 'Tajweed Basics — Term 1',
    categoryId: 'cat1',
    questionIds: ['q1', 'q2', 'q7'],
    difficulty: 'easy',
    duration: 20,
    createdAt: '2026-03-10',
  },
  {
    id: 't2',
    name: 'Islamic Studies Mid-Term',
    categoryId: 'cat3',
    questionIds: ['q3', 'q8'],
    difficulty: 'medium',
    duration: 30,
    createdAt: '2026-03-25',
  },
  {
    id: 't3',
    name: 'Comprehensive Assessment',
    categoryId: null,
    questionIds: ['q1', 'q3', 'q4', 'q5', 'q6'],
    difficulty: 'mixed',
    duration: 45,
    createdAt: '2026-04-05',
  },
];

export const DEFAULT_QUESTION_BANK_RESULTS: QuestionBankResult[] = [
  {
    id: 'r1',
    testId: 't1',
    studentName: 'Ahmed Ali',
    studentId: 's1',
    submittedAt: '2026-03-15',
    answers: { q1: 'Idgham', q2: 'True', q7: 'ب' },
    scores: { q1: 2, q2: 1, q7: 2 },
  },
  {
    id: 'r2',
    testId: 't1',
    studentName: 'Fatima Zahra',
    studentId: 's2',
    submittedAt: '2026-03-15',
    answers: { q1: 'Izhar', q2: 'True', q7: 'ب' },
    scores: { q1: 0, q2: 1, q7: 2 },
  },
  {
    id: 'r3',
    testId: 't1',
    studentName: 'Umar Hassan',
    studentId: 's3',
    submittedAt: '2026-03-15',
    answers: { q1: 'Idgham', q2: 'False', q7: 'أ' },
    scores: { q1: 2, q2: 0, q7: 0 },
  },
  {
    id: 'r4',
    testId: 't2',
    studentName: 'Ahmed Ali',
    studentId: 's1',
    submittedAt: '2026-03-28',
    answers: { q3: 'Salah', q8: 'True' },
    scores: { q3: 2, q8: 1 },
  },
  {
    id: 'r5',
    testId: 't2',
    studentName: 'Fatima Zahra',
    studentId: 's2',
    submittedAt: '2026-03-28',
    answers: { q3: 'Zakat', q8: 'True' },
    scores: { q3: 0, q8: 1 },
  },
];
