import type { FastifyInstance } from 'fastify';
import authRoutes from "./common/auth.js";
import { contactRoutes } from "./tenant/contacts.js";
import dbRoutes from "./common/db.js";
import emailRoutes from "./common/email.js";
import healthRoutes from "./common/health.js";
import platformAuthRoutes from "./platform/platformAuth.js";
import platformWorkspaceRoutes from "./platform/platformWorkspaces.js";
import platformUsersRoutes from "./platform/platformUsers.js";
import platformSettingsRoutes from "./platform/platformSettings.js";
import platformAdminSystemRoutes from "./platform/platformAdminSystem.js";
import publicRoutes from "./common/public.js";
import studentsRoutes from "./tenant/students.js";
import teachersRoutes from "./tenant/teachers.js";
import financeRoutes from "./tenant/finance.js";
import enrollmentsRoutes from "./tenant/enrollments.js";
import obligationsRoutes from "./tenant/obligations.js";
import accountingRoutes from "./tenant/accounting.js";
import hasanatRoutes from "./tenant/hasanat.js";
import examinationsRoutes from "./tenant/examinations.js";
import questionBankRoutes from "./tenant/questionBank.js";
import usersRoutes from "./tenant/users.js";
import attendanceRoutes from "./tenant/attendance.js";
import sessionsRoutes from "./tenant/sessions.js";
import backgroundJobRoutes from "./common/backgroundJobs.js";
import uploadRoutes from "./common/uploads.js";
import workspaceRoutes from "./tenant/workspace.js";
import aiRoutes from "./common/ai.js";
import websocketRoutes from "./common/websocket.js";
import messagingRoutes from "./tenant/messaging.js";
import savedReportsRoutes from "./tenant/savedReports.js";
import dashboardRoutes from "./tenant/dashboard.js";
import openapiRoutes from "./common/openapi.js";

export async function registerRoutes(app: FastifyInstance): Promise<void> {
  await app.register(openapiRoutes);
  await app.register(healthRoutes);
  await app.register(publicRoutes, { prefix: '/api/public' });
  await app.register(authRoutes, { prefix: '/api/auth' });
  await app.register(platformAuthRoutes, { prefix: '/api/platform/auth' });
  await app.register(platformWorkspaceRoutes, { prefix: '/api/platform/workspaces' });
  await app.register(platformUsersRoutes, { prefix: '/api/platform/users' });
  await app.register(platformSettingsRoutes, { prefix: '/api/platform/settings' });
  await app.register(platformAdminSystemRoutes, { prefix: '/api/platform/admin/system' });
  await app.register(workspaceRoutes, { prefix: '/api/workspace' });
  await app.register(uploadRoutes, { prefix: '/api/uploads' });
  await app.register(dbRoutes, { prefix: '/api/db' });
  await app.register(contactRoutes);
  await app.register(emailRoutes, { prefix: '/api/email' });
  await app.register(studentsRoutes);
  await app.register(teachersRoutes);
  await app.register(financeRoutes);
  await app.register(enrollmentsRoutes);
  await app.register(obligationsRoutes);
  await app.register(accountingRoutes);
  await app.register(hasanatRoutes);
  await app.register(examinationsRoutes);
  await app.register(questionBankRoutes);
  await app.register(usersRoutes);
  await app.register(attendanceRoutes);
  await app.register(sessionsRoutes);
  await app.register(messagingRoutes);
  await app.register(savedReportsRoutes);
  await app.register(dashboardRoutes);
  await app.register(backgroundJobRoutes, { prefix: '/api/background-jobs' });
  await app.register(aiRoutes, { prefix: '/api/ai' });
  await app.register(websocketRoutes, { prefix: '/api' });
}
