import type { FastifyInstance } from 'fastify';
import authRoutes from "./common/auth.js";
import { contactRoutes } from "./tenant/contacts.js";
import dbRoutes from "./common/db.js";
import emailRoutes from "./common/email.js";
import healthRoutes from "./common/health.js";
import platformAuthRoutes from "./platform/platformAuth.js";
import platformWorkspaceRoutes from "./platform/platformWorkspaces.js";
import platformUsersRoutes from "./platform/platformUsers.js";
import publicRoutes from "./common/public.js";
import studentsRoutes from "./tenant/students.js";
import teachersRoutes from "./tenant/teachers.js";
import financeRoutes from "./tenant/finance.js";
import enrollmentsRoutes from "./tenant/enrollments.js";
import obligationsRoutes from "./tenant/obligations.js";
import accountingRoutes from "./tenant/accounting.js";
import hasanatRoutes from "./tenant/hasanat.js";
import examinationsRoutes from "./tenant/examinations.js";
import questionBankRoutes from "./tenant/question-bank.js";
import usersRoutes from "./tenant/users.js";
import attendanceRoutes from "./tenant/attendance.js";
import sessionsRoutes from "./tenant/sessions.js";
import backgroundJobRoutes from "./common/backgroundJobs.js";
import uploadRoutes from "./common/uploads.js";
import workspaceRoutes from "./tenant/workspace.js";
import aiRoutes from "./common/ai.js";
import websocketRoutes from "./common/websocket.js";

export async function registerRoutes(app: FastifyInstance): Promise<void> {
  await app.register(healthRoutes);
  await app.register(publicRoutes, { prefix: '/api/public' });
  await app.register(authRoutes, { prefix: '/api/auth' });
  await app.register(platformAuthRoutes, { prefix: '/api/platform/auth' });
  await app.register(platformWorkspaceRoutes, { prefix: '/api/platform/workspaces' });
  await app.register(platformUsersRoutes, { prefix: '/api/platform/users' });
  await app.register(workspaceRoutes, { prefix: '/api/workspace' });
  await app.register(uploadRoutes, { prefix: '/api/uploads' });
  await app.register(dbRoutes, { prefix: '/api/db' });
  await app.register(contactRoutes, { prefix: '/api/contacts' });
  await app.register(emailRoutes, { prefix: '/api/email' });
  await app.register(studentsRoutes, { prefix: '/api/students' });
  await app.register(teachersRoutes, { prefix: '/api/teachers' });
  await app.register(financeRoutes, { prefix: '/api/finance' });
  await app.register(enrollmentsRoutes, { prefix: '/api/enrollments' });
  await app.register(obligationsRoutes, { prefix: '/api/obligations' });
  await app.register(accountingRoutes, { prefix: '/api/accounting' });
  await app.register(hasanatRoutes, { prefix: '/api/hasanat' });
  await app.register(examinationsRoutes, { prefix: '/api/examinations' });
  await app.register(questionBankRoutes, { prefix: '/api/question-bank' });
  await app.register(usersRoutes, { prefix: '/api/users' });
  await app.register(attendanceRoutes, { prefix: '/api/attendance' });
  await app.register(sessionsRoutes, { prefix: '/api/sessions' });
  await app.register(backgroundJobRoutes, { prefix: '/api/background-jobs' });
  await app.register(aiRoutes, { prefix: '/api/ai' });
  await app.register(websocketRoutes, { prefix: '/api' });
}
