import {
  ACCOUNTING_MODULE_MANIFEST,
  ATTENDANCE_MODULE_MANIFEST,
  CONTACTS_MODULE_MANIFEST,
  DASHBOARD_PREFERENCES_KEY,
  EMAIL_INTEGRATION_OBJECT_KEY,
  ENROLLMENTS_MODULE_MANIFEST,
  EXAMINATIONS_MODULE_MANIFEST,
  FINANCE_MODULE_MANIFEST,
  HASANAT_MODULE_MANIFEST,
  INVOICE_TEMPLATE_OBJECT_KEY,
  MESSAGING_MODULE_MANIFEST,
  OBLIGATIONS_MODULE_MANIFEST,
  QUESTION_BANK_MODULE_MANIFEST,
  SESSIONS_MODULE_MANIFEST,
  STUDENTS_MODULE_MANIFEST,
  TEACHERS_MODULE_MANIFEST,
  USERS_MODULE_MANIFEST,
  type Permission,
} from '@mms/shared';
export const WRITE_ROLES = new Set(['admin', 'accountant', 'teacher', 'assistant_teacher']);

export const COLLECTION_READ_PERMISSION: Record<string, Permission> = {
  contacts: CONTACTS_MODULE_MANIFEST.permissions.read,
  students: STUDENTS_MODULE_MANIFEST.permissions.read,
  teachers: TEACHERS_MODULE_MANIFEST.permissions.read,
  sessions: SESSIONS_MODULE_MANIFEST.permissions.read,
  enrollments: ENROLLMENTS_MODULE_MANIFEST.permissions.read,
  attendance_records: ATTENDANCE_MODULE_MANIFEST.permissions.read,
  finance_invoices: FINANCE_MODULE_MANIFEST.permissions.read,
  finance_payments: FINANCE_MODULE_MANIFEST.permissions.read,
  obligation_collections: OBLIGATIONS_MODULE_MANIFEST.permissions.read,
  obligation_types: OBLIGATIONS_MODULE_MANIFEST.permissions.read,
  mujtahids: OBLIGATIONS_MODULE_MANIFEST.permissions.read,
  mujtahid_reps: OBLIGATIONS_MODULE_MANIFEST.permissions.read,
  wakala_types: OBLIGATIONS_MODULE_MANIFEST.permissions.read,
  obligation_distributions: OBLIGATIONS_MODULE_MANIFEST.permissions.read,
  accounting_entries: ACCOUNTING_MODULE_MANIFEST.permissions.read,
  accounting_accounts: ACCOUNTING_MODULE_MANIFEST.permissions.read,
  accounting_fiscal_years: ACCOUNTING_MODULE_MANIFEST.permissions.read,
  hasanat_distributions: HASANAT_MODULE_MANIFEST.permissions.read,
  hasanat_batches: HASANAT_MODULE_MANIFEST.permissions.read,
  hasanat_denoms: HASANAT_MODULE_MANIFEST.permissions.read,
  hasanat_redemptions: HASANAT_MODULE_MANIFEST.permissions.read,
  exams: EXAMINATIONS_MODULE_MANIFEST.permissions.read,
  exam_results: EXAMINATIONS_MODULE_MANIFEST.permissions.read,
  questions: QUESTION_BANK_MODULE_MANIFEST.permissions.read,
  tests: QUESTION_BANK_MODULE_MANIFEST.permissions.read,
  assessment_results: QUESTION_BANK_MODULE_MANIFEST.permissions.read,
  users: USERS_MODULE_MANIFEST.permissions.read,
  user_activity_logs: 'analytics.view',
  custom_tabs: 'configuration.view',
  message_templates: MESSAGING_MODULE_MANIFEST.permissions.read,
  message_logs: MESSAGING_MODULE_MANIFEST.permissions.read,
  saved_reports: 'analytics.view',
};

export const COLLECTION_WRITE_PERMISSION: Record<string, Permission> = {
  contacts: CONTACTS_MODULE_MANIFEST.permissions.write,
  students: STUDENTS_MODULE_MANIFEST.permissions.write,
  teachers: TEACHERS_MODULE_MANIFEST.permissions.write,
  sessions: SESSIONS_MODULE_MANIFEST.permissions.write,
  enrollments: ENROLLMENTS_MODULE_MANIFEST.permissions.write,
  attendance_records: ATTENDANCE_MODULE_MANIFEST.permissions.write,
  finance_invoices: FINANCE_MODULE_MANIFEST.permissions.write,
  finance_payments: FINANCE_MODULE_MANIFEST.permissions.write,
  obligation_collections: OBLIGATIONS_MODULE_MANIFEST.permissions.write,
  obligation_types: OBLIGATIONS_MODULE_MANIFEST.permissions.write,
  mujtahids: OBLIGATIONS_MODULE_MANIFEST.permissions.write,
  mujtahid_reps: OBLIGATIONS_MODULE_MANIFEST.permissions.write,
  wakala_types: OBLIGATIONS_MODULE_MANIFEST.permissions.write,
  obligation_distributions: OBLIGATIONS_MODULE_MANIFEST.permissions.write,
  accounting_entries: ACCOUNTING_MODULE_MANIFEST.permissions.write,
  accounting_accounts: ACCOUNTING_MODULE_MANIFEST.permissions.write,
  accounting_fiscal_years: ACCOUNTING_MODULE_MANIFEST.permissions.write,
  hasanat_distributions: HASANAT_MODULE_MANIFEST.permissions.write,
  hasanat_batches: HASANAT_MODULE_MANIFEST.permissions.write,
  hasanat_denoms: HASANAT_MODULE_MANIFEST.permissions.write,
  hasanat_redemptions: HASANAT_MODULE_MANIFEST.permissions.write,
  exams: EXAMINATIONS_MODULE_MANIFEST.permissions.write,
  exam_results: EXAMINATIONS_MODULE_MANIFEST.permissions.write,
  questions: QUESTION_BANK_MODULE_MANIFEST.permissions.write,
  tests: QUESTION_BANK_MODULE_MANIFEST.permissions.write,
  assessment_results: QUESTION_BANK_MODULE_MANIFEST.permissions.write,
  users: USERS_MODULE_MANIFEST.permissions.write,
  user_activity_logs: 'analytics.view',
  custom_tabs: 'settings.global.write',
  message_templates: MESSAGING_MODULE_MANIFEST.permissions.write,
  message_logs: MESSAGING_MODULE_MANIFEST.permissions.write,
  saved_reports: 'settings.global.write',
};

/** Distinct delete permission when the module manifest defines one; else write. */
export const COLLECTION_DELETE_PERMISSION: Record<string, Permission> = {
  contacts: CONTACTS_MODULE_MANIFEST.permissions.delete,
  students: STUDENTS_MODULE_MANIFEST.permissions.delete,
  attendance_records: ATTENDANCE_MODULE_MANIFEST.permissions.delete,
};

export const OBJECT_READ_PERMISSION: Record<string, Permission> = {
  global_settings: 'configuration.view',
  branding: 'configuration.view',
  workspace: 'configuration.view',
  [EMAIL_INTEGRATION_OBJECT_KEY]: 'settings.global.write',
  [TEACHERS_MODULE_MANIFEST.settingsObjectKey]: TEACHERS_MODULE_MANIFEST.permissions.setupView,
  [TEACHERS_MODULE_MANIFEST.columnPreferencesObjectKey]: TEACHERS_MODULE_MANIFEST.permissions.read,
  [USERS_MODULE_MANIFEST.settingsObjectKey]: USERS_MODULE_MANIFEST.permissions.setupView,
  [USERS_MODULE_MANIFEST.columnPreferencesObjectKey]: USERS_MODULE_MANIFEST.permissions.read,
  [ATTENDANCE_MODULE_MANIFEST.settingsObjectKey]: ATTENDANCE_MODULE_MANIFEST.permissions.setupView,
  [ATTENDANCE_MODULE_MANIFEST.columnPreferencesObjectKey]: ATTENDANCE_MODULE_MANIFEST.permissions.read,
  [SESSIONS_MODULE_MANIFEST.settingsObjectKey]: SESSIONS_MODULE_MANIFEST.permissions.setupView,
  [SESSIONS_MODULE_MANIFEST.columnPreferencesObjectKey]: SESSIONS_MODULE_MANIFEST.permissions.read,
  [ENROLLMENTS_MODULE_MANIFEST.settingsObjectKey]: ENROLLMENTS_MODULE_MANIFEST.permissions.setupView,
  [ENROLLMENTS_MODULE_MANIFEST.columnPreferencesObjectKey]: ENROLLMENTS_MODULE_MANIFEST.permissions.read,
  [FINANCE_MODULE_MANIFEST.settingsObjectKey]: FINANCE_MODULE_MANIFEST.permissions.setupView,
  [FINANCE_MODULE_MANIFEST.invoiceColumnPreferencesObjectKey]: FINANCE_MODULE_MANIFEST.permissions.read,
  [FINANCE_MODULE_MANIFEST.paymentColumnPreferencesObjectKey]: FINANCE_MODULE_MANIFEST.permissions.read,
  [OBLIGATIONS_MODULE_MANIFEST.settingsObjectKey]: OBLIGATIONS_MODULE_MANIFEST.permissions.setupView,
  [OBLIGATIONS_MODULE_MANIFEST.columnPreferencesObjectKey]: OBLIGATIONS_MODULE_MANIFEST.permissions.read,
  [ACCOUNTING_MODULE_MANIFEST.settingsObjectKey]: ACCOUNTING_MODULE_MANIFEST.permissions.setupView,
  [ACCOUNTING_MODULE_MANIFEST.journalColumnPreferencesObjectKey]: ACCOUNTING_MODULE_MANIFEST.permissions.read,
  [ACCOUNTING_MODULE_MANIFEST.accountColumnPreferencesObjectKey]: ACCOUNTING_MODULE_MANIFEST.permissions.read,
  [HASANAT_MODULE_MANIFEST.settingsObjectKey]: HASANAT_MODULE_MANIFEST.permissions.setupView,
  [HASANAT_MODULE_MANIFEST.distributionColumnPreferencesObjectKey]: HASANAT_MODULE_MANIFEST.permissions.read,
  [HASANAT_MODULE_MANIFEST.redemptionColumnPreferencesObjectKey]: HASANAT_MODULE_MANIFEST.permissions.read,
  [EXAMINATIONS_MODULE_MANIFEST.settingsObjectKey]: EXAMINATIONS_MODULE_MANIFEST.permissions.setupView,
  [EXAMINATIONS_MODULE_MANIFEST.examColumnPreferencesObjectKey]: EXAMINATIONS_MODULE_MANIFEST.permissions.read,
  [EXAMINATIONS_MODULE_MANIFEST.resultsColumnPreferencesObjectKey]: EXAMINATIONS_MODULE_MANIFEST.permissions.read,
  [QUESTION_BANK_MODULE_MANIFEST.settingsObjectKey]: QUESTION_BANK_MODULE_MANIFEST.permissions.setupView,
  [QUESTION_BANK_MODULE_MANIFEST.columnPreferencesObjectKey]: QUESTION_BANK_MODULE_MANIFEST.permissions.read,
  [MESSAGING_MODULE_MANIFEST.recipientsColumnPreferencesObjectKey]: MESSAGING_MODULE_MANIFEST.permissions.read,
  [MESSAGING_MODULE_MANIFEST.historyColumnPreferencesObjectKey]: MESSAGING_MODULE_MANIFEST.permissions.read,
  [MESSAGING_MODULE_MANIFEST.templatesColumnPreferencesObjectKey]: MESSAGING_MODULE_MANIFEST.permissions.read,
};

export const OBJECT_WRITE_PERMISSION: Record<string, Permission> = {
  global_settings: 'settings.global.write',
  branding: 'settings.branding.write',
  workspace: 'settings.global.write',
  [EMAIL_INTEGRATION_OBJECT_KEY]: 'settings.global.write',
  [TEACHERS_MODULE_MANIFEST.settingsObjectKey]: TEACHERS_MODULE_MANIFEST.permissions.setupWrite,
  [TEACHERS_MODULE_MANIFEST.columnPreferencesObjectKey]: TEACHERS_MODULE_MANIFEST.permissions.read,
  [USERS_MODULE_MANIFEST.settingsObjectKey]: USERS_MODULE_MANIFEST.permissions.setupWrite,
  [USERS_MODULE_MANIFEST.columnPreferencesObjectKey]: USERS_MODULE_MANIFEST.permissions.read,
  [ATTENDANCE_MODULE_MANIFEST.settingsObjectKey]: ATTENDANCE_MODULE_MANIFEST.permissions.setupWrite,
  [ATTENDANCE_MODULE_MANIFEST.columnPreferencesObjectKey]: ATTENDANCE_MODULE_MANIFEST.permissions.read,
  [SESSIONS_MODULE_MANIFEST.settingsObjectKey]: SESSIONS_MODULE_MANIFEST.permissions.setupWrite,
  [SESSIONS_MODULE_MANIFEST.columnPreferencesObjectKey]: SESSIONS_MODULE_MANIFEST.permissions.read,
  [ENROLLMENTS_MODULE_MANIFEST.settingsObjectKey]: ENROLLMENTS_MODULE_MANIFEST.permissions.setupWrite,
  [ENROLLMENTS_MODULE_MANIFEST.columnPreferencesObjectKey]: ENROLLMENTS_MODULE_MANIFEST.permissions.read,
  [FINANCE_MODULE_MANIFEST.settingsObjectKey]: FINANCE_MODULE_MANIFEST.permissions.setupWrite,
  [FINANCE_MODULE_MANIFEST.invoiceColumnPreferencesObjectKey]: FINANCE_MODULE_MANIFEST.permissions.read,
  [FINANCE_MODULE_MANIFEST.paymentColumnPreferencesObjectKey]: FINANCE_MODULE_MANIFEST.permissions.read,
  [OBLIGATIONS_MODULE_MANIFEST.settingsObjectKey]: OBLIGATIONS_MODULE_MANIFEST.permissions.setupWrite,
  [OBLIGATIONS_MODULE_MANIFEST.columnPreferencesObjectKey]: OBLIGATIONS_MODULE_MANIFEST.permissions.read,
  [ACCOUNTING_MODULE_MANIFEST.settingsObjectKey]: ACCOUNTING_MODULE_MANIFEST.permissions.setupWrite,
  [ACCOUNTING_MODULE_MANIFEST.journalColumnPreferencesObjectKey]: ACCOUNTING_MODULE_MANIFEST.permissions.read,
  [ACCOUNTING_MODULE_MANIFEST.accountColumnPreferencesObjectKey]: ACCOUNTING_MODULE_MANIFEST.permissions.read,
  [HASANAT_MODULE_MANIFEST.settingsObjectKey]: HASANAT_MODULE_MANIFEST.permissions.setupWrite,
  [HASANAT_MODULE_MANIFEST.distributionColumnPreferencesObjectKey]: HASANAT_MODULE_MANIFEST.permissions.read,
  [HASANAT_MODULE_MANIFEST.redemptionColumnPreferencesObjectKey]: HASANAT_MODULE_MANIFEST.permissions.read,
  [EXAMINATIONS_MODULE_MANIFEST.settingsObjectKey]: EXAMINATIONS_MODULE_MANIFEST.permissions.setupWrite,
  [EXAMINATIONS_MODULE_MANIFEST.examColumnPreferencesObjectKey]: EXAMINATIONS_MODULE_MANIFEST.permissions.read,
  [EXAMINATIONS_MODULE_MANIFEST.resultsColumnPreferencesObjectKey]: EXAMINATIONS_MODULE_MANIFEST.permissions.read,
  [QUESTION_BANK_MODULE_MANIFEST.settingsObjectKey]: QUESTION_BANK_MODULE_MANIFEST.permissions.setupWrite,
  [QUESTION_BANK_MODULE_MANIFEST.columnPreferencesObjectKey]: QUESTION_BANK_MODULE_MANIFEST.permissions.read,
  [MESSAGING_MODULE_MANIFEST.recipientsColumnPreferencesObjectKey]: MESSAGING_MODULE_MANIFEST.permissions.read,
  [MESSAGING_MODULE_MANIFEST.historyColumnPreferencesObjectKey]: MESSAGING_MODULE_MANIFEST.permissions.read,
  [MESSAGING_MODULE_MANIFEST.templatesColumnPreferencesObjectKey]: MESSAGING_MODULE_MANIFEST.permissions.read,
};

export const ALLOWED_COLLECTIONS = new Set([
  // contacts + students entity rows are REST-only (typed tables) — not document-store
  TEACHERS_MODULE_MANIFEST.collectionKey,
  USERS_MODULE_MANIFEST.collectionKey,
  'user_activity_logs',
  ATTENDANCE_MODULE_MANIFEST.collectionKey,
  SESSIONS_MODULE_MANIFEST.collectionKey,
  ENROLLMENTS_MODULE_MANIFEST.collectionKey,
  FINANCE_MODULE_MANIFEST.collectionKey,
  FINANCE_MODULE_MANIFEST.paymentCollectionKey,
  OBLIGATIONS_MODULE_MANIFEST.collectionKey,
  'obligation_types',
  'mujtahids',
  'mujtahid_reps',
  'wakala_types',
  'obligation_distributions',
  ACCOUNTING_MODULE_MANIFEST.collectionKey,
  ACCOUNTING_MODULE_MANIFEST.accountCollectionKey,
  ACCOUNTING_MODULE_MANIFEST.fiscalYearCollectionKey,
  HASANAT_MODULE_MANIFEST.collectionKey,
  HASANAT_MODULE_MANIFEST.batchCollectionKey,
  HASANAT_MODULE_MANIFEST.denomCollectionKey,
  HASANAT_MODULE_MANIFEST.redemptionCollectionKey,
  EXAMINATIONS_MODULE_MANIFEST.collectionKey,
  EXAMINATIONS_MODULE_MANIFEST.resultsCollectionKey,
  QUESTION_BANK_MODULE_MANIFEST.collectionKey,
  QUESTION_BANK_MODULE_MANIFEST.testsCollectionKey,
  QUESTION_BANK_MODULE_MANIFEST.resultsCollectionKey,
  'currencies',
  'teacherStatuses',
  'teacherSpecializations',
  'sessionStatuses',
  'sessionTypes',
  'attendanceStatuses',
  'backups',
  'custom_tabs',
  'saved_reports',
]);

export const ALLOWED_OBJECTS = new Set([
  'global_settings',
  'branding',
  'workspace',
  EMAIL_INTEGRATION_OBJECT_KEY,
  'socialPlaceholders',
  TEACHERS_MODULE_MANIFEST.settingsObjectKey,
  TEACHERS_MODULE_MANIFEST.columnPreferencesObjectKey,
  USERS_MODULE_MANIFEST.settingsObjectKey,
  USERS_MODULE_MANIFEST.columnPreferencesObjectKey,
  ATTENDANCE_MODULE_MANIFEST.settingsObjectKey,
  ATTENDANCE_MODULE_MANIFEST.columnPreferencesObjectKey,
  SESSIONS_MODULE_MANIFEST.settingsObjectKey,
  SESSIONS_MODULE_MANIFEST.columnPreferencesObjectKey,
  ENROLLMENTS_MODULE_MANIFEST.settingsObjectKey,
  ENROLLMENTS_MODULE_MANIFEST.columnPreferencesObjectKey,
  FINANCE_MODULE_MANIFEST.settingsObjectKey,
  FINANCE_MODULE_MANIFEST.invoiceColumnPreferencesObjectKey,
  FINANCE_MODULE_MANIFEST.paymentColumnPreferencesObjectKey,
  OBLIGATIONS_MODULE_MANIFEST.settingsObjectKey,
  OBLIGATIONS_MODULE_MANIFEST.columnPreferencesObjectKey,
  ACCOUNTING_MODULE_MANIFEST.settingsObjectKey,
  ACCOUNTING_MODULE_MANIFEST.journalColumnPreferencesObjectKey,
  ACCOUNTING_MODULE_MANIFEST.accountColumnPreferencesObjectKey,
  HASANAT_MODULE_MANIFEST.settingsObjectKey,
  HASANAT_MODULE_MANIFEST.distributionColumnPreferencesObjectKey,
  HASANAT_MODULE_MANIFEST.redemptionColumnPreferencesObjectKey,
  EXAMINATIONS_MODULE_MANIFEST.settingsObjectKey,
  EXAMINATIONS_MODULE_MANIFEST.examColumnPreferencesObjectKey,
  EXAMINATIONS_MODULE_MANIFEST.resultsColumnPreferencesObjectKey,
  QUESTION_BANK_MODULE_MANIFEST.settingsObjectKey,
  QUESTION_BANK_MODULE_MANIFEST.columnPreferencesObjectKey,
  MESSAGING_MODULE_MANIFEST.recipientsColumnPreferencesObjectKey,
  MESSAGING_MODULE_MANIFEST.historyColumnPreferencesObjectKey,
  MESSAGING_MODULE_MANIFEST.templatesColumnPreferencesObjectKey,
  DASHBOARD_PREFERENCES_KEY,
  INVOICE_TEMPLATE_OBJECT_KEY,
  'kpi_custom_widgets',
  'mms_dashboard_disabled_cards',
  'dashboard_section_settings',
  'report_custom_visuals',
]);

export function isAllowedCollectionName(collectionName: string): boolean {
  return ALLOWED_COLLECTIONS.has(collectionName);
}

export function isAllowedObjectKey(key: string): boolean {
  return ALLOWED_OBJECTS.has(key)
    || key.startsWith('kpi_config_')
    || key.startsWith('prev_kpi_titles_')
    || key.startsWith('kpi_custom_cards_');
}
