import type React from "react";
import {
  LayoutDashboard,
  Users,
  GraduationCap,
  UserCheck,
  BookOpen,
  Calendar,
  ClipboardCheck,
  DollarSign,
  Award,
  FileText,
  HelpCircle,
  Calculator,
  ShieldAlert,
  MessageSquare,
  UserCog,
  Settings,
  User,
} from "lucide-react";
import { ROUTES } from "@/lib/config/routes";

export interface CommandItem {
  id: string;
  labelKey: string;
  fallbackLabel: string;
  categoryKey: string;
  fallbackCategory: string;
  path: string;
  icon: React.ElementType;
  keywords: string[];
}

export const COMMAND_ITEMS: CommandItem[] = [
  {
    id: "dashboard",
    labelKey: "nav.dashboard",
    fallbackLabel: "Dashboard",
    categoryKey: "nav.modules",
    fallbackCategory: "Navigation",
    path: ROUTES.home,
    icon: LayoutDashboard,
    keywords: ["home", "analytics", "kpi", "metrics", "dashboard"],
  },
  {
    id: "contacts",
    labelKey: "nav.contacts",
    fallbackLabel: "Contacts",
    categoryKey: "nav.modules",
    fallbackCategory: "Navigation",
    path: ROUTES.contacts,
    icon: Users,
    keywords: ["contacts", "directory", "people", "guardian", "phone"],
  },
  {
    id: "students",
    labelKey: "nav.students",
    fallbackLabel: "Students",
    categoryKey: "nav.modules",
    fallbackCategory: "Navigation",
    path: ROUTES.students,
    icon: GraduationCap,
    keywords: ["students", "pupils", "learners", "class", "grade"],
  },
  {
    id: "teachers",
    labelKey: "nav.teachers",
    fallbackLabel: "Teachers",
    categoryKey: "nav.modules",
    fallbackCategory: "Navigation",
    path: ROUTES.teachers,
    icon: UserCheck,
    keywords: ["teachers", "faculty", "instructors", "staff"],
  },
  {
    id: "enrollments",
    labelKey: "nav.enrollments",
    fallbackLabel: "Enrollments",
    categoryKey: "nav.modules",
    fallbackCategory: "Navigation",
    path: ROUTES.enrollments,
    icon: BookOpen,
    keywords: ["enrollments", "admissions", "classes", "registration"],
  },
  {
    id: "sessions",
    labelKey: "nav.sessions",
    fallbackLabel: "Sessions",
    categoryKey: "nav.modules",
    fallbackCategory: "Navigation",
    path: ROUTES.sessions,
    icon: Calendar,
    keywords: ["sessions", "timetable", "schedule", "term"],
  },
  {
    id: "attendance",
    labelKey: "nav.attendance",
    fallbackLabel: "Attendance",
    categoryKey: "nav.modules",
    fallbackCategory: "Navigation",
    path: ROUTES.attendance,
    icon: ClipboardCheck,
    keywords: ["attendance", "present", "absent", "tardy", "rollcall"],
  },
  {
    id: "finance",
    labelKey: "nav.finance",
    fallbackLabel: "Finance",
    categoryKey: "nav.modules",
    fallbackCategory: "Navigation",
    path: ROUTES.finance,
    icon: DollarSign,
    keywords: ["finance", "fees", "invoices", "payments", "dues", "billing"],
  },
  {
    id: "hasanatCards",
    labelKey: "nav.hasanatCards",
    fallbackLabel: "Hasanat Cards",
    categoryKey: "nav.modules",
    fallbackCategory: "Navigation",
    path: ROUTES.hasanatCards,
    icon: Award,
    keywords: ["hasanat", "cards", "rewards", "merit", "points"],
  },
  {
    id: "examinations",
    labelKey: "nav.examinations",
    fallbackLabel: "Examinations",
    categoryKey: "nav.modules",
    fallbackCategory: "Navigation",
    path: ROUTES.examinations,
    icon: FileText,
    keywords: ["examinations", "exams", "grades", "marks", "tests", "results"],
  },
  {
    id: "questionBank",
    labelKey: "nav.questionBank",
    fallbackLabel: "Question Bank",
    categoryKey: "nav.modules",
    fallbackCategory: "Navigation",
    path: ROUTES.questionBank,
    icon: HelpCircle,
    keywords: ["question bank", "questions", "quiz", "assessment"],
  },
  {
    id: "accounting",
    labelKey: "nav.accounting",
    fallbackLabel: "Accounting",
    categoryKey: "nav.modules",
    fallbackCategory: "Navigation",
    path: ROUTES.accounting,
    icon: Calculator,
    keywords: ["accounting", "ledger", "journal", "expenses", "revenue"],
  },
  {
    id: "obligations",
    labelKey: "nav.obligations",
    fallbackLabel: "Obligations",
    categoryKey: "nav.modules",
    fallbackCategory: "Navigation",
    path: ROUTES.obligations,
    icon: ShieldAlert,
    keywords: ["obligations", "compliance", "dues", "liabilities"],
  },
  {
    id: "messaging",
    labelKey: "nav.messaging",
    fallbackLabel: "Messaging",
    categoryKey: "nav.modules",
    fallbackCategory: "Navigation",
    path: ROUTES.messaging,
    icon: MessageSquare,
    keywords: ["messaging", "sms", "whatsapp", "notifications", "broadcast"],
  },
  {
    id: "users",
    labelKey: "nav.users",
    fallbackLabel: "Users",
    categoryKey: "nav.system",
    fallbackCategory: "System",
    path: ROUTES.users,
    icon: UserCog,
    keywords: ["users", "admins", "staff", "permissions", "roles"],
  },
  {
    id: "settings",
    labelKey: "nav.settings",
    fallbackLabel: "Settings",
    categoryKey: "nav.system",
    fallbackCategory: "System",
    path: ROUTES.settings,
    icon: Settings,
    keywords: ["settings", "branding", "theme", "backup", "configuration"],
  },
  {
    id: "profile",
    labelKey: "account.title",
    fallbackLabel: "Account Profile",
    categoryKey: "nav.system",
    fallbackCategory: "System",
    path: ROUTES.profile,
    icon: User,
    keywords: ["profile", "account", "password", "security", "me"],
  },
];
