import {
  LayoutDashboard,
  Users,
  GraduationCap,
  UserCheck,
  BookOpen,
  Calendar,
  ClipboardCheck,
  DollarSign,
  Award,
  FileText,
  HelpCircle,
  Calculator,
  ShieldAlert,
  MessageSquare,
} from "lucide-react";
import { ROUTES } from "@/lib/config/routes";
import { SYSTEM_COMMAND_ITEMS, type CommandItem } from "@/components/ui/systemCommandItems";

export type { CommandItem };

export const COMMAND_ITEMS: CommandItem[] = [
  {
    id: "dashboard",
    labelKey: "nav.dashboard",
    fallbackLabel: "Dashboard",
    categoryKey: "nav.modules",
    fallbackCategory: "Navigation",
    path: ROUTES.home,
    icon: LayoutDashboard,
    keywords: ["home", "analytics", "kpi", "metrics", "dashboard"],
  },
  {
    id: "contacts",
    labelKey: "nav.contacts",
    fallbackLabel: "Contacts",
    categoryKey: "nav.modules",
    fallbackCategory: "Navigation",
    path: ROUTES.contacts,
    icon: Users,
    keywords: ["contacts", "directory", "people", "guardian", "phone"],
  },
  {
    id: "students",
    labelKey: "nav.students",
    fallbackLabel: "Students",
    categoryKey: "nav.modules",
    fallbackCategory: "Navigation",
    path: ROUTES.students,
    icon: GraduationCap,
    keywords: ["students", "pupils", "learners", "class", "grade"],
  },
  {
    id: "faculty",
    labelKey: "nav.faculty",
    fallbackLabel: "Faculty",
    categoryKey: "nav.modules",
    fallbackCategory: "Navigation",
    path: ROUTES.faculty,
    icon: UserCheck,
    keywords: ["faculty", "teachers", "instructors", "staff"],
  },
  {
    id: "enrollments",
    labelKey: "nav.enrollments",
    fallbackLabel: "Enrollments",
    categoryKey: "nav.modules",
    fallbackCategory: "Navigation",
    path: ROUTES.enrollments,
    icon: BookOpen,
    keywords: ["enrollments", "admissions", "classes", "registration"],
  },
  {
    id: "sessions",
    labelKey: "nav.sessions",
    fallbackLabel: "Sessions",
    categoryKey: "nav.modules",
    fallbackCategory: "Navigation",
    path: ROUTES.sessions,
    icon: Calendar,
    keywords: ["sessions", "timetable", "schedule", "term"],
  },
  {
    id: "attendance",
    labelKey: "nav.attendance",
    fallbackLabel: "Attendance",
    categoryKey: "nav.modules",
    fallbackCategory: "Navigation",
    path: ROUTES.attendance,
    icon: ClipboardCheck,
    keywords: ["attendance", "present", "absent", "tardy", "rollcall"],
  },
  {
    id: "finance",
    labelKey: "nav.finance",
    fallbackLabel: "Finance",
    categoryKey: "nav.modules",
    fallbackCategory: "Navigation",
    path: ROUTES.finance,
    icon: DollarSign,
    keywords: ["finance", "fees", "invoices", "payments", "dues", "billing"],
  },
  {
    id: "hasanatCards",
    labelKey: "nav.hasanatCards",
    fallbackLabel: "Hasanat Cards",
    categoryKey: "nav.modules",
    fallbackCategory: "Navigation",
    path: ROUTES.hasanatCards,
    icon: Award,
    keywords: ["hasanat", "cards", "rewards", "merit", "points"],
  },
  {
    id: "examinations",
    labelKey: "nav.examinations",
    fallbackLabel: "Examinations",
    categoryKey: "nav.modules",
    fallbackCategory: "Navigation",
    path: ROUTES.examinations,
    icon: FileText,
    keywords: ["examinations", "exams", "grades", "marks", "tests", "results"],
  },
  {
    id: "questionBank",
    labelKey: "nav.questionBank",
    fallbackLabel: "Question Bank",
    categoryKey: "nav.modules",
    fallbackCategory: "Navigation",
    path: ROUTES.questionBank,
    icon: HelpCircle,
    keywords: ["question bank", "questions", "quiz", "assessment"],
  },
  {
    id: "accounting",
    labelKey: "nav.accounting",
    fallbackLabel: "Accounting",
    categoryKey: "nav.modules",
    fallbackCategory: "Navigation",
    path: ROUTES.accounting,
    icon: Calculator,
    keywords: ["accounting", "ledger", "journal", "expenses", "revenue"],
  },
  {
    id: "obligations",
    labelKey: "nav.obligations",
    fallbackLabel: "Obligations",
    categoryKey: "nav.modules",
    fallbackCategory: "Navigation",
    path: ROUTES.obligations,
    icon: ShieldAlert,
    keywords: ["obligations", "compliance", "dues", "liabilities"],
  },
  {
    id: "messaging",
    labelKey: "nav.messaging",
    fallbackLabel: "Messaging",
    categoryKey: "nav.modules",
    fallbackCategory: "Navigation",
    path: ROUTES.messaging,
    icon: MessageSquare,
    keywords: ["messaging", "sms", "whatsapp", "notifications", "broadcast"],
  },
  ...SYSTEM_COMMAND_ITEMS,
];

