import type { CustomWidget } from "./pinnedWidgetTypes";
import { financialCardWidgetSeeds } from "./widgetSeedsFinancialCards";

export const financialWidgetSeeds: CustomWidget[] = [
  ...financialCardWidgetSeeds,
  {
    id: "def-finance-outstanding",
    title: "",
    titleKey: "widget.title.overduePayments",
    category: "financial",
    collection: "finance_invoices",
    widgetType: "kpi",
    operation: "sum",
    targetField: "finalAmt",
    filterField: "status",
    filterOperator: "equals",
    filterValue: "unpaid",
    color: "red",
    isPinnedToDashboard: false,
    thresholdEnabled: true,
    thresholdCondition: "gt",
    thresholdValue: 10000,
    thresholdColor: "red",
  },
  {
    id: "def-finance-paid-rate",
    title: "",
    titleKey: "widget.title.paidInvoicesRatio",
    category: "financial",
    collection: "finance_invoices",
    widgetType: "progress",
    operation: "percentage",
    filterField: "status",
    filterOperator: "equals",
    filterValue: "paid",
    color: "emerald",
    isPinnedToDashboard: true,
    thresholdEnabled: true,
    thresholdCondition: "lt",
    thresholdValue: 70,
    thresholdColor: "yellow",
  },
  {
    id: "def-finance-toggle-rev",
    title: "",
    titleKey: "widget.title.showRevenueGraph",
    category: "financial",
    collection: "finance_invoices",
    widgetType: "switch",
    operation: "count",
    switchActionType: "app_setting",
    switchStateKey: "section_revenueChart",
    switchLabelOnKey: "reports.widgets.switchVisible",
    switchLabelOffKey: "reports.widgets.switchHidden",
    color: "blue",
    isPinnedToDashboard: true,
  },
  {
    id: "def-fee-summary",
    title: "",
    titleKey: "widget.title.feeCollectionSummary",
    category: "financial",
    collection: "finance_invoices",
    widgetType: "fee-summary",
    operation: "sum",
    targetField: "paidAmt",
    color: "emerald",
    isPinnedToDashboard: true,
  },
  {
    id: "def-outstanding-list",
    title: "",
    titleKey: "widget.title.outstandingInvoicesList",
    category: "financial",
    collection: "finance_invoices",
    widgetType: "outstanding-list",
    operation: "sum",
    targetField: "finalAmt",
    color: "red",
    isPinnedToDashboard: true,
  },
  {
    id: "def-overdue-obligations",
    title: "",
    titleKey: "widget.title.overdueObligations",
    category: "financial",
    collection: "finance_invoices",
    widgetType: "overdue-obligations",
    operation: "sum",
    targetField: "finalAmt",
    color: "red",
    isPinnedToDashboard: true,
  },
  {
    id: "def-revenue-expenses",
    title: "",
    titleKey: "widget.title.revenueExpenses",
    category: "financial",
    collection: "finance_invoices",
    widgetType: "revenue-expenses",
    operation: "sum",
    color: "emerald",
    isPinnedToDashboard: true,
  },
];
