import type { CustomWidget } from "./pinnedWidgetTypes";

export const financialWidgetSeeds: CustomWidget[] = [
      {
        id: "def-card-admin-fees",
        title: "Fee Collection",
        category: "financial",
        collection: "finance_invoices",
        widgetType: "card",
        operation: "sum",
        targetField: "paidAmt",
        filterField: "status",
        filterOperator: "equals",
        filterValue: "paid",
        icon: "DollarSign",
        color: "emerald",
        subTextType: "fixed",
        trend: 11,
        trendType: "manual",
        role: "admin",
        isPinnedToDashboard: false
      },
      {
        id: "def-card-admin-outstanding",
        title: "Outstanding Payments",
        category: "financial",
        collection: "finance_invoices",
        widgetType: "card",
        operation: "sum",
        targetField: "finalAmt",
        filterField: "status",
        filterOperator: "equals",
        filterValue: "unpaid",
        icon: "AlertCircle",
        color: "red",
        subTextType: "fixed",
        trend: -8,
        trendType: "manual",
        role: "admin",
        isPinnedToDashboard: false
      },
      {
        id: "def-card-accountant-fees",
        title: "Fee Collection",
        category: "financial",
        collection: "finance_invoices",
        widgetType: "card",
        operation: "sum",
        targetField: "paidAmt",
        filterField: "status",
        filterOperator: "equals",
        filterValue: "paid",
        icon: "DollarSign",
        color: "emerald",
        subTextType: "fixed",
        trend: 11,
        trendType: "manual",
        role: "accountant",
        isPinnedToDashboard: false
      },
      {
        id: "def-card-accountant-outstanding",
        title: "Outstanding Payments",
        category: "financial",
        collection: "finance_invoices",
        widgetType: "card",
        operation: "sum",
        targetField: "finalAmt",
        filterField: "status",
        filterOperator: "equals",
        filterValue: "unpaid",
        icon: "AlertCircle",
        color: "red",
        subTextType: "fixed",
        trend: -8,
        trendType: "manual",
        role: "accountant",
        isPinnedToDashboard: false
      },
      {
        id: "def-card-accountant-revenue",
        title: "Total Revenue (YTD)",
        category: "financial",
        collection: "finance_invoices",
        widgetType: "card",
        operation: "sum",
        targetField: "finalAmt",
        filterField: "status",
        filterOperator: "equals",
        filterValue: "paid",
        icon: "TrendingUp",
        color: "blue",
        subTextType: "fixed",
        trend: 11.4,
        trendType: "manual",
        role: "accountant",
        isPinnedToDashboard: false
      },
      {
        id: "def-card-accountant-expenses",
        title: "Total Expenses (YTD)",
        category: "financial",
        collection: "finance_invoices",
        widgetType: "card",
        operation: "sum",
        targetField: "discountAmt",
        icon: "Receipt",
        color: "violet",
        subTextType: "fixed",
        trend: -2,
        trendType: "manual",
        role: "accountant",
        isPinnedToDashboard: false
      },
      {
        id: "def-finance-outstanding",
        title: "Overdue Payments",
        category: "financial",
        collection: "finance_invoices",
        widgetType: "kpi",
        operation: "sum",
        targetField: "finalAmt",
        filterField: "status",
        filterOperator: "equals",
        filterValue: "unpaid",
        color: "red",
        isPinnedToDashboard: true,
        thresholdEnabled: true,
        thresholdCondition: "gt",
        thresholdValue: 10000,
        thresholdColor: "red"
      },
      {
        id: "def-finance-paid-rate",
        title: "Paid Invoices Ratio",
        category: "financial",
        collection: "finance_invoices",
        widgetType: "progress",
        operation: "percentage",
        filterField: "status",
        filterOperator: "equals",
        filterValue: "paid",
        color: "emerald",
        isPinnedToDashboard: true,
        thresholdEnabled: true,
        thresholdCondition: "lt",
        thresholdValue: 70,
        thresholdColor: "yellow"
      },
      {
        id: "def-finance-toggle-rev",
        title: "Show Revenue Graph",
        category: "financial",
        collection: "finance_invoices",
        widgetType: "switch",
        operation: "count",
        switchActionType: "app_setting",
        switchStateKey: "section_revenueChart",
        switchLabelOnKey: "reports.widgets.switchVisible",
        switchLabelOffKey: "reports.widgets.switchHidden",
        color: "blue",
        isPinnedToDashboard: true
      },
      {
        id: "def-fee-summary",
        title: "Fee Collection Summary",
        category: "financial",
        collection: "finance_invoices",
        widgetType: "fee-summary",
        operation: "sum",
        targetField: "paidAmt",
        color: "emerald",
        isPinnedToDashboard: true
      },
      {
        id: "def-outstanding-list",
        title: "Outstanding Invoices List",
        category: "financial",
        collection: "finance_invoices",
        widgetType: "outstanding-list",
        operation: "sum",
        targetField: "finalAmt",
        color: "red",
        isPinnedToDashboard: true
      },
      {
        id: "def-overdue-obligations",
        title: "Overdue Obligations Table",
        category: "financial",
        collection: "finance_invoices",
        widgetType: "overdue-obligations",
        operation: "sum",
        targetField: "finalAmt",
        color: "red",
        isPinnedToDashboard: true
      },
      {
        id: "def-revenue-expenses",
        title: "Revenue & Expenses",
        category: "financial",
        collection: "finance_invoices",
        widgetType: "revenue-expenses",
        operation: "sum",
        color: "emerald",
        isPinnedToDashboard: true
      }
    ];
