import type { CustomWidget } from "./pinnedWidgetTypes";

export const studentsWidgetSeeds: CustomWidget[] = [
  {
    id: "def-card-admin-students",
    title: "",
    titleKey: "widget.title.totalStudents",
    category: "students",
    collection: "students",
    widgetType: "card",
    operation: "count",
    icon: "GraduationCap",
    color: "emerald",
    subTextType: "fixed",
    fixedSubText: "",
    fixedSubTextKey: "widget.subtitle.registeredStudents",
    trend: 0,
    trendType: "database",
    role: "admin",
    isPinnedToDashboard: false,
  },
  {
    id: "def-card-admin-attendance",
    title: "",
    titleKey: "widget.title.attendanceToday",
    category: "students",
    collection: "attendance_records",
    widgetType: "card",
    operation: "percentage",
    filterField: "status",
    filterOperator: "equals",
    filterValue: "present",
    icon: "UserCheck",
    color: "amber",
    subTextType: "fixed",
    fixedSubText: "",
    fixedSubTextKey: "widget.subtitle.attendanceRateToday",
    trend: 0,
    trendType: "database",
    role: "admin",
    isPinnedToDashboard: false,
  },
  {
    id: "def-card-teacher-attendance",
    title: "",
    titleKey: "widget.title.attendanceToday",
    category: "students",
    collection: "attendance_records",
    widgetType: "card",
    operation: "percentage",
    filterField: "status",
    filterOperator: "equals",
    filterValue: "present",
    icon: "UserCheck",
    color: "emerald",
    subTextType: "fixed",
    fixedSubText: "",
    fixedSubTextKey: "widget.subtitle.averagePresentRate",
    trend: 0,
    trendType: "database",
    role: "teacher",
    isPinnedToDashboard: false,
  },
  {
    id: "def-students-kpi",
    title: "",
    titleKey: "widget.title.activeStudents",
    category: "students",
    collection: "students",
    widgetType: "kpi",
    operation: "count",
    filterField: "status",
    filterOperator: "equals",
    filterValue: "active",
    color: "emerald",
    isPinnedToDashboard: false,
    thresholdEnabled: true,

    thresholdCondition: "lt",
    thresholdValue: 10,
    thresholdColor: "amber",
  },
  {
    id: "def-students-lock",
    title: "",
    titleKey: "widget.title.attendanceLocking",
    category: "students",
    collection: "students",
    widgetType: "switch",
    operation: "count",
    switchActionType: "app_setting",
    switchStateKey: "app_setting_attendance_lock",
    switchLabelOnKey: "reports.widgets.switchLocked",
    switchLabelOffKey: "reports.widgets.switchUnlocked",
    color: "red",
    isPinnedToDashboard: true,
  },
  {
    id: "def-attendance-summary",
    title: "",
    titleKey: "widget.title.todaysAttendanceSummary",
    category: "students",
    collection: "attendance_records",
    widgetType: "attendance-summary",
    operation: "percentage",
    filterField: "status",
    filterOperator: "equals",
    filterValue: "present",
    color: "amber",
    isPinnedToDashboard: true,
  },
  {
    id: "def-enrollment-trends",
    title: "",
    titleKey: "widget.title.enrollmentTrends",
    category: "students",
    collection: "students",
    widgetType: "enrollment-trends",
    operation: "count",
    color: "emerald",
    isPinnedToDashboard: true,
  },
  {
    id: "def-attendance-rate",
    title: "",
    titleKey: "widget.title.attendanceRate",
    category: "students",
    collection: "attendance_records",
    widgetType: "attendance-rate",
    operation: "percentage",
    color: "blue",
    isPinnedToDashboard: true,
  },
];
