import type { CustomWidget } from "./pinnedWidgetTypes";

export const hasanatWidgetSeeds: CustomWidget[] = [
  {
    id: "def-card-admin-hasanat",
    title: "",
    titleKey: "widget.title.hasanatAwarded",
    category: "hasanat",
    collection: "hasanat_distributions",
    widgetType: "card",
    operation: "sum",
    targetField: "points",
    icon: "Star",
    color: "amber",
    subTextType: "fixed",
    fixedSubText: "",
    fixedSubTextKey: "widget.subtitle.allTimePoints",
    trend: 0,
    trendType: "database",
    role: "admin",
    isPinnedToDashboard: false,
  },
  {
    id: "def-card-teacher-hasanat",
    title: "",
    titleKey: "widget.title.hasanatAwarded",
    category: "hasanat",
    collection: "hasanat_distributions",
    widgetType: "card",
    operation: "sum",
    targetField: "points",
    icon: "Star",
    color: "amber",
    subTextType: "fixed",
    fixedSubText: "",
    fixedSubTextKey: "widget.subtitle.awardedByMe",
    trend: 0,
    trendType: "database",
    role: "teacher",
    isPinnedToDashboard: false,
  },
  {
    id: "def-hasanat-points",
    title: "",
    titleKey: "widget.title.totalPointsIssued",
    category: "hasanat",
    collection: "hasanat_distributions",
    widgetType: "kpi",
    operation: "sum",
    targetField: "points",
    color: "amber",
    isPinnedToDashboard: true,
  },
  {
    id: "def-hasanat-distribution",
    title: "",
    titleKey: "widget.title.hasanatDistribution",
    category: "hasanat",
    collection: "hasanat_distributions",
    widgetType: "hasanat-distribution",
    operation: "sum",
    color: "amber",
    isPinnedToDashboard: true,
  },
];
