import type { CustomWidget } from "./pinnedWidgetTypes";

export const financialWidgetSeeds: CustomWidget[] = [
  {
    id: "def-card-admin-fees",
    title: "",
    titleKey: "widget.title.feeCollection",
    category: "financial",
    collection: "finance_invoices",
    widgetType: "card",
    operation: "sum",
    targetField: "paidAmt",
    filterField: "status",
    filterOperator: "equals",
    filterValue: "paid",
    icon: "DollarSign",
    color: "emerald",
    subTextType: "fixed",
    fixedSubText: "",
    fixedSubTextKey: "widget.subtitle.thisMonth",
    trend: 0,
    trendType: "database",
    role: "admin",
    isPinnedToDashboard: false,
  },
  {
    id: "def-card-admin-outstanding",
    title: "",
    titleKey: "widget.title.outstandingPayments",
    category: "financial",
    collection: "finance_invoices",
    widgetType: "card",
    operation: "sum",
    targetField: "finalAmt",
    filterField: "status",
    filterOperator: "equals",
    filterValue: "unpaid",
    icon: "AlertCircle",
    color: "red",
    subTextType: "fixed",
    fixedSubText: "",
    fixedSubTextKey: "widget.subtitle.unpaidInvoices",
    trend: 0,
    trendType: "database",
    role: "admin",
    isPinnedToDashboard: false,
  },
  {
    id: "def-card-accountant-fees",
    title: "",
    titleKey: "widget.title.feeCollection",
    category: "financial",
    collection: "finance_invoices",
    widgetType: "card",
    operation: "sum",
    targetField: "paidAmt",
    filterField: "status",
    filterOperator: "equals",
    filterValue: "paid",
    icon: "DollarSign",
    color: "emerald",
    subTextType: "fixed",
    fixedSubText: "",
    fixedSubTextKey: "widget.subtitle.thisMonth",
    trend: 0,
    trendType: "database",
    role: "accountant",
    isPinnedToDashboard: false,
  },
  {
    id: "def-card-accountant-outstanding",
    title: "",
    titleKey: "widget.title.outstandingPayments",
    category: "financial",
    collection: "finance_invoices",
    widgetType: "card",
    operation: "sum",
    targetField: "finalAmt",
    filterField: "status",
    filterOperator: "equals",
    filterValue: "unpaid",
    icon: "AlertCircle",
    color: "red",
    subTextType: "fixed",
    fixedSubText: "",
    fixedSubTextKey: "widget.subtitle.unpaidInvoices",
    trend: 0,
    trendType: "database",
    role: "accountant",
    isPinnedToDashboard: false,
  },
  {
    id: "def-card-accountant-revenue",
    title: "",
    titleKey: "widget.title.totalRevenueYtd",
    category: "financial",
    collection: "finance_invoices",
    widgetType: "card",
    operation: "sum",
    targetField: "finalAmt",
    filterField: "status",
    filterOperator: "equals",
    filterValue: "paid",
    icon: "TrendingUp",
    color: "blue",
    subTextType: "fixed",
    fixedSubText: "",
    fixedSubTextKey: "widget.subtitle.fromInvoices",
    trend: 0,
    trendType: "database",
    role: "accountant",
    isPinnedToDashboard: false,
  },
  {
    id: "def-card-accountant-expenses",
    title: "",
    titleKey: "widget.title.totalExpensesYtd",
    category: "financial",
    collection: "finance_invoices",
    widgetType: "card",
    operation: "sum",
    targetField: "discountAmt",
    icon: "Receipt",
    color: "violet",
    subTextType: "fixed",
    fixedSubText: "",
    fixedSubTextKey: "widget.subtitle.totalDiscountOffset",
    trend: 0,
    trendType: "database",
    role: "accountant",
    isPinnedToDashboard: false,
  },
  {
    id: "def-finance-outstanding",
    title: "",
    titleKey: "widget.title.overduePayments",
    category: "financial",
    collection: "finance_invoices",
    widgetType: "kpi",
    operation: "sum",
    targetField: "finalAmt",
    filterField: "status",
    filterOperator: "equals",
    filterValue: "unpaid",
    color: "red",
    isPinnedToDashboard: false,
    thresholdEnabled: true,

    thresholdCondition: "gt",
    thresholdValue: 10000,
    thresholdColor: "red",
  },
  {
    id: "def-finance-paid-rate",
    title: "",
    titleKey: "widget.title.paidInvoicesRatio",
    category: "financial",
    collection: "finance_invoices",
    widgetType: "progress",
    operation: "percentage",
    filterField: "status",
    filterOperator: "equals",
    filterValue: "paid",
    color: "emerald",
    isPinnedToDashboard: true,
    thresholdEnabled: true,
    thresholdCondition: "lt",
    thresholdValue: 70,
    thresholdColor: "yellow",
  },
  {
    id: "def-finance-toggle-rev",
    title: "",
    titleKey: "widget.title.showRevenueGraph",
    category: "financial",
    collection: "finance_invoices",
    widgetType: "switch",
    operation: "count",
    switchActionType: "app_setting",
    switchStateKey: "section_revenueChart",
    switchLabelOnKey: "reports.widgets.switchVisible",
    switchLabelOffKey: "reports.widgets.switchHidden",
    color: "blue",
    isPinnedToDashboard: true,
  },
  {
    id: "def-fee-summary",
    title: "",
    titleKey: "widget.title.feeCollectionSummary",
    category: "financial",
    collection: "finance_invoices",
    widgetType: "fee-summary",
    operation: "sum",
    targetField: "paidAmt",
    color: "emerald",
    isPinnedToDashboard: true,
  },
  {
    id: "def-outstanding-list",
    title: "",
    titleKey: "widget.title.outstandingInvoicesList",
    category: "financial",
    collection: "finance_invoices",
    widgetType: "outstanding-list",
    operation: "sum",
    targetField: "finalAmt",
    color: "red",
    isPinnedToDashboard: true,
  },
  {
    id: "def-overdue-obligations",
    title: "",
    titleKey: "widget.title.overdueObligations",
    category: "financial",
    collection: "finance_invoices",
    widgetType: "overdue-obligations",
    operation: "sum",
    targetField: "finalAmt",
    color: "red",
    isPinnedToDashboard: true,
  },
  {
    id: "def-revenue-expenses",
    title: "",
    titleKey: "widget.title.revenueExpenses",
    category: "financial",
    collection: "finance_invoices",
    widgetType: "revenue-expenses",
    operation: "sum",
    color: "emerald",
    isPinnedToDashboard: true,
  },
];
