import type { CustomWidget } from "./pinnedWidgetTypes";

export const financialCardWidgetSeeds: CustomWidget[] = [
  {
    id: "def-card-admin-fees",
    title: "",
    titleKey: "widget.title.feeCollection",
    category: "financial",
    collection: "finance_invoices",
    widgetType: "card",
    operation: "sum",
    targetField: "paidAmt",
    filterField: "status",
    filterOperator: "equals",
    filterValue: "paid",
    icon: "DollarSign",
    color: "emerald",
    subTextType: "fixed",
    fixedSubText: "",
    fixedSubTextKey: "widget.subtitle.thisMonth",
    trend: 0,
    trendType: "database",
    role: "admin",
    isPinnedToDashboard: false,
  },
  {
    id: "def-card-admin-outstanding",
    title: "",
    titleKey: "widget.title.outstandingPayments",
    category: "financial",
    collection: "finance_invoices",
    widgetType: "card",
    operation: "sum",
    targetField: "finalAmt",
    filterField: "status",
    filterOperator: "equals",
    filterValue: "unpaid",
    icon: "AlertCircle",
    color: "red",
    subTextType: "fixed",
    fixedSubText: "",
    fixedSubTextKey: "widget.subtitle.unpaidInvoices",
    trend: 0,
    trendType: "database",
    role: "admin",
    isPinnedToDashboard: false,
  },
  {
    id: "def-card-accountant-fees",
    title: "",
    titleKey: "widget.title.feeCollection",
    category: "financial",
    collection: "finance_invoices",
    widgetType: "card",
    operation: "sum",
    targetField: "paidAmt",
    filterField: "status",
    filterOperator: "equals",
    filterValue: "paid",
    icon: "DollarSign",
    color: "emerald",
    subTextType: "fixed",
    fixedSubText: "",
    fixedSubTextKey: "widget.subtitle.thisMonth",
    trend: 0,
    trendType: "database",
    role: "accountant",
    isPinnedToDashboard: false,
  },
  {
    id: "def-card-accountant-outstanding",
    title: "",
    titleKey: "widget.title.outstandingPayments",
    category: "financial",
    collection: "finance_invoices",
    widgetType: "card",
    operation: "sum",
    targetField: "finalAmt",
    filterField: "status",
    filterOperator: "equals",
    filterValue: "unpaid",
    icon: "AlertCircle",
    color: "red",
    subTextType: "fixed",
    fixedSubText: "",
    fixedSubTextKey: "widget.subtitle.unpaidInvoices",
    trend: 0,
    trendType: "database",
    role: "accountant",
    isPinnedToDashboard: false,
  },
  {
    id: "def-card-accountant-revenue",
    title: "",
    titleKey: "widget.title.totalRevenueYtd",
    category: "financial",
    collection: "finance_invoices",
    widgetType: "card",
    operation: "sum",
    targetField: "finalAmt",
    filterField: "status",
    filterOperator: "equals",
    filterValue: "paid",
    icon: "TrendingUp",
    color: "blue",
    subTextType: "fixed",
    fixedSubText: "",
    fixedSubTextKey: "widget.subtitle.fromInvoices",
    trend: 0,
    trendType: "database",
    role: "accountant",
    isPinnedToDashboard: false,
  },
  {
    id: "def-card-accountant-expenses",
    title: "",
    titleKey: "widget.title.totalExpensesYtd",
    category: "financial",
    collection: "finance_invoices",
    widgetType: "card",
    operation: "sum",
    targetField: "discountAmt",
    icon: "Receipt",
    color: "violet",
    subTextType: "fixed",
    fixedSubText: "",
    fixedSubTextKey: "widget.subtitle.totalDiscountOffset",
    trend: 0,
    trendType: "database",
    role: "accountant",
    isPinnedToDashboard: false,
  },
];
