import type { CustomWidget } from "./pinnedWidgetTypes";

export const studentsWidgetSeeds: CustomWidget[] = [
      {
        id: "def-card-admin-students",
        title: "Total Students",
        category: "students",
        collection: "students",
        widgetType: "card",
        operation: "count",
        icon: "GraduationCap",
        color: "emerald",
        subTextType: "fixed",
        trend: 14,
        trendType: "manual",
        role: "admin",
        isPinnedToDashboard: false
      },
      {
        id: "def-card-admin-attendance",
        title: "Attendance Today",
        category: "students",
        collection: "attendance_records",
        widgetType: "card",
        operation: "percentage",
        filterField: "status",
        filterOperator: "equals",
        filterValue: "present",
        icon: "UserCheck",
        color: "amber",
        subTextType: "fixed",
        trend: -3,
        trendType: "manual",
        role: "admin",
        isPinnedToDashboard: false
      },
      {
        id: "def-card-teacher-attendance",
        title: "Attendance Today",
        category: "students",
        collection: "attendance_records",
        widgetType: "card",
        operation: "percentage",
        filterField: "status",
        filterOperator: "equals",
        filterValue: "present",
        icon: "UserCheck",
        color: "emerald",
        subTextType: "fixed",
        trend: 5,
        trendType: "manual",
        role: "teacher",
        isPinnedToDashboard: false
      },
      {
        id: "def-students-kpi",
        title: "Active Students",
        category: "students",
        collection: "students",
        widgetType: "kpi",
        operation: "count",
        filterField: "status",
        filterOperator: "equals",
        filterValue: "active",
        color: "emerald",
        isPinnedToDashboard: true,
        thresholdEnabled: true,
        thresholdCondition: "lt",
        thresholdValue: 10,
        thresholdColor: "amber"
      },
      {
        id: "def-students-lock",
        title: "Attendance Locking",
        category: "students",
        collection: "students",
        widgetType: "switch",
        operation: "count",
        switchActionType: "app_setting",
        switchStateKey: "app_setting_attendance_lock",
        switchLabelOnKey: "reports.widgets.switchLocked",
        switchLabelOffKey: "reports.widgets.switchUnlocked",
        color: "red",
        isPinnedToDashboard: true
      },
      {
        id: "def-attendance-summary",
        title: "Today's Attendance Summary",
        category: "students",
        collection: "attendance_records",
        widgetType: "attendance-summary",
        operation: "percentage",
        filterField: "status",
        filterOperator: "equals",
        filterValue: "present",
        color: "amber",
        isPinnedToDashboard: true
      },
      {
        id: "def-enrollment-trends",
        title: "Enrollment Trends",
        category: "students",
        collection: "students",
        widgetType: "enrollment-trends",
        operation: "count",
        color: "emerald",
        isPinnedToDashboard: true
      },
      {
        id: "def-attendance-rate",
        title: "Attendance Rate",
        category: "students",
        collection: "attendance_records",
        widgetType: "attendance-rate",
        operation: "percentage",
        color: "blue",
        isPinnedToDashboard: true
      }
    ];
