import type { CustomWidget } from "./pinnedWidgetTypes";

export const sessionsWidgetSeeds: CustomWidget[] = [
      {
        id: "def-card-admin-sessions",
        title: "Active Sessions",
        category: "sessions",
        collection: "sessions",
        widgetType: "card",
        operation: "count",
        filterField: "status",
        filterOperator: "equals",
        filterValue: "active",
        icon: "CalendarCheck",
        color: "blue",
        subTextType: "fixed",
        trend: 0,
        trendType: "manual",
        role: "admin",
        isPinnedToDashboard: false
      },
      {
        id: "def-card-admin-classes",
        title: "Active Classes",
        category: "sessions",
        collection: "sessions",
        widgetType: "card",
        operation: "count",
        icon: "BookOpen",
        color: "violet",
        subTextType: "fixed",
        trend: 4,
        trendType: "manual",
        role: "admin",
        isPinnedToDashboard: false
      },
      {
        id: "def-card-teacher-classes",
        title: "My Classes",
        category: "sessions",
        collection: "sessions",
        widgetType: "card",
        operation: "count",
        icon: "BookOpen",
        color: "violet",
        subTextType: "fixed",
        trend: 0,
        trendType: "manual",
        role: "teacher",
        isPinnedToDashboard: false
      },
      {
        id: "def-card-teacher-sessions",
        title: "Sessions Today",
        category: "sessions",
        collection: "sessions",
        widgetType: "card",
        operation: "count",
        icon: "CalendarCheck",
        color: "blue",
        subTextType: "fixed",
        trend: 0,
        trendType: "manual",
        role: "teacher",
        isPinnedToDashboard: false
      },
      {
        id: "def-sessions-count",
        title: "Active Sessions",
        category: "sessions",
        collection: "sessions",
        widgetType: "kpi",
        operation: "count",
        filterField: "status",
        filterOperator: "equals",
        filterValue: "active",
        color: "blue",
        isPinnedToDashboard: true
      },
      {
        id: "def-sessions-toggle-grid",
        title: "Dashboard Session List",
        category: "sessions",
        collection: "sessions",
        widgetType: "switch",
        operation: "count",
        switchActionType: "app_setting",
        switchStateKey: "section_sessionsTable",
        switchLabelOnKey: "reports.widgets.switchVisible",
        switchLabelOffKey: "reports.widgets.switchHidden",
        color: "violet",
        isPinnedToDashboard: false
      },
      {
        id: "def-sessions-list",
        title: "Active Sessions List",
        category: "sessions",
        collection: "sessions",
        widgetType: "sessions-list",
        operation: "count",
        color: "blue",
        isPinnedToDashboard: true
      }
    ];
