import type { CustomWidget } from "./pinnedWidgetTypes";

export const sessionsWidgetSeeds: CustomWidget[] = [
  {
    id: "def-card-admin-sessions",
    title: "",
    titleKey: "widget.title.activeSessions",
    category: "sessions",
    collection: "sessions",
    widgetType: "card",
    operation: "count",
    filterField: "status",
    filterOperator: "equals",
    filterValue: "active",
    icon: "CalendarCheck",
    color: "blue",
    subTextType: "fixed",
    fixedSubText: "",
    fixedSubTextKey: "widget.subtitle.activeSessions",
    trend: 0,
    trendType: "database",
    role: "admin",
    isPinnedToDashboard: false,
  },
  {
    id: "def-card-admin-classes",
    title: "",
    titleKey: "widget.title.activeClasses",
    category: "sessions",
    collection: "sessions",
    widgetType: "card",
    operation: "count",
    icon: "BookOpen",
    color: "violet",
    subTextType: "fixed",
    fixedSubText: "",
    fixedSubTextKey: "widget.subtitle.allActiveClasses",
    trend: 0,
    trendType: "database",
    role: "admin",
    isPinnedToDashboard: false,
  },
  {
    id: "def-card-teacher-classes",
    title: "",
    titleKey: "widget.title.myClasses",
    category: "sessions",
    collection: "sessions",
    widgetType: "card",
    operation: "count",
    icon: "BookOpen",
    color: "violet",
    subTextType: "fixed",
    fixedSubText: "",
    fixedSubTextKey: "widget.subtitle.activeClassesCount",
    trend: 0,
    trendType: "database",
    role: "teacher",
    isPinnedToDashboard: false,
  },
  {
    id: "def-card-teacher-sessions",
    title: "",
    titleKey: "widget.title.sessionsToday",
    category: "sessions",
    collection: "sessions",
    widgetType: "card",
    operation: "count",
    icon: "CalendarCheck",
    color: "blue",
    subTextType: "fixed",
    fixedSubText: "",
    fixedSubTextKey: "widget.subtitle.fromActiveSessions",
    trend: 0,
    trendType: "database",
    role: "teacher",
    isPinnedToDashboard: false,
  },
  {
    id: "def-sessions-count",
    title: "",
    titleKey: "widget.title.activeSessions",
    category: "sessions",
    collection: "sessions",
    widgetType: "kpi",
    operation: "count",
    filterField: "status",
    filterOperator: "equals",
    filterValue: "active",
    color: "blue",
    isPinnedToDashboard: true,
  },
  {
    id: "def-sessions-toggle-grid",
    title: "",
    titleKey: "widget.title.dashboardSessionList",
    category: "sessions",
    collection: "sessions",
    widgetType: "switch",
    operation: "count",
    switchActionType: "app_setting",
    switchStateKey: "section_sessionsTable",
    switchLabelOnKey: "reports.widgets.switchVisible",
    switchLabelOffKey: "reports.widgets.switchHidden",
    color: "violet",
    isPinnedToDashboard: false,
  },
  {
    id: "def-sessions-list",
    title: "",
    titleKey: "widget.title.activeSessionsList",
    category: "sessions",
    collection: "sessions",
    widgetType: "sessions-list",
    operation: "count",
    color: "blue",
    isPinnedToDashboard: true,
  },
];
