import { useMemo } from "react";
import {
  applyRelationshipOptionOrder,
  deriveRelationshipOptionsFromPairs,
  resolveRelationshipPairs,
} from "@mms/shared";
import type { ContactConfigContextType } from "@/lib/contacts/contactConfigContextTypes";
import { getFallbackCountryCode } from "@/lib/contacts/contactI18n";
import type { ContactsConfigResult } from "@/lib/contacts/useContactStandardConfig";

/**
 * Builds ContactConfig context value.
 * Relationship-type options are derived from the fixed system pair catalog
 * (`resolveRelationshipPairs` → Parent/Child, Husband/Wife, Guardian/Dependent).
 * Lookups kind `relationships` remains a write mirror only.
 */
export function useContactConfigProviderValue(
  config: ContactsConfigResult,
): ContactConfigContextType {
  const {
    settings: fieldConfig,
    formTabsReady,
    prefs,
    updateConfig,
    updateConfigAsync,
    updatePrefs,
    updatePrefsAsync,
    enabledTabIds,
    requiredTabIds,
    fields,
    isTabFieldEnabled,
    isTabFieldRequired,
    genders,
    socialPlatforms,
    phoneLabels,
    emailLabels,
    addressLabels,
    countryCodes,
    countryCodesMap,
    educationDegrees,
    employmentTypes,
    skillCategories,
    skillProficiencies,
    lookupsLoading,
    lookupsError,
    columnRegistry,
    availableColumns,
    visibleColumns,
    updateGenders,
    updateSocialPlatforms,
    updateRelationships,
    updatePhoneLabels,
    updateEmailLabels,
    updateAddressLabels,
    updateEducationDegrees,
    updateEmploymentTypes,
    updateSkillCategories,
    updateSkillProficiencies,
    updateCountryCodes,
    updateColumnRegistry,
    updateUserColumnLayout,
    isColumnVisible,
    getColumnWidth,
    setColumnWidth,
    systemSortOptions,
  } = config;

  const defaultPhoneCountryCode = useMemo(
    () => getFallbackCountryCode(prefs, countryCodesMap, countryCodes),
    [countryCodes, countryCodesMap, prefs],
  );

  /** Form Relationship-type dropdown — fixed system catalog (Parent/Child, …). */
  const resolvedRelationships = useMemo(() => {
    const derived = deriveRelationshipOptionsFromPairs(
      resolveRelationshipPairs(prefs.relationshipPairs),
    );
    return applyRelationshipOptionOrder(derived, prefs.relationshipOptionOrder);
  }, [prefs.relationshipPairs, prefs.relationshipOptionOrder]);

  return useMemo(
    () => ({
      fieldConfig,
      formTabsReady,
      prefs,
      updateConfig,
      updateConfigAsync,
      updatePrefs,
      updatePrefsAsync,
      enabledTabIds,
      requiredTabIds,
      fields,
      isTabFieldEnabled,
      isTabFieldRequired,
      genders,
      socialPlatforms,
      relationships: resolvedRelationships,
      phoneLabels,
      emailLabels,
      addressLabels,
      countryCodes,
      countryCodesMap,
      educationDegrees,
      employmentTypes,
      skillCategories,
      skillProficiencies,
      lookupsLoading,
      lookupsError,
      defaultPhoneCountryCode,
      columnRegistry,
      availableColumns,
      visibleColumns,
      updateGenders,
      updateSocialPlatforms,
      updateRelationships,
      updatePhoneLabels,
      updateEmailLabels,
      updateAddressLabels,
      updateEducationDegrees,
      updateEmploymentTypes,
      updateSkillCategories,
      updateSkillProficiencies,
      updateCountryCodes,
      updateColumnRegistry,
      updateUserColumnLayout,
      isColumnVisible,
      getColumnWidth,
      setColumnWidth,
      systemSortOptions,
    }),
    [
      fieldConfig,
      formTabsReady,
      prefs,
      updateConfig,
      updateConfigAsync,
      updatePrefs,
      updatePrefsAsync,
      enabledTabIds,
      requiredTabIds,
      fields,
      isTabFieldEnabled,
      isTabFieldRequired,
      genders,
      socialPlatforms,
      resolvedRelationships,
      phoneLabels,
      emailLabels,
      addressLabels,
      countryCodes,
      countryCodesMap,
      educationDegrees,
      employmentTypes,
      skillCategories,
      skillProficiencies,
      lookupsLoading,
      lookupsError,
      defaultPhoneCountryCode,
      columnRegistry,
      availableColumns,
      visibleColumns,
      updateGenders,
      updateSocialPlatforms,
      updateRelationships,
      updatePhoneLabels,
      updateEmailLabels,
      updateAddressLabels,
      updateEducationDegrees,
      updateEmploymentTypes,
      updateSkillCategories,
      updateSkillProficiencies,
      updateCountryCodes,
      updateColumnRegistry,
      updateUserColumnLayout,
      isColumnVisible,
      getColumnWidth,
      setColumnWidth,
      systemSortOptions,
    ],
  );
}
