name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-typecheck:
    runs-on: ubuntu-latest
    env:
      PUPPETEER_SKIP_DOWNLOAD: 'true'
      JWT_SECRET: 'e2e-test-jwt-secret-key-at-least-32-chars-long'
      DATABASE_URL: 'postgres://postgres:postgres@localhost:5432/mms'
    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v6
        with:
          node-version: 26

      - run: pnpm install --frozen-lockfile

      - name: Start PostgreSQL and Setup Database
        run: |
          sudo systemctl start postgresql.service
          pg_isready
          sudo -u postgres psql -c "ALTER USER postgres PASSWORD 'postgres';"
          sudo -u postgres psql -c "CREATE DATABASE mms;"

      - run: pnpm typecheck

      - name: Install Playwright Browsers
        run: pnpm --filter e2e-tests exec playwright install chromium

      - run: pnpm test

      - run: pnpm lint
        working-directory: apps/frontend

      - run: pnpm lint
        working-directory: apps/backend

